### ISSUE TITLE
What do I do with this?

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#1005]
I moved all members of a family to another family, so the system archived the family.
Now when I log in to Jethro I have a 'Note for immediate action'.
Clicking either link just goes to the family record!
Did I maybe break something when I manually deleted all those accidentally created notes from the database recently?

**Comment by tim-pearce** [comment]
When I 'cheat' and go directly to the note, all it shows is a heading 'Editing Note for ******** Family'.
For now, I have gone into the database and given it a status of 'complete'.
I was able to manually add and edit a person note for myself.
Ditto for a family note for my own family.
If I go to some family note, then 'edit original' I can edit the URL to access the problem note and change it's status!
There are no errors in the log. Could the problem be with trying to access a note on an archived family?

**Comment by tbar0970** [comment]
Archived families (and persons) are still visible if you want to look at them.
If you click a link from the homepage and it takes you to the family record, you should then be able to switch to the "notes" tab to see the relevant note ?

**Comment by tbar0970** [comment]
Perhaps when you were deleting things in the database you did delete a record from abstract_note but left one behind in family_note ?
