### ISSUE TITLE
Error when sms.log written to for the first time

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1006]
When ENABLE_SMS is enabled, and SMS_SEND_LOGFILE points to a `sms.log` file to record SMS sendings to - if `sms.log` doesn't exist Jethro throws an error:

```
filesize(): stat failed for /home/jethro/accounts/ccu/logs/sms.log
Line 275 of /home/jethro/code/2.34.1/app/include/sms_sender.class.php
```
The `sms.log` is created, and the error doesn't recur, so it's just a minor annoyance.

**Comment by tbar0970** [comment]
It now creates the file if it can. But if directory permissions don't allow for that, the problem remains.
