### ISSUE TITLE
Error when you run document merge on SOME persons shown in a report

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#1009]
View a report
Tick SOME of the persons but not all
Mail merge a document

```
Undefined offset: 7 
Line 254 of /home/jethro/code/2.34.1/app/calls/call_document_merge.class.php
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
```

It seems like the code is making the assumption that all persons in the report will be part of the merge

**Comment by tim-pearce** [comment]
My version, which has that same code does not get that error.

**Comment by tim-pearce** [comment]
I don't have a running copy of version 2.34.1.
I can only assume that line 248,249 is returning data for all persons.
In that case replace 
`$merge_data[$val] += $data;`
with
`if (isset($merge_data[$val])) {`
`  $merge_data[$val] += $data;`
`}`
