### ISSUE TITLE
Making a an admin login 'inactive' does not stop the person receiving system admin emails.

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#1033]
I recently enabled 2FA (which is fantastic - THANK YOU!) and now, when a change is made to a person's mobile number (presumably only a person with an admin login?) all the 'system admins' are notified. 

However system admins (with their login set to 'inactive') also receive an email notification (in my case, some past staff)

Turns out, disabling their login did not disable their permissions. I needed to go into each person and view their 'Accounts Tab' and then uncheck all the boxes ... 

I reckon it would be reasonable for permission to be un-checked by default when a login account is made 'inactive'. Either that, or system admin notifications should only send to active accounts?

**Comment by tbar0970** [comment]
Thanks for reporting. The notifications should only go to active accounts.

**Comment by s4069b** [comment]
Actually, yes, that makes more sense (than unchecking permissions).
