### ISSUE TITLE
Contact List DOCX export has %SYSTEM_NAME% and %MONTH% untranslated tokens

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1054]
The `.docx` contact list header is broken in Jethro 2.34.1:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/9aa96c5f-b6b1-4d80-bb62-832e880f0d79)

To replicate:
-  Families -> Contact List
- Pick an opt-in group and click `Show Results`
- Click `Download as: DOCX`

**Comment by jefft** [comment]
It seems I broke this in https://github.com/tbar0970/jethro-pmm/commit/08b16ff0b34b9d74a0ca4be466ef975e512ea1c5 - the temp file must have a `.docx` extension. I can't remember why those particular changes prevented double tempfiles being created..

**Comment by tbar0970** [comment]
Is it just those two keywords that are unreplaced, or is the whole content missing?
Not sure how the temp filename change would cause the former.

**Comment by jefft** [comment]
> Is it just those two keywords that are unreplaced, or is the whole content missing?

Just the keywords.

> Not sure how the temp filename change would cause the former.

We pass the temp filename into `ODF_Tools::replaceKeywords` which checks the filename extension to infer type:

https://github.com/tbar0970/jethro-pmm/blob/469a8011064217d20311c9c4ff23e9d3bea60e41/include/odf_tools.class.php#L67

See proposed fix in https://github.com/tbar0970/jethro-pmm/pull/1096
