### ISSUE TITLE
Editing group memberships should be granted by 'Groups - add/edit/delete' permission

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1075]
Jethro has a **Groups - add/edit/delete** permission:

![image](https://github.com/user-attachments/assets/eccbc8e1-35dc-4a50-90f4-cbaa28b52599)

A long-standing quirk of Jethro is that in order to edit group *memberships*, you need the `Persons and Families - add/edit/group` permission, not the `Groups - add/edit/delete` permission.

This came up 9 years ago on #82. Tom explained:

> The intention is that you only need the "persons & families - add/edit/delete" permission to add or remove people from a group. A person's group memberships are seen as a property of the person.
> The "groups - add/edit/delete" permission is for creating groups, changing their properties or deleting them.
> The idea is that the latter is more of an administrator type action.

I think it's time to revisit this, and change Jethro so that group membership is governed by the `Groups` permission. See attached PR.

There are three arguments for doing so:

### It makes much more sense

I think it's fair to say that "edit a group" means, to most people, "edit the group memberships".  It is completely unintuitive that "a person's group memberships are seen as a property of the person". Multiple people across 2 churches (that I'm aware of) have reported this as a bug. If a permission doesn't do what 99% of people think it does - then that *is* a bug.

### It makes Jethro more useful

As I said on #82:
> managing group memberships is a frequent operation, and frequently delegated to non-administrators. In our case we have dozens of home group leaders and ministry leaders, all of whom may need to keep their Jethro groups up-to-date. We don't want these dozens of people to be able to edit person records OR group records - just memberships.

Being able to grant only a membership-editing permission, without a person-editing-permission, is exactly what we want for group leaders! Conversely there is no benefit (that I can see) in having a permission to add/delete groups without the ability to populate them. Tying membership-editing to person-editing was bad design. Fixing it addresses a real use-case.

### It clears up Jethro bugs

Right now (Jethro 2.35.1), someone with only `Groups - add/edit/delete` permission sees:

![image](https://github.com/user-attachments/assets/d6e92dfe-920a-4bb3-930d-95872ce995fc)

Adding groups works, but clicking 'Edit' or 'Delete' results in 'Undefined view' error:

![image](https://github.com/user-attachments/assets/3451bf08-bcd8-41d9-8eb5-ec48eebbd69b)

This is because the 'Edit group' view (also called by 'Delete') check for the `EDITPERSON` permission, rather than `EDITGROUP` permission:

https://github.com/tbar0970/jethro-pmm/blob/27cf2545f364e75315213eb603a6d0921a09d010/views/view_0_edit_group.class.php#L11-L14

So the `Groups - add/edit/delete` permission would more accurately be called the `Groups - add` permission.

### Summary

Tying group memberships to the `Group` permission, rather than `Person` will make Jethro more intuitive, more useful and less buggy.

As for implementation:

The permissions code change is simple, but I think we also need an upgrade SQL script that grants `Groups - add/edit/delete` to everyone currently granted `Persons & families - add/edit`.  Because:
 - Prior to the upgrade, people with only `Persons & families - add/edit` permission were able to edit memberships. After the upgrade they won't be able to, unless our upgrade SQL gives it to them the extra permission.
 -  Due to the bugs noted above, the `Persons & families - add/edit` permission currently also grants people a sort of `Groups - edit/delete` permission. When the bug is fixed, if we want those same users to be able to edit/delete groups, we must grant them the extra permission.

The SQL upgrade is part of the PR.

**Comment by tbar0970** [comment]
OK...
If I trust Johnny Smith to add people to groups, but I don't trust him not to mess up the groups structure by adding and deleting groups, this leaves me with no way to grant the former without the latter.
But it sounds like it solves other problems which have come up in real life.
