### ISSUE TITLE
Roster assignments randomly disappear

### ISSUE THREAD

**Issue by sdenness** [tbar0970/jethro-pmm#1077]
I'm finding that people assigned to particular roster roles randomly drop out of the roster.

I email the service run sheet on Monday to all participants. The roster assignments are all correct. Then after making changes to the run sheet (but not the rosters), I print the run sheet again on Saturday, only to discover that one or two people have randomly dropped out of their roles on both the run sheet and the roster. This week I lost one welcomer and two kitchen helpers. This has happened over multiple weeks.

I think it only happens to roster fields that take multiple people. I'm the only one who edits the roster. 

Any suggestions/troubleshooting?

Thanks!

**Comment by jefft** [comment]
Strange. I can edit runsheets displaying rostered multi-person roles just fine. 

Some thoughts/questions:

1. Can you replicate this? What are the steps?
2. Which version of Jethro are you using?
3. Are there any errors in the webserver logs (e.g. apache `error.log`)?

**Comment by tbar0970** [comment]
I think I've encountered this too - see https://github.com/tbar0970/jethro-pmm/issues/1078

**Comment by sdenness** [comment]
> Strange. I can edit runsheets displaying rostered multi-person roles just fine.
> 
> Some thoughts/questions:
> 
> 1. Can you replicate this? What are the steps?
> 2. Which version of Jethro are you using?
> 3. Are there any errors in the webserver logs (e.g. apache `error.log`)?

Sorry, haven't been able to get to this yet, I'll get back to you in a few days.

**Comment by jefft** [comment]
I'd try the following:
 - display all roster assignments in a browser tab
 - apply the SQL in https://github.com/tbar0970/jethro-pmm/issues/1078#issuecomment-2345383727
 - view roster assignments again in a second tab

..and see if the missing roster assignments reappeared. If so, #1078 was the problem.

**Comment by tbar0970** [comment]
I'm going to close this, assuming that #1078 is behind it. Please re-open if needed.
