### ISSUE TITLE
Reports that specify 'status' are empty after 2.36 upgrade

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1080]
I have a Person report that specifies a person status:

![image](https://github.com/user-attachments/assets/796b41ae-3ade-41f0-9385-65a1a40d266e)

After upgrading to 2.36-dev and applying `upgrades/2024-upgrade-to-2.36.sql`, the report returns nothing, because the Status field has lost its value:

![image](https://github.com/user-attachments/assets/8d630fe7-cf5a-4469-a954-7a2b05db7c73)

**Comment by tbar0970** [comment]
For those watching from the sidelines, NB that 2.36 is not yet a complete release!
