### ISSUE TITLE
Deleting a congregation fails if attendance 'Total Headcount' was recorded

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1091]
Jethro allows one to delete a congregation once all members are removed from it:

![image](https://github.com/user-attachments/assets/2ae4af45-f555-45cb-ae05-8c453f49c092)

Any attendance records are left untouched in the database, since they are associated with the person, not the congregation directly.

However, if, while marking attendances, one ever recorded the 'Total headcount':

![image](https://github.com/user-attachments/assets/f318cab7-fe35-4266-b250-3e110fd138c1)

The headcount is associated with the congregation - the `congregation_headcount` table's `congregationid` refers to it.

```sql
MariaDB [jethro]> select * from congregation where id=15;
+----+-----------+----------+--------------+---------------------------+---------------+
| id | long_name | name     | meeting_time | attendance_recording_days | holds_persons |
+----+-----------+----------+--------------+---------------------------+---------------+
| 15 | TestCong  | Testcong |              |                       127 | 1             |
+----+-----------+----------+--------------+---------------------------+---------------+

MariaDB [jethro]> select * from congregation_headcount where date='2024-10-20';;
+------------+----------------+--------+
| date       | congregationid | number |
+------------+----------------+--------+
| 2024-10-20 |             15 |    123 |
+------------+----------------+--------+
```

The congregation appears deletable, but doing so results in "An error occurred. Please contact your system administrator for help.", and an `error.log` entry:
```
AH01071: Got error 'PHP message: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jethro`.`congregation_headcount`, CONSTRAINT `congregation_headcount_congid2` FOREIGN KEY (`congregationid`) REFERENCES `congregation` (`id`)) - Line 481 of /srv/www/jethro/2.35.1/app/include/db_object.class.php
```

**Comment by tbar0970** [comment]
Aha, one more foreign key for congregations.
If somebody really wants to delete a congregation altogether, probably the headcounts should be wiped with it.
So the foreign key should just be changed to ON DELETE CASCADE.

**Comment by jefft** [comment]
> So the foreign key should just be changed to ON DELETE CASCADE.

Yes, that works. PR https://github.com/tbar0970/jethro-pmm/pull/1098.

**Comment by tbar0970** [comment]
Did some digging. It's only systems older than 2015 which had the wrong kind of FK (via upgrade script).
