### ISSUE TITLE
Replace person history serialization with JSON

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1092]
Jethro keeps a history of person changes in `_person.history`. This is done with PHP `serialize()` and `unserialize()`.

It would be nice if Jethro switched to JSON, because:
 - JSON is supported by modern databases. It is sometimes necessary to alter histories programmatically, e.g. to change it structure (https://github.com/tbar0970/jethro-pmm/pull/1083), to undo the result of bugs (e.g. https://github.com/tbar0970/jethro-pmm/issues/1086, https://github.com/tbar0970/jethro-pmm/issues/845). 
 - PHP `serialize()` will serialize a newline to `\r\n` on Windows, and `\r` on *nix. This means that if Jethro deployed on Windows is dumped (`mysqldump`) and imported on a Linux server, you get errors:
```
unserialize(): Error at offset 119 of 1282 bytes
Line 310 of /home/jethro/code/2.35.1/app/include/db_object.class.php
```

**Comment by jefft** [comment]
Hm, there are quite a few fields of type `'serialise`' in `db_objects/*.php`. Unless they can all become JSON it's probably not a good idea for just `_person.history` to be JSON.

For reference, here is what to run on a database created in Windows, to run without errors in Linux:

```sql
update abstract_note SET history = REPLACE(history, '\r\n', '\n') WHERE history LIKE '%\r\n%' ;
update _person SET history = REPLACE(history, '\r\n', '\n') WHERE history LIKE '%\r\n%' ;
update family SET history = REPLACE(history, '\r\n', '\n') WHERE history LIKE '%\r\n%' ;
update action_plan SET actions = REPLACE(actions, '\r\n', '\n') WHERE actions LIKE '%\r\n%' ;
```

**Comment by tbar0970** [comment]
Serlialisation isn't great, though it was a quick and easy solution back in the day. The better solution would be for the history to be stored in different tables altogether - person_history, famil_history etc - not serialised but with one row per change. That is mentioned in another issue. But it's time intensive for no visible benefit to the end user
