### ISSUE TITLE
SMS 2FA fails if the user's mobile number contains spaces

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#1093]
If a person's mobile number contains space separators, and 2FA is required for login, then Jethro breaks on login:

![image](https://github.com/user-attachments/assets/f0fb7a41-40ea-4a7a-95ff-df351513ec44)

The SMS is actually sent, but due to the error the code cannot be entered.

In `sms-2fa.log` one finds an error message. Say the person's mobile number is set to `0402 123 456`, the error will be like:

```
2024-11-03T12:21:27+10:30 ERROR: SMS send failure: Array
(
    [executed] => 1
    [successes] => Array
        (
        )

    [failures] => Array
        (
            [0] => Array
                (
                    [id] => ...
                    [username] => ...
                    ....
    [rawresponse] => {"error":"","messages":[{"destination":"0402123456","id":"91931792","status":"1011","status_text":"Sending...","credits":1}]}
    [error] =>
)

**Comment by jefft** [comment]
The problem is that Jethro uses the mobile number with whitespace (`0402 123 456`) to construct a regex (`$okRegex`) to test the SMS gateway response:

https://github.com/tbar0970/jethro-pmm/blob/469a8011064217d20311c9c4ff23e9d3bea60e41/include/sms_sender.class.php#L276-L277

The gateway response has removed the whitespace (`"destination":"0402123456"`) so doesn't match.

A workaround is to remove whitespaces in people's `mobile_tel` fields:

```sql
update _person set mobile_tel=regexp_replace(mobile_tel, '[[:space:]]\+', '') where mobile_tel like '% %';
```

I will create a PR.

**Comment by tbar0970** [comment]
There should never be spaces in a mobile number saved in Jethro. The code strips them out at all points. Did this system have some DIY imports applied??

**Comment by jefft** [comment]
I don't know the history of the Jethro instance (EJ import from SQL).

There are 2 other EJ instances with whitespace in `mobile_tel`, so there must be some (uncommon) codepath allowing it. Perhaps CSV import?

**Comment by tbar0970** [comment]
I've checked, and CSV import doesn't result in spaces in mobile numbers.
Perhaps it was some DIY SQL at some point?
Anyway the presenting symptom is solved by this PR.
