### ISSUE TITLE
Remove Admin User Accounts

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#112]
I have some people who no longer needs access to the Jethro interface, but still attend the church.
Is there a way to remove these user admin accounts?

It would be handy to be able to delete them (not just inactivate)... Can this be done via the mysql database?

**Comment by tbar0970** [comment]
If they've performed any activity such as creating persons or actioning notes, the user account record needs to be there or else those persons/notes may become invisible.  If you're confident they haven't done anything you could delete the row from the staff_member table in the database, but I would advise against it if you can avoid it.

**Comment by Gibbz** [comment]
Yeah great thanks :)
