### ISSUE TITLE
FR: Allow roster views to be set as visible in members interface but not public interface

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#117]
Currenly, a roster view can either be "public" (visible everywhere including publicly) or "private" (only visible within the staff interface).  It would be useful if a roster cold also be visible to "members" which would show it in the member interface but not the public interface.

**Comment by helpware** [comment]
+1 
Yes great -- if our members can login and see selected private rosters. 

Even better (for us at least). If the Admin could change the /public URL then these pages move from "Public" to "Unpublished" view.  See https://github.com/tbar0970/jethro-pmm/issues/130
