### ISSUE TITLE
SQL erros on new install

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#123]
I'm getting a few SQL errors with a fairly new Jethro install.

For example, if I go to Services->Component library, I get the error:
`_doQuery: [Error message: Could not execute statement] [Last executed query: SELECT service_component_category.id, service_component_category.category_name, service_component_category.runsheet_title_format, service_component_category.handout_title_format, service_component_category.is_numbered_default, service_component_category.show_in_handout_default, service_component_category.show_on_slide_default, service_component_category.length_mins_default FROM service_component_category] [Native code: 1054] [Native message: Unknown column 'service_component_category.is_numbered_default' in 'field list']`

So I assume the issue is there's something missing in my database.

The origin of this may be that I originally installed from the current GIT master, but noticed a few issues. So re-read the documentation and down-graded to the latest stable version. Lots of things are working now (adding people, marking attendance) but not everything.

Any ideas of a way forward? (e.g. could I drop the database, let Jethro create a new one, and then import that data I've entered?)

**Comment by tbar0970** [comment]
Hmm, yes it's because you've installed the latest GIT version and then downgraded.

If you drop the DB and re-install, migrating your existing data will be tricky (Jethro can import a CSV of persons and service components, but not other things).

v2.14 will be coming out in the next week or so, so the best approach might be to wait for that, upgrade your code, and then look through the 2.14 SQL upgrades to see which ones you need to apply and which ones you've already got.

**Comment by funkydan2** [comment]
Thanks so much Tom. I think your proposal sounds good.

**Comment by funkydan2** [comment]
Tom - just a massive thanks for your response, and a note to say that the release that came out last night has resolved all the persons. Your work is a great blessing to a minister in a small church in regional Australia.

Do you have a system for donations from people who don't have a need to sponsor new features?

**Comment by tbar0970** [comment]
Great to hear the fix worked and that Jethro is benefiting your ministry!
We don't have a donations system, but I could suggest some small things you might like to sponsor.
Can you drop me an email - my github user name @gmail.com
