### ISSUE TITLE
Guide to upgrade database?

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#129]
Im just doing an upgrade for the first time and you have this step going to the latest version:
Apply upgrades/2015_upgrade_to_2.14.sql to your mysql database

How does one apply this upgrade on linux? 
Edit: is this the same as run sql from file? - Ran that, worked i guess :)

**Comment by Gibbz** [comment]
ok getting the following error on a few of the admin pages:


SYSTEM ERROR (WARNING)

require_once(/xxxx/www/jethro/views/view_10_admin__4_action_plans.class.php): failed to open stream: No such file or directory
Show Details

Fatal error: require_once(): Failed opening required '/xxxx/www/jethro/views/view_10_admin__4_action_plans.class.php' (include_path='.:/usr/share/php:/usr/share/pear:/xxxx/www/jethro:/xxxx/www/jethro/include/:/xxxx/www/jethro/db_objects/:/xxxx/www/jethro') in /xxxx/www/jethro/include/system_controller.class.php on line 118

**Comment by Gibbz** [comment]
The file doesnt exist
/views/view_10_admin__4_action_plans.class.php

instead in the zip is 
view_10_admin__5_action_plans.class.php

**Comment by vanoudt** [comment]
In terms of those last errors, try logging out and then in again. Got hit by that myself today.

 Would be good to have the db upgrade done automatically in the future.   Until then:
In terms of applying the  Sql, its pretty easy using phpmyadmin, if you've got that handy. Or else try editing the file to add a line at the top reading:
USE DATABASENAME;
Where DATABASENAME is the name of your database.
Then run myself -uMYSQLUSER -pMYSQLPASSWORD < upgrades/2015_upgrade_to_2.14.sql

Or else, just run the SQL, as you say you did :-)

**Comment by tbar0970** [comment]
Or just to extend vanoudt's helpful answer above, you can specify the db on the commandline.
If your mysql database is called myjethrodb
then you can run
`mysql -u MYUSER -p MYPASSWORD myjethrodb < upgrades/2015_upgrade_to_2.14.sql`
- no editing of files needed.

**Comment by tbar0970** [comment]
I've just updated the release notes to mention logging out before upgrade.

**Comment by Gibbz** [comment]
ok cool, thanks! re logged in today and its all working a treat! :+1:
