### ISSUE TITLE
For Privacy Allow Admin to Change Public Link Path

### ISSUE THREAD

**Issue by helpware** [tbar0970/jethro-pmm#130]
Hey Tom @tbar0970 @
Re Public Roster privacy issues (very important for us) https://github.com/tbar0970/jethro-pmm/issues/50 https://github.com/tbar0970/jethro-pmm/issues/117

A simple solution is to allow the Admin to set the \Public link path.
_eg Public URL Path:   [{domain-name}\public]   <-- default_
The link becomes like a Google Site or YouTube "Unpublished" link.
If unguessable nobody can find it except members you share it with.

Add an Optional "PassKey" (so enter public page only if correct PassKey entered)
then the admin has a lot of control over privacy without the hassle of 
making everyone create a personal account or set Nicknames.

## -- Background --

We published our \public link to the public web site and now the search engines have the link.
So we can no longer hide our member names without pulling down the public roster pages.
Try doing a Google search for  "easyjethro.com.au/public" 

Think how Google Sites etc implement security....
A Google Site or YouTube clip can be either be "Public | Unpublished | private (needs login)"

If Admins can set the \public path, then it means the path can be "Unpublished"
(unless someone guesses it or posts it in a public space)

Additionally the admin could set an optional "Passkey".  Without the PassKey you can't get into the public area. Effectively another layer of protection.

This will solve our problems. 
Thanks 
Rob

**Comment by tbar0970** [comment]
How about just making the ID into a hard-to-guess hash?
So an "unpublished" roster might be available at
myjethrosystem.domain.com/public/view=roster&rosterid=a6b636d6e6fa6b636d6e6fa6b636d6e6f

This would be easier to implement, and seems to me like it would provide the same level of protection?

I assume you'd then send this secret URL to your members by email or something?  Of course the security would depend on them not posting the URL as a public bookmark or something!

**Comment by helpware** [comment]
Sounds good. So..
- Each client Jethro site can have a unique public link that cannot be guessed.
- Tech support (you) and not admin can change URL if in the unlikely event it has been compromised

So in Define Rosters View -- Edit Roster XYZ you could we have...
= Name: XYZ
= Is Public: Yes/No   -- available in /public pages and member login
= Enable hidden URL: Yes/No    -- available in special passkey URL and member login
= Show on Running Sheet

Or a tri-state dropdown
= Share: <None>|<Public>|<Unpublished>
   "public" is seen by \public and member login
   "unpublished" is seen by special passkey URL and member login

Yes low security "unpublished" links are emailed to members OR members login to our members only area to get such links. Obviously more sensitive info is fully password protected.

**Comment by tbar0970** [comment]
Thinking about how we could make it even simpler.  

What if we simply added a "public roster secret" setting (editable by server admins).  
If the secret is set in the config file, then 
* whenever you access any public roster, you need to include it in the URL, like this:
http://mysystem.easyjethro.com.au/public/?view=display_roster&rosterid=3&secret=ab40wjwn
* the public site wouldn't list any rosters - it would simply say "Please contact the church for access to online rosters".

Would that meet your needs?  It would be the quickest way to get something working.

**Comment by helpware** [comment]
Public Secret flag with string to set path fragment -- brilliant. 
And we can change the path if the need arose.

Yep this would certainly meet our needs.
