### ISSUE TITLE
Tell Search Engines not to Index or follow Jethro public pages 

### ISSUE THREAD

**Issue by helpware** [tbar0970/jethro-pmm#131]
To help protect user names add meta tag to tells search engines not to index 
or follow links for the public pages 

<meta name="robots" content="noindex,nofollow">
a ref:  http://www.metatags.info/meta_name_robots

Basically I see no reason to allow search engines or Web Archives to 
access and publish church member names (do you?). 
Thanks 
Rob

**Comment by tbar0970** [comment]
Sounds like we might as well add
`<meta name="robots" content="noindex, nofollow">`
to the whole site?

**Comment by helpware** [comment]
Yes sure. But robots can only crawl into the public pages where the link has been shared on the public web page.

**Comment by tbar0970** [comment]
+1
