### ISSUE TITLE
Attach photo to family as well as person

### ISSUE THREAD

**Issue by howardgrigg** [tbar0970/jethro-pmm#137]
When we produce our contact booklet we do so by family (currently done manually). We have previously included a family photo next to each entry. Obviously Jethro is setup for individual photos but I imagine it wouldn't be overly complex to add a photo field to the family table as well. This would then allow a photo to be included in the Family 'Contact List'. 

Thoughts?

**Comment by tbar0970** [comment]
Another possibility is just to include all the individual photos for each family in the contact list.

**Comment by tbar0970** [comment]
Done in 2e4b2b7f925c4eab5c7f35a1daeb504cc2542832 and related commits
