### ISSUE TITLE
SMS link in reports doesn't work

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#139]
## Steps to reproduce:
Set up system with SMS gateway
Run a person report that includes mobile numbers
Mobile numbers in results show the phone and envelope icons - hmm.
Click on the envelope icon - page reloads to <base url>/undefined.

## Comments:
It's probably better just to list unadorned mobile numbers in report results ?  Reports are rarely used on phones, so the tel link is not very useful, and to send SMS you can use the bulk action at the bottom.  The tel and envelope buttons are intended just for the view-single-person page.

**Comment by vanoudt** [comment]
Personally, I find the ability to send non-bulk SMSes from reports very useful - use it every week like this. I have a report of those who weren't at church, and send them a "how are you going?" sms. I like to tailor this to the different persons.

This bug has been irritating me for a while, so finally got around to fixing it. The big issue was that the cells were clickable - pull request #141 adds the ability to disable cell-clickability for the mobile_tel column.

As for phone numbers - yeah, probably not much use on computers. Except for those who have skype/some other VOIP plugin installed. Personally - I'd leave it in...

**Comment by tbar0970** [comment]
Fixed in @vanoudt 's SMS-AJAX rework.
