### ISSUE TITLE
FR: Edit system configuration within Jethro

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#15]
The DB credentials will always need to be in the conf.php file

But we could move all the other config into a settings table in the DB, so that it can be edited from within jethro.  Saves on system-administrator effort.

Migration plan could be:

On init:  Select all from settings table, and for any setting not already defined as a constant, define it as a constant.  For any setting that is already defined as a constant, define(<setting_name>_DEFINED_IN_FILE).

In the settings page:  
For each setting, 
if <setting_name>_DEFINED_IN_FILE is set:
- save the constant value to the DB
- render a read-only interface
- show an explanatory message inviting them to remove it from the conf.php file

else
- show editable interface.

**Comment by vanoudt** [comment]
Have started working on this...

**Comment by tbar0970** [comment]
Great!  Let me know if the backwards compatibility concept above needs further explanation (backwards compatibility will be important).
