### ISSUE TITLE
a few bugs from updating to version 2.14

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#151]
This is a bit of a complicated one. I had some issues upgrading to version 2014. When I did so, I got lots of error messages so I rolled back to the previous version and reloaded the backup of the SQL database I had just made. 

This caused lots of errors, it could find service details, but no people or groups from the backup version. 

I looked at the tables in the database, and the tables 'people' and 'groups' were empty. But down the bottom there were two tables '_people' and '_groups' where all our details were. I renamed the tables beginning with '_' and deleted the empty ones, and things seemed to work. 

Except when someone other than me tried to log on (or when I tried to log in from a new device), we got errors. 

Then, instead of deleting the tables beginning with '_' I copied all the contents to the other files. This time things worked fine and people could log in. I think upgraded to version 2.14 and it worked this time. 

Except, there are there problems: 

1. I can put data in our custom fiends to any people created prior to the whole mess, but get this error if I do it with anyone created after (changing their default fiends, eg contact details is fine)

SYSTEM ERROR (ERROR)

Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: INSERT INTO custom_field_value (personid, fieldid, value_text, value_date, value_optionid) VALUES (289,14,'2',NULL,NULL)] [Native code: 1452] [Native message: Cannot add or update a child row: a foreign key constraint fails (`christch_jethro`.`custom_field_value`, CONSTRAINT `customfieldvalue_personid` FOREIGN KEY (`personid`) REFERENCES `_person` (`id`) ON DELETE CASCADE)]

2. in groups, all archived members are displayed (greyed out) by default, then if I click 'show archived members' they're removed, then they reappear when I click 'hide archived members. 

3. in the members area, I can see my families details and edit them. I can see rosters. There is a new heading 'my groups' that has everyone listed with contact details, BUT if I click on the 'people' heading, there are no results. 

I've updated to 2.14.2, but these problems remain. 

Sorry for being such a pain, I would appreciate any help you could give, or if you could point me to any help that would be much appreciate too! 

Andrew.

**Comment by tbar0970** [comment]
Hi Andrew

Hmm, this has got pretty messy.  It's actually correct that person and person_group appear to be empty and that there are tables called _person and _person_group.  The ones without the underscores are views, which show the persons/groups that the current user has access to.  If you're just viewing via phpmyadmin or whatever, they will appear empty.

I think you must have done something wrong when you reverted your database to your backup.  Did you drop the database first and re-create it before importing the SQL backup?

I don't think we can patch up your current database, but we should be able to do the upgrade properly from your original backup.

**Comment by agoddard77** [comment]
Hi Tom, thanks for your help. Shows how little I know!

At first I went to cpanel/backup and chose 'restore a mysql database
backup'. That didn't work. so then I deleted the database and user and
tried restoring again and created a new user. that didn't work either until
I did the thing with the tables, that I now realise I shouldn't have!

If I send you the original backup and our login details, would you mind
having a look at it? Could we reimburse you for your time?

Andrew.

Assistant Minister,
Christ Church Mortdale

(m) 0401 097 162 (w) 02 9585 2925

**Comment by tbar0970** [comment]
I'll get in touch directly.
