### ISSUE TITLE
Email parsing problem

### ISSUE THREAD

**Issue by NeilAtw** [tbar0970/jethro-pmm#16]
Hi Tom,
I've just struck a new problem with the current version of Jethro:
I have a new person to enter, their email address is a little different: xxxxx@circle.education  
Jethro won't accept this - I assume because it's one of the newer tld's 

Easy to fix?

Cheers

Neil A.
(PS, sorry, no idea how to add the labels, etc to this post...)

**Comment by tbar0970** [comment]
Yep should be a simple fix

**Comment by tbar0970** [comment]
Also need to add support for an email with localpart ending in -

**Comment by tbar0970** [comment]
Fixed
