### ISSUE TITLE
Roster exceptions

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#166]
If I configure a roster role with a volunteer group,
then when I edit assignments for that role, I get to choose from a dropdown box of the people in that group.
On special occasions I might want to allocate somebody else to that role on a particular date (eg a guest preacher).

So it would be useful to have an "other" option in the dropdown box,
which opens a modal where I can search for any person to assign
(like I do for roles that don't have volunteer groups).

**Comment by alwr** [comment]
+1 for me.

However, are you going to add a guest preacher to Jethro just to add them to a roster?  Could the 'other' modal offer person suggestions, but also allow free text? This would be similar to how the new service planning features let you pull personnel details from a roster, but they can be overridden with free text.
