### ISSUE TITLE
Email bulk action doesn't work on iphone

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#175]
To reproduce:
- Use iphone
- Navigate to view a group
- Select some (or all) people from the member list
- Down the bottom choose "with selected persons... send email"
- Click Go to proceed with sending email
- Alert box:  "Jethro tried but could not open a popup window... please disable your popup blocker..."

Mobile safari has some rule where window.open must be called from a 'user action' or somesuch..?

**Comment by tbar0970** [comment]
Also when you use the direct link "email members", the modal window is too big on mobile and for some reason you can't scroll across to the left edge of the modal content.

**Comment by GatesheadBen** [comment]
The "modal window is too big" is because the JS applies to the responsive design whether wide or narrow.  I have commented out 
//			'margin-left': function () {
//				return -($(this).width() / 2);
//			}

in jethro-2.18.2.js which makes the modal off centre on wide screens but useable on narrow.

**Comment by tbar0970** [comment]
Modal sizing is in jethro.js here:
```
	$('.modal.autosize').on('shown', function() {
		$(this).css({
			width: 'auto',
			'margin-left': function () {
				return -($(this).width() / 2);
			}
		});
	});
```
