### ISSUE TITLE
JETHRO INSTALLATION ON WINDOWS PC GIVING FATAL ERROR

### ISSUE THREAD

**Issue by ikforson** [tbar0970/jethro-pmm#187]
Please I have been trying to install Jethro-PMM on a windows machine using XAMPP. I have thoroughly followed all the steps on below link but I still have difficulties accessing the login page. 
http://www.virtualpreacher.org/church-software-and-technology/install-jethro-pastoral-ministry-manager-windows/.  

The error I get is [Fatal error: Call to undefined function: MDB2_Driver_mysql::raiseError(). in C:\xampp\htdocs\jethro\MDB2.php on line 1936].

I really need to get Jethro to work and I need help. Thanks

**Comment by vanoudt** [comment]
Hmmm - that's strange. From the about page, try unzipping [this file](http://sourceforge.net/project/showfiles.php?group_id=192555&package_id=247862&release_id=544189) into your Jethro directory...

**Comment by ikforson** [comment]
vanoudt,
Thanks for your response and your readiness to help. I have done exactly what you have asked me to do and I am getting the above Fatal Error message. It looks like I need to do something to the MDB2.php file which I have no idea.

**Comment by vanoudt** [comment]
Hmmm - as a linux guy, might be a bit out of my depth here. Had a look at that line in MDB2.php - all it is saying is that it can't load the mysql mdb2 driver. Just checking, do you have a folder in your jethro directory called "MDB2", and another under the "MDB2" folder called "Driver"?

**Comment by vanoudt** [comment]
I was about to send you to "http://www.virtualpreacher.org/church-software-and-technology/install-jethro-pastoral-ministry-manager-windows/" - but I see that you've already commented there!

**Comment by vanoudt** [comment]
You could also have a look here: http://davehiren.blogspot.com.au/2011/04/how-to-install-or-uninstall-pear.html

What you'd want to do is to follow his instructions, and then install MDB2 and MDB2_Driver_mysql.

I've copied (and modified) his instructions here. Note, I don't have a windows machine, so can't guarantee that it'll work...
First off, remove the MDB2.php file and MDB2 directory from your Jethro directory.
Then: 

 > First of all go to folder c:\xampp\php and find the file pear.bat. In my case I installed xampp in c drive. If its not in c drive go to the correct path and find pear.bat file.
> 
> Open that file in Notepad or Notepad++ to edit. Find the following line in in that file.
> 
> IF “%PHP_PEAR_INSTALL_DIR%”==”" SET “PHP_PEAR_INSTALL_DIR=\xampp\php\pear”
> 
> 
> Add following line above this line.
> 
> SET “PHP_PEAR_INSTALL_DIR=C:\xampp\php\PEAR”
> 
> 
> Now include c:\xampp\php to PATH environment variable.
> 
> In windows vista you can find it here.
> 
> Start->Control Panel->System and Maintenance->System->Advanced System Settings->Environment Variable
> 
> That's it and now go to command prompt and type command pear. You will see all the possible options for that command.
> 
> Use following command to install pear package.

pear install -o MDB2
pear install -o pear install MDB2_Driver_mysql

**Comment by ikforson** [comment]
I actually followed the steps provided on the www.virtualpreacher.org website. On the MDB2 folder inquiry, I only have "MDB2" folder in the jethro directory. I don't have "MDB2" in the "Driver" folder.

**Comment by ikforson** [comment]
Hello Nicholas,

When I issue the pear install -o MDB2 command, the installation fails as
indicated below. I am suspecting that I am not getting the [Now include
c:\xampp\php to PATH environment variable.] part correct. I have  attached
a screen print of  how I included c:\xampp\php to PATH environment
variable. Please see if you can help. Thanks

Installation Error
C:\Users\ikforson>pear install -o MDB2
No releases available for package "pear.php.net/MDB2"
install failed

Regards,
Isaac

**Comment by vanoudt** [comment]
Hmmmm.... Looks lime it has fot the pear command running okay, so I'd guess the path is fine. This is getting a bit beyond me, I'm afraid to say 😢. But one more suggestion, culled from stackoverflow:

Try replacing the install command with this:

pear clear-cache
pear install -a MDB2
pear install -a MDB2_Driver_mysql

**Comment by ikforson** [comment]
Hmmmm.... you have really done your best. The "pear clear-cashe" command gives me below result.

C:\Users\ikforson>pear clear-cache
C:\Users\ikforson\AppData\Local\Temp\pear\cache does not exist or is not a directory.

I am grateful for all the suggestions you have given me. I am running Windows 10, could it be a factor?

**Comment by tbar0970** [comment]
I would ditch trying to get PEAR to work and just use the MDB2 dropin file that Nicholas mentioned above - download from http://sourceforge.net/project/showfiles.php?group_id=192555&package_id=247862&release_id=544189

Unzip this into your Jethro folder - it should result in an MDB2.php file AND an MDB2 folder in your Jethro folder.

**Comment by ikforson** [comment]
I have MDB2.php file AND an MDB2 folder (Driver folder, Date.php file, Extended.php file, Iterator.php file, LOB.php file) in my jethro folder but I am still getting an error instead of the login page.

Fatal error: Call to undefined function: MDB2_Driver_mysql::raiseError(). in C:\xampp\htdocs\jethro\MDB2.php on line 1936

**Comment by tbar0970** [comment]
Ok, two things to check
1) does your MDB2/Driver folder have a file mysql.php in it?  It should.  If not, unzip the file linked above again.
2) what version of PHP is your XAMPP install running?  I'm starting to wonder if MDB2 (which is a bit old) might not be compatible with super-recent PHP versions.

**Comment by ikforson** [comment]
Thanks for all the suggestions. I am hopeful that a solution is just near.
1. I already have the mysql.php file in the MDB2/Driver folder.
2. The xampp version I installed is, **xampp-portable-win32-5.6.20-0-VC11**-installer. I suppose this should work as well for 64bit operating system, right? Please if you know a version that will work for me, let me know about it. Thanks

**Comment by tbar0970** [comment]
Sorry this dropped off my radar.  
The next thing I can think to suggest is to try a XAMPP release that has a slightly older PHP version - perhaps 5.4 or 5.5.  Possibly the MDB2 PEAR library has some incompatibility with php 5.6.
There are lots of people running jethro successfully on XAMPP.
