### ISSUE TITLE
FATAL ERROR-INSTALLATION

### ISSUE THREAD

**Issue by jsoftwares** [tbar0970/jethro-pmm#188]
Hello friends,
I tried to install Jethro on cpanel and immediately i type the url to start installation, I got this error:

Warning: require_once(/home/exchange/public_html/jethro/include/init.php): failed to open stream: No such file or directory in /home/exchange/public_html/jethro/index.php on line 39

Fatal error: require_once(): Failed opening required '/home/exchange/public_html/jethro/include/init.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/exchange/public_html/jethro/index.php on line 39

Please, kindly assist.
Thanks

**Comment by tbar0970** [comment]
Hi there,
This is an usual error and sounds like you probably don't have all the Jethro files in place.  In your Jethro folder there should be a folder called "include" with a bunch of files in it, a folder called "db_objects" with a bunch of files in it, ditto "views" and various others.  Can you check these are all there - if not you'll need to unzip the ZIP file again.

If the files are there it could be a permissions problem, but this is unusual for a cpanel system.

Tom

**Comment by jsoftwares** [comment]
Thanks Tom for your response.

I would check for these file when I get back to my PC. 
I downloaded the files from github; hope this is fine?

**Comment by tbar0970** [comment]
You should use the release ZIP from https://github.com/tbar0970/jethro-pmm/releases rather than downloading the raw source code.

**Comment by jsoftwares** [comment]
Hi Tom,
when i used the files (jethro-2.15.0.zip) from the URL above, I now get the below error when I try to install;
Warning: ini_set() has been disabled for security reasons in /home/exchange/public_html/portalcevi/include/init.php on line 18

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/exchange/public_html/portalcevi/include/init.php:18) in /home/exchange/public_html/portalcevi/include/init.php on line 23

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/exchange/public_html/portalcevi/include/init.php:18) in /home/exchange/public_html/portalcevi/include/init.php on line 23

Warning: Cannot modify header information - headers already sent by (output started at /home/exchange/public_html/portalcevi/include/init.php:18) in /home/exchange/public_html/portalcevi/include/init.php on line 38

What possibly is the problem?

**Comment by tbar0970** [comment]
OK, that's a different problem.  Your hosting provider has prohibited PHP scripts like Jethro from changing PHP settings.  We can probably work around this.
Edit the include/init.php file and replace all its contents with the text below.

`<?php
if (file_exists(dirname(__FILE__).'/version.txt')) {
	define('JETHRO_VERSION', trim(file_get_contents(dirname(__FILE__).'/version.txt')));
} else {
	define('JETHRO_VERSION', 'DEV');
}

$path_sep = defined('PATH_SEPARATOR') ? PATH_SEPARATOR : ((FALSE === strpos($_ENV['OS'], 'Win')) ? ';' : ':');
set_include_path(ini_get('include_path').$path_sep.JETHRO_ROOT.$path_sep.JETHRO_ROOT.'/include/'.$path_sep.JETHRO_ROOT.'/db_objects/');

function __autoload($class_name) {
	 include_once strtolower($class_name) . '.class.php';
}

// set error level such that we cope with PHP versions before and after 5.3 when E_DEPRECATED was introduced.
$error_level = defined('E_DEPRECATED') ? (E_ALL & ~constant('E_DEPRECATED') & ~constant('E_STRICT')) : E_ALL;
error_reporting($error_level);
@ini_set('display_errors', 1);

session_set_cookie_params(NULL, parse_url(BASE_URL, PHP_URL_PATH));
if (session_id() == '') {
	session_name('JethroSession');
	session_start();
}
require_once JETHRO_ROOT.'/include/general.php';
strip_all_slashes();

if (php_sapi_name() != 'cli') {
	// Make sure we're at the correct URL
	$do_redirect = FALSE;
	if (REQUIRE_HTTPS && !defined('IS_PUBLIC') && empty($_SERVER['HTTPS'])) {
		$do_redirect = TRUE;
	}
	if (strpos(array_get($_SERVER, 'HTTP_HOST', array_get($_SERVER, 'SERVER_NAME', '')).$_SERVER['REQUEST_URI'], str_replace(Array('http://', 'https://'), '', BASE_URL)) !== 0) {
		$do_redirect = TRUE;
	}
	if ($do_redirect) {
		header('Location: '.build_url(Array()));
		exit();
	}
}

// Set up the DB
if (!@include_once('MDB2.php')) {
	trigger_error('MDB2 Library not found on the server.  See the readme file for how to work around this');
	exit();
}
$GLOBALS['db'] =& MDB2::factory(DSN);
if (MDB2::isError($GLOBALS['db']) || MDB2::isError($GLOBALS['db']->getConnection())) {
	trigger_error('Could not connect to database - please check for mistakes in your DSN in conf.php, and check in MySQL that the database exists and the specified user has been granted access.', E_USER_ERROR);
	exit();
}

$GLOBALS['db']->setOption('portability', $GLOBALS['db']->getOption('portability') & !MDB2_PORTABILITY_EMPTY_TO_NULL);
$GLOBALS['db']->setFetchmode(MDB2_FETCHMODE_ASSOC);


if (defined('TIMEZONE') && constant('TIMEZONE')) {
	date_default_timezone_set(constant('TIMEZONE'));
	$GLOBALS['db']->query('SET time_zone = "'.date('P').'"');
}

@ini_set('default_charset', 'UTF-8');`

**Comment by jsoftwares** [comment]
Hi Tom,
Thanks for you support so far.
Now when I try to install from cpanel, I get the below error;

MDB2 Library not found on the server. See the readme file for how to work around this in /home/exchange/public_html/portalcevi/include/init.php on line 45
I have copied MDB2_Dropin into the root directory and renamed it to MDB2.
What would be the problem this time?

**Comment by jsoftwares** [comment]
I managed to fix that one as instructed in the readme file and now getting the below error;

Fatal error: Could not connect to database - please check for mistakes in your DSN in conf.php, and check in MySQL that the database exists and the specified user has been granted access. in /home/exchange/public_html/portalcevi/include/init.php on line 50

**Comment by jsoftwares** [comment]
Hi Tom,
Now am getting this error but system has installed successfully;

Warning: ini_set() has been disabled for security reasons in /home/exchange/public_html/portalcevi/include/system_controller.class.php on line 36
SYSTEM ERROR (WARNING)

ini_set() has been disabled for security reasons

**Comment by tbar0970** [comment]
To fix that one you can edit /include/system_controller.class.php line 36 and put a @ sign at the beginning of the line

**Comment by jsoftwares** [comment]
Thanks Tom

-----Original Message-----

**Comment by jsoftwares** [comment]
Hi Tom,
I get the below error when I do things like adding new group and adding a person to a group.

Cannot modify header information - headers already sent by (output started at /home/exchange/public_html/portalcevi/include/system_controller.class.php:36) 
Line 120 of /home/exchange/public_html/portalcevi/include/general.php

Current user: jeffonochie

Request: Array
(
    [view] => _edit_group
    [action] => add_member
    [groupid] => 1
    [membership_status] => 1
    [JethroSession] => 5229ad3af7fae27418a81af524f84c34
)


Referer: http://portalcevi.exchangepointgroup.com/?view=groups&groupid=1

Array
(
    [0] => Array
        (
            [file] => /home/exchange/public_html/portalcevi/include/general.php
            [line] => 120
            [function] => header
            [args] => Array
                (
                    [0] => Location: http://portalcevi.exchangepointgroup.com/?view=groups&action=add_member&groupid=1
                )

        )

    [1] => Array
        (
            [file] => /home/exchange/public_html/portalcevi/views/view_0_edit_group.class.php
            [line] => 123
            [function] => redirect
            [args] => Array
                (
                    [0] => groups
                    [1] => [Object/Array]
                )

        )

    [2] => Array
        (
            [file] => /home/exchange/public_html/portalcevi/views/abstract_view_edit_object.class.php
            [line] => 33
            [function] => _processObjectEditing
            [class] => View__Edit_Group
            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /home/exchange/public_html/portalcevi/include/system_controller.class.php
            [line] => 124
            [function] => processView
            [class] => Abstract_View_Edit_Object
            [type] => ->
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /home/exchange/public_html/portalcevi/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

)



-----Original Message-----

**Comment by jsoftwares** [comment]
Also, how can I rename fields like GROUPS - CELLS, NOTE - ACTION etc

**Comment by tbar0970** [comment]
It looks like that ini_set problem is still having some effect. Can you try editing include/system_controller.class.php once again and removing line 46 altogether.

Re renaming fields - I think the things you are referring to are fixed - groups always get called groups etc.  You can add extra custom fields to persons via the admin > custom fields page.
