### ISSUE TITLE
Set and SMS numbers as array

### ISSUE THREAD

**Issue by mikaoelitiana** [tbar0970/jethro-pmm#195]
I am using Jethro with SMS Gateway Me (https://smsgateway.me/sms-api-documentation/messages/send-message-to-many-numbers) to send SMS for roaster reminder. 

I have trouble sending sms to multiple users because the _RECIPIENTS_COMMAS_ placeholder would not work with SMS Gateway Me API. Instead, they would need something like : 

`number[]=00000000&number[]=111111111...`

It would help to have another placeholder like _RECIPIENTS_COMMAS_ and _RECIPIENTS_NEWLINES_ with an array : _RECIPIENTS_ARRAY_

**Comment by mikaoelitiana** [comment]
I will work on this ;)

**Comment by tbar0970** [comment]
This is resolved in aa0f000860008e56bb024c09da28e4f4c100faae
