### ISSUE TITLE
Configurable error level for production

### ISSUE THREAD

**Issue by mikaoelitiana** [tbar0970/jethro-pmm#196]
By default, error_reporting is set to E_ALL for all environment .

https://github.com/tbar0970/jethro-pmm/blob/e9455ab36708d848e680e2d1f4e6db35375b1d7a/include/init.php#L16

I don't need to display these in production and would like to log errors in file only.

**Comment by tbar0970** [comment]
Fair enough.  The error handling function in system_controller.class.php currently checks whether it's a DEV version or a production release, and hides the backtrace in production.  I thought it would be valuable to still indicate some sort of error had occurred, so the user understands why their action has (possiblly) failed.  But perhaps it would be better to have them even more muted.

**Comment by tbar0970** [comment]
Resolved in 2.20 I believe.  There is a new setting in conf.php which defaults to hiding most errors.
