### ISSUE TITLE
Missing MEMBERS_DSN and MEMBER_PASSWORD_MIN_LENGTH variables in sample conf.php

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#2]
Hi Tom,

Trying 2.9's new /members URL, I just get a database error. Turns out it is because /members/index.php relies on a new variable, MEMBERS_DSN being defined, which isn't in the sampel conf.php's.

Having defined MEMBERS_DSN in conf.php, I then could log in as a member, but got an error up top complaining about a missing MEMBER_PASSWORD_MIN_LENGTH, which also needs defining.

If you'd like to 'git remote add jefft https://github.com/jefft/jethro-pmm'' these changes are in HEAD.

Regards,
Jeff

**Comment by tbar0970** [comment]
Thanks Jeff, I've merged your pull request.
