### ISSUE TITLE
Printing Rosters with Comment Field

### ISSUE THREAD

**Issue by mvanglican** [tbar0970/jethro-pmm#202]
We recently upgraded to the latest version of Jethro and when we print out rosters the "Comment" field with text we have included will not print. The work around is to use the CSV option. Is this a known issue or has it been resolved. I couldn't find any related references.

**Comment by tbar0970** [comment]
I don't think this has been reported before.

Can you give some step by step instructions to reproduce the problem - how are you entering the comments and how are you printing the roster.

**Comment by mvanglican** [comment]
Just a clarification -  it is the Notes field that is not printing. To enter comments in the Notes field, we select the Services Tab and select/tick a defined service from the All Services list then click the Edit box. This brings up the Edit Service Program page and for the date we wish to add 
[Notes field blank.docx](https://github.com/tbar0970/jethro-pmm/files/317545/Notes.field.blank.docx)
Notes, we select the drop down arrow next to the Format box which then displays the Notes box. We then enter the text we want included eg. Film Night. We then save the changes.

To print the roster we then select Display Roster Assignments tab from the Rosters drop down box. We then select the specific service (Roster View) to display (covers the next 8 weeks). On this view, we can see that our Notes included in the step above are included in the display. We then select the "Show the print/email version" option shown above the roster which opens the roster in a new window. On this window, the roster shows all the assignments correctly (eg. Dates, Topic, Bible readings etc.) but the Notes fields are empty. I do see that the space available in the Notes field on this view is quite narrow - not sure if this is related. I have attached screen prints FYI

**Comment by tbar0970** [comment]
Thanks, that makes it clear.  I'll look into it.

**Comment by tbar0970** [comment]
Hi again, 

Thinking further on this I think it may be a config issue.  On your admin > system config page there is a setting "show service notes publicly" - can you check if turning that setting on fixes your problem?

**Comment by tbar0970** [comment]
Solved
