### ISSUE TITLE
Including Songs in Rosters

### ISSUE THREAD

**Issue by mvanglican** [tbar0970/jethro-pmm#203]
We recently upgraded to the latest version of Jethro and what to add Hymns to our rosters. When we went to use the "Define Roster Views" and included the "Service Field" - All Songs, This creates a "Songs" field in the Roster View however, I can't populate it via either the Edit Roster Assignments option or the Edit Services option. How do I populate the Songs field? All I want to do is just include the name of the various Hymns that will be played in the service - is this possible or do I need to start using the component library? 

BTW as many churches no doubt use CCLI for their music, is there a simple way of populating the Songs Component Library without having to add each song individually?

**Comment by tbar0970** [comment]
Hi there

You do need to use the component library.  The "Service field -- all songs" roster field will show all the components from the "song category" which  have been added to that service's run sheet.

CCLI import would be nice, but they charge very high fees for accessing their API.  If you enter CCLI numbers into Jethro, it gives you a link to the CCLI site to get quick access to lyrics etc.  (This link can be configured in the conf.php file to point to different countries' songselect etc).

Hope that helps.

**Comment by mvanglican** [comment]
Thanks for the feedback, that helps clarify the option for me.
