### ISSUE TITLE
Feature request - Attendance report for more than one group

### ISSUE THREAD

**Issue by AlwynBarry** [tbar0970/jethro-pmm#21]
Problem and rationalle:

At the moment one can input and display attendance for more than one congregations, but not more than one group.  So, if you have groups to maintain records of attendance at (for example) many Bible Study Groups, it is not currently possible to input or display these in one go.  But, for tracking attendance over multiple related groups this is a really useful feature ... and the functionality must be basically similar as the implementation for congregations.

Feature Request:
So, the feature request is simple: provide the ability to report attendance over a number of groups at the same time, in the same way as we already have for congregations.

**Comment by tbar0970** [comment]
Done in latest version
