### ISSUE TITLE
FR: Change email address delimiter from "," to ";"

### ISSUE THREAD

**Issue by ken-h** [tbar0970/jethro-pmm#223]
If I email a group of people the email address delimiter is "," which does not work with Outlook 365 but is fine for Windows Mail (in Windows 10) and Gmail.  The delimiter ";" works for all of these.

**Comment by tbar0970** [comment]
Semicolon doesn't work for mac mail.  But you can adjust the separator in your conf.php:

define('MULTI_EMAIL_SEPARATOR', ';');
