### ISSUE TITLE
Other attendances lost when recording attendance for specific status

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#226]
Very similar to bug #72. Say one records attendances, and then later records attendances for people in a specific status (e.g. 'Irregular'). The original attendances are lost.

To replicate:
1. Pick any group and day, and record an attendance (e.g. from a 'Regular' status person).
2. Go to Attendance -> Record,  pick the same group and date, but untick 'All statuses' and tick a different status (e.g. 'Irregular'). Mark someone present and 'Save All Attendances'.
3. View the group's attendance via Attendance -> Display. You'll see the previous ('Regular') attendance has been lost, and only the last save ('Irregular') is kept.

**Comment by tbar0970** [comment]
Thanks for reporting. I will sort this out tonight. Not sure how it has crept back in.

**Comment by tbar0970** [comment]
This was caused by an inadvertent reversion of the fix for #176 during the merging in of PR #201.
