### ISSUE TITLE
PHP7 support & bugs

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#229]
Im moving my server over to ubuntu 16.04 and Jethro no longer works, due to php7 now being the only option (hence default option).

Is there any easy fix for this?
I get the following errors under php7:

Warning: session_start(): open(/var/lib/php/sessions/sess_1v99eamsbtp6i5koal96ic93s6, O_RDWR) failed: Permission denied (13) in /home/user/www/jethro/include/init.php on line 23

Parse error: syntax error, unexpected 'new' (T_NEW) in /usr/share/php/MDB2.php on line 390

Warning: Unknown: open(/var/lib/php/sessions/sess_1v99eamsbtp6i5koal96ic93s6, O_RDWR) failed: Permission denied (13) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions) in Unknown on line 0

**Comment by tbar0970** [comment]
The parse error is likely an incompatibility of the MDB2 library with PHP7.   I want to get rid of MDB2.

The other errors look like they are not php7-specific but that PHP can't write to the session path - a permissions problem not to do with PHP version.

**Comment by Gibbz** [comment]
ok ive found a work around to get php5 installed on ubuntu server 16.04
the following commands will get it up and running:

`sudo su
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0 php5.6-curl php5.6-gd php5.6-mcrypt php5.6-xml php5.6-xmlrpc
sudo a2dismod php7.0 && sudo a2enmod php5.6 && sudo service apache2 restart
sudo ln -sfn /usr/bin/php5.6 /etc/alternatives/php`

**Comment by funkydan2** [comment]
Thanks @Gibbz, I also upgraded my server to Ubuntu 16.04LTS and have run into a bunch of issues with MySQL and PHP, and you're instructions on downgrading have done the trick.

When Jethro is able to run on PHP7 (when the code moves from relying on MDB2?) will moving back to PHP7 be: do the opposite a2dismod/a2enmod commands, uninstall php5.6, remove the php5 repository?

**Comment by vanoudt** [comment]
Shouldn't be long now - there's a pull request in to get PHP7 running. in fact, I'm running php7 on my test machine right now and everything's fine!

**Comment by funkydan2** [comment]
I did see some commits and discussion that mentioned things working with PHP7. But I'd got into a bit of trouble earlier with cloning the github repo, rather than waiting for a release - so I eagerly await the next version!
