### ISSUE TITLE
Reporting Errors

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#232]
I was getting the error:
MDB2_Driver_mysql::raiseError()

So ive updated to the beta versions, using:
sudo pear install MDB2-2.5.0b5
sudo pear install MDB2_Driver_mysql-1.5.0b4

Now i get the error:

SYSTEM ERROR (ERROR)

Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: INSERT INTO db_object_lock (objectid, object_type, lock_type, userid, expires) VALUES ( '1', 'congregation', 'attendance-2016-07-31', '1', '2016-08-02 14:26:39')] [Native code: 1406] [Native message: Data too long for column 'lock_type' at row 1]

Any ideas why this is? And how to fix it?

**Comment by Gibbz** [comment]
Also if i go into a member and click on their attendance tab, i get the following error:

	
SYSTEM ERROR (ERROR)

Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: SELECT g.id, recorded.`date`, present FROM ( SELECT groupid, `date` FROM attendance_record WHERE date BETWEEN '2016-05-10' AND '2999-01-01' AND ((groupid = 0) OR (groupid IN ( select groupid from person_group_membership WHERE personid ='115' )) ) GROUP BY groupid, `date` ) recorded LEFT JOIN attendance_record ar ON ar.`date` = recorded.`date` AND ar.groupid = recorded.groupid AND ar.personid = '115' LEFT JOIN person_group g ON recorded.groupid = g.id WHERE ((recorded.groupid = 0) OR (g.name <> "")) GROUP BY recorded.groupid, recorded.date ORDER BY recorded.groupid, recorded.date] [Native code: 1055] [Native message: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'g.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]

**Comment by tbar0970** [comment]
I think these are both due to your MySQL being in strict mode.  Historically MySQL has been pretty forgiving with queries that violate the rules in minor ways, but when it's in strict mode it's, well, strict.

If you have access to configure MySQL on your server, see the discussion at http://stackoverflow.com/questions/15949038/error-code-1406-data-too-long-for-column-mysql for how to adjust MySQL mode.

To make Jethro compatible with MySQL strict mode I've opened issue #233 and issue #234

**Comment by Gibbz** [comment]
thanks! thats fixed it :)

**Comment by Gibbz** [comment]
just a note, i needed to edit the .cnf file to be persistent!

A work around if you encounter this issue is to edit the file:

sudo nano /etc/mysql/my.cnf

add the following

[mysqld]
sql_mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Then restart mysql:

sudo /etc/init.d/mysql restart

**Comment by tbar0970** [comment]
I turned on ONLY_FULL_GROUP_BY on my test system and got errors everywhere.  Jethro actually depends in several places on the more relaxed group-by rules that are the default in MySQL < 5.7.5

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

BTW I think in the instructions above you need to REMOVE the text `ONLY_FULL_GROUP_BY,` from  the my.cnf line.
