### ISSUE TITLE
Replace MDB2

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#235]
The MDB2 library is really old and using it means we need to turn off PHP5 strict mode.

We should move to using PHP5 PDO instead.

The easiest approach would probably be to define a JethroPDO class with methods that mimic the MDB2 methods and have $GLOBALS['db'] contain an instance of that instead of an MDB2 instance.  That way we wouldn't need to update all the calls.

**Comment by vanoudt** [comment]
And that is done - have a look at PR #238!
Probably needs some more testing - though it seems to work for me...

**Comment by tbar0970** [comment]
Resolved.
