### ISSUE TITLE
Search in banner/menu bar

### ISSUE THREAD

**Issue by russarundel** [tbar0970/jethro-pmm#240]
Any chance of making the search function on the homepage accessible on all pages? It's such a useful way to get around but a pain to keep going back to the front to get to it.

**Comment by tbar0970** [comment]
Yes, I'm keen to do this when I can get to it.  It would also simplify the navigation because we could get rid of persons > search, families > search and groups > search.

**Comment by tbar0970** [comment]
Completed in 1e0928d4a4204a674eddd5487981c63cf0c4150e
