### ISSUE TITLE
mailchimp_sync.php intermittent failures: unserialize() Error at offset

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#246]
This might be a Mailchimp problem, but since 5 August, running mailchimp_sync.php has been intermittently (2% of runs) throwing errors:

```
PHP Notice:  unserialize(): Error at offset 1121 of 1127 bytes in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 2680
Notice: unserialize(): Error at offset 1121 of 1127 bytes in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 2680
PHP Notice:  Undefined index: data in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 118
Notice: Undefined index: data in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 118
PHP Warning:  Invalid argument supplied for foreach() in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 118
Warning: Invalid argument supplied for foreach() in /srv/www/jethro/2.16.0/scripts/mailchimp_sync.php on line 118
```

The 'offset' byte varies each time.

We're running PHP 5.4.45-0+deb7u4.

Anyway, posting this in case other people see the same thing.

**Comment by tbar0970** [comment]
The code that calls unserialize here is part of the Mailchimp library (which probably should have been put in its own file).  It's trying to unserialize the response it gets from the Mailchimp API, which in this case must either have become corrupt along the way or been badly formed at the Mailchimp end.

I think Mailchimp might have a new API version; we could look into calling that instead.

**Comment by tbar0970** [comment]
@jefft are you still experiencing this? Can I close the issue?
