### ISSUE TITLE
Attendance rates do not sort numerically

### ISSUE THREAD

**Issue by russarundel** [tbar0970/jethro-pmm#247]
When sorting reports by attendance rate, it is alphabetical (1%, 100%, 13%, 22%, 3%, 35% etc) where it should be numerical.

**Comment by tbar0970** [comment]
Thanks for reporting this bug.  It was already reported back in May - by you! https://github.com/tbar0970/jethro-pmm/issues/191

I'll get on to it soon.

**Comment by russarundel** [comment]
Oops! thanks for that :)
