### ISSUE TITLE
Song Usage Report

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#25]
Based on saved run sheets

List all the components of type [song] that have been used in the last [3] months for congregations [X, Y]
and for each one how many times it's been used.

Useful for CCLI reporting.

**Comment by tbar0970** [comment]
requested by ej customer today

**Comment by tbar0970** [comment]
+1

**Comment by marcusmac** [comment]
Also useful for song usage tracking. For instance, able to see what songs are not being used regularly and need to be played again or archived from the rotation.

Without this feature we would need to use two different song list systems, one for tracking and one for services.

**Comment by tbar0970** [comment]
To highlight some partial workarounds:
1) You can include songs in a roster, to see the raw list of what's been used over time on one page
2) When editing a service run sheet, it shows you how recently songs were used and how many times they were used this year.  So that covers the case of "song X hasn't been sung for a while, we should give it another go".

**Comment by marcusmac** [comment]
Thanks for the ideas.

Regards,
Marcus Macbeth
