### ISSUE TITLE
2.16.3 - Unable to record attendance due to database lock

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#251]
Hi,

Big thanks for pushing out the latest update.

After upgrading I've gone to record attendance for a bible study and received an error stating that 'we do not have a lock' on the database. 
![Error Screenshot](https://cloud.githubusercontent.com/assets/10623666/17953922/c9585102-6aba-11e6-8cc0-f851bd19155e.png)

It doesn't seem to be stopping other database changes - e.g. I successfully removed someone from being a member of a group. 

(Running MySQL 5.7 on Ubuntu 16.04)

**Comment by funkydan2** [comment]
I found the bug - two lines in db_objects/attendance_record_set.class.php still referenced 'attendance-' for unlocking the database rather than 'att-'. (I think I may have done some github magic and the fixes are in pull request #252)

**Comment by tbar0970** [comment]
Pull Request merged.  Fix will be in the next release.
