### ISSUE TITLE
Unknown Family photo not displaying when MySQL is in strict mode

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#253]
Since upgrading my server to Ubuntu 16.04 (which runs MySQL  in 'strict mode') the default/unknown /blank family photo hasn't been shown in the family view.

I think the problem is because of the SQL query in calls/call_photo.class.php, which doesn't have enough columns in the GROUP BY clause, and thus is throwing an error. 

My knowledge of MySQL is quite rusty, but I think if line 34 of calls/call_photo.class.php is changed to:
					`GROUP BY f.id, p.id';`
then the query gives the expected result.

**Comment by tbar0970** [comment]
The other day I turned on strict mode and started modifying queries in Jethro to suit (Issue #232, #234), and quickly realised that there are lots and lots of places in Jethro that rely on MySQL's more permissive previous approach.  So I think that turning strict mode off is really the way to go.

**Comment by funkydan2** [comment]
Actually, I'm not sure if it's to do with strict mode. I'm running with the suggested MySQL settings from #232 and with the query as it is family pictures (whether in the database or the unknown gif) don't display on my setup.

**Comment by tbar0970** [comment]
Hmm, it's working for me outside strict mode.  Did you restart MySQL after changing your settings?  I think the changes in your pull request may break the functionality that falls back to the person photo for a single-person family without a family photo.

**Comment by tbar0970** [comment]
If you can post the full error message you were getting it should tell us whether it's a strict mode problem

**Comment by funkydan2** [comment]
Yep...I've had a quick fiddle with the mysql settings, and removed the ONLY_FULL_GROUP_BY setting, and now photos are displaying with the original query.

So the settings I've got in my.cnf are:

`[mysqld]
sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Thanks so much for your help.
