### ISSUE TITLE
attendance statistics error

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#259]
upgrade to new version, and reverted the strict mode changes. I am getting this error on the attendance statistics. I assume this is another strict mode issue?

SYSTEM ERROR (ERROR)

Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: SELECT status, AVG(TotalPresent) as avg_present, AVG(TotalAbsent) as avg_absent FROM ( SELECT ar.date, pgms.id AS status, rank, SUM(present) as TotalPresent, COUNT(*)-SUM(present) as TotalAbsent FROM person p JOIN attendance_record ar ON p.id = ar.personid LEFT JOIN person_group_membership pgm ON pgm.personid = p.id AND pgm.groupid = ar.groupid LEFT JOIN person_group_membership_status pgms ON pgms.id = pgm.membership_status WHERE ar.date BETWEEN '2016-05-31' AND '2016-07-31' AND ar.groupid = 1 GROUP BY ar.date, status ) perdate GROUP BY status] [Native code: 1055] [Native message: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jethro.pgms.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]

**Comment by tbar0970** [comment]
Yep, it's another strict mode issue (the giveaway is the mention of only_full_group_by at the end).  You'll need to run with only_full_group_by turned off.
