### ISSUE TITLE
attendance statistics error

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#270]
Running the latest build (2.16.4), and have disabled strict mode, but still getting this error.
Attendance > Statistics

SYSTEM ERROR (ERROR)

Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: SELECT status, AVG(TotalPresent) as avg_present, AVG(TotalAbsent) as avg_absent FROM ( SELECT ar.date, pgms.id AS status, rank, SUM(present) as TotalPresent, COUNT(*)-SUM(present) as TotalAbsent FROM person p JOIN attendance_record ar ON p.id = ar.personid LEFT JOIN person_group_membership pgm ON pgm.personid = p.id AND pgm.groupid = ar.groupid LEFT JOIN person_group_membership_status pgms ON pgms.id = pgm.membership_status WHERE ar.date BETWEEN '2016-06-15' AND '2016-08-31' AND ar.groupid = 1 GROUP BY ar.date, status ) perdate GROUP BY status] [Native code: 1055] [Native message: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'jethro.pgms.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by]

**Comment by tbar0970** [comment]
The bit at the end that says
>  this is incompatible with sql_mode=only_full_group_by
indicates it is the same strict-mode problem at play.
Did you remember to restart mysql after changing the mode?

**Comment by Gibbz** [comment]
sorry my bad, I missed a bit in the config, its all working now :)
