### ISSUE TITLE
Make it easier to insert intervening services

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#272]
Currently, if you've got services saved for 20th and 27th December, and you want to add one on 24th December, then you need to use a tricky workaround in which you edit the service program up to some far-off-future date, and change one of the editable dates in the final rows to be 24th Dec.  This is not intuitive.

We should add a "insert new row in between" button to make it easier to insert services.

**Comment by jefft** [comment]
+1, this comes up each Christmas and Easter.

**Comment by GatesheadBen** [comment]
Hi Folks, did anything ever get implemented to solve this? Thankyou!

**Comment by tbar0970** [comment]
@GatesheadBen - finally resolved today - will be in next release.
