### ISSUE TITLE
Service Runsheet - Print view doesn't show service components

### ISSUE THREAD

**Issue by alwr** [tbar0970/jethro-pmm#279]
When you set up a roster view, you can set it to "show on runsheet".  This works well for displaying roster roles (personnel) on the runsheet.

If you include service fields in the roster view (eg Topic, Notes), they show fine on the runsheet view page, but are not included in the print view.  It would be very useful to have these appear so that the printed runsheet header can contain all the key details at the top (eg date, topic, passage & key people).

**Comment by tbar0970** [comment]
The view-run-sheet page includes the service details automatically - regardless of the roster view.

We can add this to the printable version too.
