### ISSUE TITLE
Dropdown menu on services list isn't populating correctly

### ISSUE THREAD

**Issue by RoystonS** [tbar0970/jethro-pmm#280]
Hi,

[Jethro version 2.16.4]

I've just noticed that the dropdown menu item at the end of the rows in the service list isn't populating correctly. Clicking the 'down chevron' button on our 2.16.4 installation produces a popup containing 4 "SYSTEM ERROR (WARNING) Invalid argument supplied for foreach()" messages.

I've just tried this out on http://easyjethro.com.au/demo/?view=services__list_all (2.16.2) and there's a problem there too, although there it reports "SYSTEM ERROR (NOTICE)
Bad config: Templates/To_Populate does not exist" and "SYSTEM ERROR (NOTICE)
Bad config: Templates/To_Expand does not exist" instead.

Cheers,
 Royston.

**Comment by tbar0970** [comment]
Thanks for reporting this.  That dropdown menu is used for generating service documents.  These errors occur when the those folders it mentions don't exist (see the Documents page in Jethro) and/or when there are no templates found there.  Jethro needs to handle this situation better.
