### ISSUE TITLE
Order of people added to a roster roll not staying in the order you enter them.

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#282]
Hi there, 

When we add multiple people to a roster roll, Jethro does not keep the order they are entered in, but automatically changes the order to alphabetical. This is a problem for things such as Bible reading, where the first person entered does the first reading and the second person does the second. We choose who is doing what, but then Jethro changes it to match alphabetical order. 

Can this be changed? Or can an option be added to not automatically alphabetise people in roster views? (having people in alphabetical order in other places such as reports is usually helpful). 

Thanks, Andrew.

**Comment by tbar0970** [comment]
Already opened in Issue #8.  High priority!
