### ISSUE TITLE
Service planning on ipad problem

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#284]
A user reported unable to drag items into the run sheet on ipad

**Comment by funkydan2** [comment]
Confirmed for me using the *Covenant Eyes* browser. This is a bit of a pain as it means I can't pick songs from the Component Library whilst I'm away from my Mac.

**Comment by tbar0970** [comment]
+1

**Comment by tbar0970** [comment]
https://github.com/RWAP/jquery-ui-touch-punch
