### ISSUE TITLE
SMS: uninformative 'sending failed' message when any of recipient SMS numbers are invalid

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#292]
When more than one person is messaged, if _any_ of the recipients' mobile numbers are incorrect, then Jethro reports a generic error, of the form:

    SMS sending failed for 5 recipients.
    User1, User2, User3, User4, User5

First, the error suggests that _all_ recipients failed to receive the message, when most would have. Secondly it provides no hint as to which numbers failed, so that they could be corrected/excluded. There are no further details in the SMS_SEND_LOGFILE either.

**Comment by tbar0970** [comment]
Hi Jeff

We can certainly improve that error message to make it clearer that only some of the recipients failed.
The purpose of SMS_SEND_LOGFILE is just meant to record successes, to keep track of who is using up all the credits :)

If it's giving you the names of the recipients who failed, doesn't that allow you to find those persons and check their numbers?
I guess it would be nice to be able to click through to the person record rather than searching for them by name.  Is that what you're thinking?

**Comment by jefft** [comment]
Hi Tom,

It's not showing just usernames that failed - it shows all the usernames, regardless of their individual success or failure. That's why the message is so confusing. Showing just the failures would be ideal.

**Comment by tbar0970** [comment]
Ah.  Can you post the (redacted) SMS settings you're using?  One of them is a regex to detect success per recipient.

**Comment by jefft** [comment]
Good point. We're using:

    define('SMS_HTTP_URL', 'https://www.5centsms.com.au:/api/v4/sms');
    define('SMS_HTTP_HEADER_TEMPLATE', "User: <REDACTEDEMAIL>\r\nApi-Key: <REDACTEDPASSWORD>\r\n");
    define('SMS_HTTP_POST_TEMPLATE', 'sender=_USER_MOBILE_&to=_RECIPIENTS_COMMAS_&message=_MESSAGE_');
    define('SMS_RECIPIENT_ARRAY_PARAMETER', 'number');
    define('SMS_HTTP_RESPONSE_OK_REGEX', '[{]\s*"destination":\s*"_RECIPIENT_",[^}]*"status":\s*(1000|1001|1002|1004|1006|1011|1527),');
    define('SMS_HTTP_RESPONSE_ERROR_REGEX', '');
    define('SMS_LOCAL_PREFIX', '0');
    define('SMS_INTERNATIONAL_PREFIX', '61');
    define('SMS_SAVE_TO_NOTE_BY_DEFAULT', false);
    define('SMS_SAVE_TO_NOTE_SUBJECT', 'SMS Sent');
    define('SMS_SEND_LOGFILE', '/var/log/jethro/sms_senders.log');

**Comment by tbar0970** [comment]
That looks OK.  I'll investigate.

**Comment by russarundel** [comment]
That sounds like the explanation for what I reported Tom. Thanks

**Comment by tbar0970** [comment]
Hi Jeff

Just looking through the bug list and had a bit more of a look at this.

I suspect one factor at play here is that we need to update the "OK" regex because they've started returning statuses as strings not ints:

**Comment by tbar0970** [comment]
`define('SMS_HTTP_RESPONSE_OK_REGEX', '[{]\s*"destination":\s*"_RECIPIENT_",[^}]*"status":\s*"?(1000|1001|1002|1004|1006|1011|1527)"?,');`

Can you see if that makes a difference?

The other thing is that often the initial status from 5centsms is "sending" which may later turn into "failed", but we don't currently repeat the check later...

**Comment by russarundel** [comment]
Ahhhh, what do I do with that?

Sorry, you’re talking to someone with little-no tech talk.

 

It’s probably outside your job, but would you be able to log in for me?

That should be the current password.

 

russ@arundel.org.auallIED132

 

 

In Christ,

 

EmJay Fraser

Administrative Assistant

Phone: 07 5571 5676 

Address: 132 Allied Drive, Arundel QLD 4214

**Comment by jefft** [comment]
(Sorry, I missed your response to this)

Yes, the new regex (I assume) fixes this problem, or at least something in 2.21.1 does. Thanks!
