### ISSUE TITLE
Outdated Jethro download link on Sourceforge

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#3]
Hi,

A minor nit: the old sourceforge page still has 2.7.2 as the latest download:

http://sourceforge.net/projects/jethro-pmm

Also, the page http://jethro-pmm.sourceforge.net/download.php is blank:

![screenshot](https://cloud.githubusercontent.com/assets/205995/6034028/c8b9edd6-ac71-11e4-99a7-01bd5a165201.png)

I get a 200 response with a bizarro corrupt HTTP header, with the URL 'https: //github.com/tbar0970/jethro-pmm/releases' tossed in amongst the response headers:

````
jturner@jturner-desktop ~ $ curl -v http://jethro-pmm.sourceforge.net/download.php
* Hostname was NOT found in DNS cache
*   Trying 216.34.181.96...
* Connected to jethro-pmm.sourceforge.net (216.34.181.96) port 80 (#0)
> GET /download.php HTTP/1.1
> User-Agent: curl/7.35.0
> Host: jethro-pmm.sourceforge.net
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server Apache/2.2.15 (CentOS) is not blacklisted
< Server: Apache/2.2.15 (CentOS)
< Vary: Host
< https: //github.com/tbar0970/jethro-pmm/releases
< Cache-Control: max-age=172800
< Expires: Fri, 06 Feb 2015 02:33:29 GMT
< Content-Type: text/html
< Content-Length: 0
< Date: Wed, 04 Feb 2015 02:33:29 GMT
< X-Varnish: 488059601
< Age: 0
< Via: 1.1 varnish
< Connection: keep-alive
< 
* Connection #0 to host jethro-pmm.sourceforge.net left intact
````

**Comment by tbar0970** [comment]
Thanks Jeff.  I'll look into it.

**Comment by tbar0970** [comment]
Have now fixed the download page redirect and the "latest release" link on sourceforge.

**Comment by jefft** [comment]
Hm, does it work for you? I now see:

![screenshot](https://cloud.githubusercontent.com/assets/205995/6074838/26ae5e04-ae1b-11e4-9658-bab1419afa53.png)

Clicking on the link to https://sourceforge.net/projects/jethro-pmm/files/latest/download, my browser eventually redirects to http://internode.dl.sourceforge.net/project/jethro-pmm/jethro-pmm/LATEST/readme.md, which is served with MIME type 'application/octet-stream' rather than text/plain, so it downloads rather than displays:

![screenshot](https://cloud.githubusercontent.com/assets/205995/6074872/cac7822c-ae1b-11e4-9643-3f39489ac79c.png)

This might just be a misconfiguration on Internode's part.
