### ISSUE TITLE
Editing rosters in 2.18.1 - something's broken

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#304]
Just upgraded to 2.18.1 and it seems something's broken when editing rosters.

Here's a screenshot from the edit roster section. For each of these entries, there should be two names listed, but there is either none, or a number (I assume the number is the ID of the person).  (For this roster, there are two names in the *read only* view, but disappear when editing)
![screen shot 2016-12-17 at 8 58 27 am](https://cloud.githubusercontent.com/assets/10623666/21281743/f931f55c-c43a-11e6-8dc4-b5206f839691.png)

**Comment by funkydan2** [comment]
Just went to a different roster view, and got this error...
![screen shot 2016-12-17 at 9 30 10 am](https://cloud.githubusercontent.com/assets/10623666/21281831/9dc625c0-c43b-11e6-9a64-59de13d6ad4f.png)

**Comment by tbar0970** [comment]
Hi Dan

Thanks for reporting this.  Could I get you to drop in the changes I committed above and check that it solves the problem for you?  Here are direct links - both to go in the db_objects folder:

person.class.php:
https://raw.githubusercontent.com/tbar0970/jethro-pmm/482462aae5aa32ee2a0bec1672967e2cfc2a4c97/db_objects/person.class.php

roster_role.class.php:
https://raw.githubusercontent.com/tbar0970/jethro-pmm/482462aae5aa32ee2a0bec1672967e2cfc2a4c97/db_objects/roster_role.class.php

Thanks
Tom

**Comment by tbar0970** [comment]
Updated links:

person.class.php:
https://raw.githubusercontent.com/tbar0970/jethro-pmm/482462aae5aa32ee2a0bec1672967e2cfc2a4c97/db_objects/person.class.php

roster_role.class.php
https://raw.githubusercontent.com/tbar0970/jethro-pmm/45faec5729bd97bee3768e3ea1e8c805ddda1b1f/db_objects/roster_role.class.php

**Comment by funkydan2** [comment]
Yes, that seems to have fixed it. Thanks heaps!

**Comment by funkydan2** [comment]
Actually this may not have fixed it. In a rush this morning I printed off a new roster, got to church and reasoned that somehow *I* had become rostered on for a whole of jobs in the place of others!
![jethro_pmm_-_gympie_presbyterian_-_standard_roster](https://cloud.githubusercontent.com/assets/10623666/21290898/af8ff92a-c517-11e6-8bd5-42621a62dae7.png)
(Also, someone has been filled in for the 'welcoming' column who shouldn't have been.)

I think the bug is in the edit page, because I've had a quick look at the database and I think I've *really been* assigned to these roster tasks. (Looks like I better learn to bake and vacuum soon!)

I'll keep playing - the corrupt data may have been entered before you fixed things, or it may still be there.

**Comment by tbar0970** [comment]
Unfortunately I think this due to data corruption when the bug was in play.  Your best bet is to roll back your roster_role_assignment table to the backup you took when you upgraded.  
(Extract the SQL backup into a new database called "restored" then run
```
TRUNCATE jethro.roster_role_assignment;
INSERT INTO jethro.roster_role_assignment SELECT * FROM restored.roster_role_assignment;
```
)
The old data format had person IDs as array keys; the new data format has rankings as the array keys; rankings are low numbers; you were probably one of the first people entered in the system therefore a low person ID.

**Comment by tbar0970** [comment]
Sorry for the hassle.

**Comment by funkydan2** [comment]
Restoring from a backup has worked the trick! Thanks for all your work in constantly improving Jethro!
