### ISSUE TITLE
Unable to delete items from the service component library

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#318]
Like it says, I think this would be useful so that it doesn't get too cluttered with old items. 

Thanks, Andrew.

**Comment by tbar0970** [comment]
Hi Andrew, the intention is that for items you don't use any more you just set them to be "used by" no congregations.  Then they don't show up in the run sheet editor, or in the component library unless you select "any congregation".  Does that solve your problem?

**Comment by tbar0970** [comment]
Closing for now.  Re-open if you think it needs more discussion.
