### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by GatesheadBen** [tbar0970/jethro-pmm#320]
I'm not sure if it is the configuration of this particular server but I'm currently getting an error on install like 

Error in foreign key constraint of table [databasename]/person_group_membership:
	 FOREIGN KEY (membership_status) REFERENCES person_group_membership_status (id) ON DELETE SET NULL ) ENGINE=InnoDB:
	You have defined a SET NULL condition though some of the columns are defined as NOT NULL.

By removing the on delete set null statement from db_objects/person_group.class.php line 99 the installer succeeds.

I will look to reproduce this issue with another clean install later in the week.

**Comment by tbar0970** [comment]
Thanks for reporting.  NULL membership statuses were removed in issue #303 and I missed this bit of init sql.  Now fixed.
