### ISSUE TITLE
Safari autocompletes username/password in the add/edit user page

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#330]
When you try to add or edit a user via admin > user accounts
there are username and password fields for the new user.
Safari always tries to autofill these with MY username and password

Can address this by using a different form element name eg user-username, user-password.

**Comment by funkydan2** [comment]
I haven't made new/edited user accounts very many times, but I did come across this bug when I did. Thanks heaps for fixing!

**Comment by tbar0970** [comment]
This is still happening on
