### ISSUE TITLE
Ability to sms groups/selections/reports of users

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#348]
Hi,

Ive setup a sms gateway for Jethro. Id like to see the ability to send bulk messages to groups of users. Either from the reports menu in the same way an email is done, or from the groups menu, or possibly even a dedicated page for texting users.

I guess ideally in the "With selected persons:" drop down box. An option to text/sms all users.

**Comment by tbar0970** [comment]
The "with selected persons" box already has a "send SMS" option...

**Comment by Gibbz** [comment]
ah my bad! It is there!
