### ISSUE TITLE
Ordering members within families

### ISSUE THREAD

**Issue by AnthonyDouglas** [tbar0970/jethro-pmm#350]
It's not clear how Jethro determines what order people have within families. When I generate a contact list, my own three kids are shown out of alphabetical, age, or personid order. Not bad! It would be nice if this was controllable, if not by interface, at least by a transparent reason so that we could work within it.

**Comment by funkydan2** [comment]
There's also the case of adult children who live at home and in the contact list they get jumbled in with the parents.

**Comment by tbar0970** [comment]
Assuming you're using v2.19, it should be listing people in order of age bracket, as configured in Admin > System Configuration.  Those in the same age bracket are listed as male first, female second.

Adult children living at home will indeed be listed along with the other adults in the family.  But in v2.19 you have the ability to create several age brackets that are treated as adult - so you could have a "young adult" category which would show up after "adult".
