### ISSUE TITLE
Jethro and PHP7 ... error message relating to MDB2

### ISSUE THREAD

**Issue by AlwynBarry** [tbar0970/jethro-pmm#359]
I've had to upgrade our web service to PHP 7 in order to support some aspects of our main church website.  However, Jethro now throws the following error, which prevents any aspect of Jethro running:

`Parse error: syntax error, unexpected 'new' (T_NEW) in /home/sites/streetbaptist.co.uk/public_html/directory/MDB2.php on line 390`

I know this is a problem beyond Jethro itself, but is rather a killer error for the future of Jethro unless it can be resolved.  Clearly I may be running an old MDB2.php ... the one you provide is of 2007 vintage.  I've tried the 2012 (version 2.5.0b5) but it produces the following errors:

`Notice: Only variables should be assigned by reference in /home/sites/streetbaptist.co.uk/public_html/directory/MDB2.php on line 578`

`Notice: Only variables should be assigned by reference in /home/sites/streetbaptist.co.uk/public_html/directory/include/init.php on line 51`

`Fatal error: Could not connect to database - please check for mistakes in your DSN in conf.php, and check in MySQL that the database exists and the specified user has been granted access. in /home/sites/streetbaptist.co.uk/public_html/directory/include/init.php on line 53`

Going back to the original MDB2 you ship (the 2007 version), it is possible to systematically change the assignments:  `$variable &= new ...;`  to `$instance = new ...; $variable &= $instance`  but I gave up as the errors descended into mysql.php and other files.  But, that _might_ be a 'hacked' fix.  It would be better, though, to find a maintained MDB2 or move to a new abstraction layer that is kept up to date.

With many websites starting to require PHP7, this is a potentially critical issue ... so just flagging it now!

**Comment by tbar0970** [comment]
Yes.  We have a pull request pending which removes MDB2.  This is one more reason I should get on with reviewing and merging it!

**Comment by tbar0970** [comment]
As an interim fix, try this:

Edit include/system_controller.class.php
add a new line at line 238:

```
switch ($errno) {
			case E_ERROR:
			case E_USER_ERROR:

                               // NEW LINE:
				if (FALSE !== strpos($errstr, 'variables should be assigned by reference')) return;**

				$bg = 'error';
				$title = 'SYSTEM ERROR (ERROR)';
				$exit = true;
```

That will suppress the error messages - but there could be other problems at play.
(Errors are occuring because this error used to be E_STRICT but is E_NOTICE in php7)

**Comment by AlwynBarry** [comment]
Sorry - that interim fix (without the additional asterixes on the line end) doesn't solve it ... the responses remain exactly the same with both MDB2 versions.

**Comment by tbar0970** [comment]
@vanoudt has kindly brought his pull request up to date which fixes this problem by removing MDB2 and using PDO instead:
https://github.com/tbar0970/jethro-pmm/pull/238

I'm flat out with other things at the moment but I'll definitely have this released by the end of June.  In the meantime you could try merging this into your own system yourself.

**Comment by tbar0970** [comment]
MDB2 is now gone!  Closing.

**Comment by kevlwig** [comment]
@tbar0970 could we just remove & when instantiating objects?  because are objects already passed by reference? I am new to php and i havent dove deep into you class but i removed the reference operator and it error is gone.

**Comment by vanoudt** [comment]
You could try... But the latest version of Jethro shouldn't have any issue working on php7...

**Comment by tbar0970** [comment]
@kevlwig have you found any examples of the extraneous ampersand in the latest Jethro?  They should be all gone but if there are some we've missed a pull request would be welcome.
