### ISSUE TITLE
Fatal Error: maximum execition time of 30 seconds exceeded in:/home/christch/public_html/jethro/include/phpword/src/PhPWord/Template/TemplateProcessor.php on line 372

### ISSUE THREAD

**Issue by mathew839** [tbar0970/jethro-pmm#362]
Hi,
       I need help with this error.

This fatal error occurs when attempting to "Mail Merge a Document" from the Person Report: 

The report contains 122 records (for congregation members). The mail merge is to print name tags onto avery labels. using a nametag template document.

There is no timeout error when fewer records are used to mail merge.

Please let me know what addition information you require to resolve this error?

Regards,
          WebMaster
          Christ Church Mortdale

**Comment by tbar0970** [comment]
Hi there

It shouldn't be hitting the time limit with only 122 records.  I wonder if there's complexity hiding in the template file which is slowing down the processing.  Would it be possible to post your template file here?

**Comment by mathew839** [comment]
Tom,
                The template is attached.

Regards,
                Mathew

**Comment by tbar0970** [comment]
Curious.. I tried this template on one Jethro system with ~150 records and it produced the merged file almost immediately.  Then I tried it on a different system (different hosting) and got the timeout.  Will need to dig into it more deeply.

**Comment by mathew839** [comment]
Tom,
                Thanks for the hard work your putting in on this matter!

Regards,
                Mathew McLaughlin

**Comment by tbar0970** [comment]
Hi Matthew
I've just had another look at this, and unfortunately I can now no longer replicate the timeout, on any of my systems, up to 1300 persons!
Can you check if it's still happening for you?


[CCM nametag template.docx](https://github.com/tbar0970/jethro-pmm/files/1147191/CCM.nametag.template.docx)

**Comment by tbar0970** [comment]
(Can you double check the file attached above is the right one to test with)
