### ISSUE TITLE
MDB2 issues with Jethro pmm

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#371]
Hi, 

I'm using 'Bluehost.com' 
I created a mysql database and user. 
Added the user to the database with full permissions. 
I created a directory and uploaded jethro-ppm (from here https://github.com/tbar0970/jethro-pmm) unziped and put database and domain settings in the config file. 

browsing to the directory gave me an MDB2 error.
so I loaded MDB2-dropin to the director, unziped, moved files (from here https://sourceforge.net/projects/jethro-pmm/ )

now I had a fatal error to do with the mysql driver. I googled and discovered someone else having a similar issue (but with a different script... not jethro) and followed their solution which was in install a newer version of MDB2 (from here http://pear.php.net/package/MDB2/download ). It's beta but it s a lot newer.

now I get this error
"Fatal error: Could not connect to database - please check for mistakes in your DSN in conf.php, and check in MySQL that the database exists and the specified user has been granted access. "

Not sure where to turn now.

Any ideas?

thank you

**Comment by vanoudt** [comment]
Hmmm - if you are able to use git, try using the version referenced in the pull request #238  - which totally replaces MDB2 with something more modern. It'll hopefully go mainstream, but Tom's quite a busy man!

**Comment by s4069b** [comment]
Thank you for the very quick response. I really appreciate it. 
That suggestion sounds like it makes sense. 
I will check out the post and see if I can work it out.

**Comment by s4069b** [comment]
Been busy but had a chance to have another look at this problem. 
I am new to git (created account today) - so don't really have much idea. I followed the link to #238 then clicked on your name, which showed me your 'popular repositories' and then clicked the link to 'jethro-pmm' then 'clone or download' and saved the zip - hoping that what I had saved is your fork of the project with all your changes.

After loading that zip to the server I created the conf.php file from the sample and entered the relevant details ... this is what I see.

> Notice: Only variables should be assigned by reference in /opt/php70/lib/php/MDB2.php on line 578
> Notice: Only variables should be assigned by reference in .........jethro/include/init.php on line 51
> Fatal error: Could not connect to database - please check for mistakes in your DSN in conf.php, and check in MySQL that the database exists and the specified user has been granted access. in ......./jethro/include/init.php on line 53

Perhaps I'll wait till the next version and then give it another go.

**Comment by s4069b** [comment]
I found a work around for now - and that was to force the server to use php 5.4 (i.e. an old version). I checked in cpanel to see which versions were available and then added this line to the .htaccess file in the folder I have jethro pmm in: 
# Use PHP 5.4 as default
AddHandler application/x-httpd-php54 .php

I'll close this issue and await the next version of jethro pmm which does away with using MDB2.
