### ISSUE TITLE
custom css does not apply to the /public directory

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#379]
Hi,
I really like the feature in the conf.php file - where you can point to custom css.

However the css changes to not apply to the rosters etc in the /public directory.  

If I drop the custom css into the bottom of /resources/css/jethro-2.19.2.css they do apply. 

I'm guessing that's a minor fix?

**Comment by tbar0970** [comment]
Yep, should be an easy fix.

**Comment by tbar0970** [comment]
Are you using the EXTRA_HEAD_HTML or CUSTOM_LESS_VARS settings?

It should be fine to include the latter in the public interface but I'm uncertain about the former...

**Comment by s4069b** [comment]
I tried using 'EXTRA_HEAD_HTML' in the conf.php file.  
When I saw this follow-up from you I logged in and checked the conf.php file - and I now see where I could adjust the CUSTOM_LESS_VARS settings.  I have not tried that. Sounds like you are saying those CUSTOM_LESS_VARS settings will be seen by the /public interface too.

**Comment by tbar0970** [comment]
Yes, the CUSTOM_LESS_VARS will affect the public area.
If that will solve your problem that would be good.
(I'm not sure what people are using the extra-head-html for and it could potentially cause problems to make it public)

**Comment by s4069b** [comment]
Thanks. I had time to look at it. And that will do the trick.
