### ISSUE TITLE
unable to assign a new 'group category' to 'None' parent category

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#380]
I was adding new group categories and accidentally discovered that after assigning a new category to a parent category I could not assign any further new categories to 'none' parent categories.

After logging out and back in - I was able to create a new category and assign to 'none' parent category.... so I had a work-around.

**Comment by tbar0970** [comment]
Yes I see the problem - even if you choose parent category = "none" it ends up as a child of the category you used as the parent previously.

**Comment by tbar0970** [comment]
This will be something to do with how it stores the last-used parent category in the session to make it easier to create lots of kids under the same parent.

**Comment by s4069b** [comment]
Yes. From memory I could change to another 'parent' - just not 'none'.  
The log-in, log-out work-around takes the edge off it. 

Thanks for all the time you have put into Jethro-pmm. It's nice to find a 'database' system that feels like it's built for an Australian context (even things like people only being about to be in 'one-congregation'... just makes sense). Most US equivalents have a different feel particularly with all the $ side of things added too.

**Comment by tbar0970** [comment]
no longer occurring
