### ISSUE TITLE
cron job to email result of a report query as .pdf or .xls

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#384]
Has anyone requested this yet? Or has anyone had a go?

I'm am interested in being able to setup a cron job to email the result of a report query as a .pdf or .xls. By that I mean... set-up a report as normal and save it. And then use the report/query number in a simple .php script.  

Possible application could be:
- email a list of people who have missed church for three sundays
- email a list of newcomers to a member of the newcomer team
- email upcoming birthdays to the Sunday School coordinator
- generate a regular report (e.g. monthly) of childsafe training details
- maybe send a .pdf of the weekly roster?

If no-one has done it already I could give it a go. I'm guessing the MailChimp sync script would be a starting point?

At this point I have a couple of cron jobs which email with a link to generate the report. but this requires the recipient of the email to log-in to Jethro. I'd like to be able to achieve the same result without needing to give user access to the jethro-pmm.

**Comment by tbar0970** [comment]
Hi there, looks like it hasn't been requested or attempted before, but it's a good idea.

Yes, the mailchimp sync script would be an excellent starting point.

See the includes/emailer.class.php class for emailing functionality

Sending the results as a CSV would be the simplest - there is already code to download a report as CSV so it should be easy to repurpose that.

**Comment by s4069b** [comment]
can you point me to this function printResults() ? not sure where it is.
this application of it outputs what I want to the browser $report->printResults('csv') but I'd rather it went to an email.
thanks

**Comment by tbar0970** [comment]
printResults is part of the person_query class - see db_objects/person_query.class.php

One option is to use ob_start to capture the results:
```
ob_start();
$query->printResults('csv');
$csv = ob_get_clean()
```

**Comment by s4069b** [comment]
sorry, I should have posted again to say that I had found it - and also planned to use ob_start as you have suggested.  
I'll post the script here (tonight perhaps). At the moment it'll send the report as a csv attachment but I'd like to also in include it in the body of the email in html.  Just need to parse the csv string into a table.  I'm pretty rusty on php.
also the server here does not play with swiftmail or the /emailer.class.php script or both for some reason so I just used php mail()

**Comment by tbar0970** [comment]
Sounds good.

If you want to send an HTML email I'd strongly suggest getting swiftmailer to work - it does the hard work of constructing the MIME message envelope etc.  Plus, to integrate your script into Jethro we'll want it to send emails in the same way as the other parts of Jethro.

**Comment by tbar0970** [comment]
See the date_reminder script for some examples of how Jethro constructs and sends emails.

**Comment by s4069b** [comment]
Here's my hack-script. 

If I can get swift mail working on the server I can try to tidy it up. But as it is it does the job adequately. 

<?php
/*****************************************************************
This script will send the results of a report to an email, and attach a .csv of the report.
Make sure you have your 'from email' setup on the same server as jethro because this script will use php mail(). 
Set-up a cron job in this format:
php this-script-and-path report_number from_email to_email
******************************************************************/
//grab the report query number and email addresses
if (count($_SERVER['argv']) == 4) {
	$report_id=$_SERVER['argv'][1];
	$email_from=$_SERVER['argv'][2];
	$email_to=$_SERVER['argv'][3];
} else {
	echo "Usage: php kpc-email-report.php REPORT_ID FROM-EMAIL TO-EMAIL\n";
	exit(1);
}
if(!isset($_SESSION)){ @session_start(); }
//setup the includes etc
define('JETHRO_ROOT', dirname(dirname(__FILE__)));
set_include_path(get_include_path().PATH_SEPARATOR.JETHRO_ROOT);
if (!is_readable(JETHRO_ROOT.'/conf.php')) {
	trigger_error('Jethro configuration file not found.  You need to copy conf.php.sample to conf.php and edit it before Jethro can run', E_USER_ERROR);
	exit();
}
require_once JETHRO_ROOT.'/conf.php';
if (!defined('DSN')) define('DSN', constant('PRIVATE_DSN'));
require_once JETHRO_ROOT.'/include/init.php';
require_once JETHRO_ROOT.'/include/user_system.class.php';
$GLOBALS['user_system'] = new User_System();
$GLOBALS['user_system']->setPublic();
require_once JETHRO_ROOT.'/include/system_controller.class.php';
$GLOBALS['system'] = System_Controller::get();
// Check that we have a report
if (!(int)$report_id) {
	trigger_error("No Report ID found - correct your config within ".__FILE__, E_USER_ERROR);
	echo "have no report";
}
// Use the report to generate the subject and content of the email using the output buffer, then clear the buffer
$report = $GLOBALS['system']->getDBObject('person_query', $report_id);
$reportname = $report->getValue('name');
if (empty($reportname)) $reportname = 'Jethro-Report-'.date('Y-m-d_H:i');
ob_start();
$report->printResults('csv');
$csv_string = ob_get_contents();
ob_end_clean();
// turn csv into html table for email content
$csv_array = preg_split("/\\r\\n|\\r|\\n/", $csv_string);
$rows=(count($csv_array)-1);
$x=0; 
$email_html="<html><head><title>HTML email from Jethro-pmm</title></head><body>This is the result of a report generatated from Jethro-pmm<br><br>Report name: ".$reportname."<br><br>";
  $email_html.="<table border='1' cellpadding='5' cellspacing='1'>";
while($x < $rows) {
    $line = explode(',',$csv_array[$x]);
	$email_html.="<tr>";
     	if ($x==0) {
     	foreach ($line as $cell) {$email_html.="<th>".(str_replace('"', "", $cell))."</th>";}
	} else {
     	foreach ($line as $cell) {$email_html.="<td>".(str_replace('"', "", $cell))."</td>";}
	}
 	$email_html.="</tr>";	
  $x++;
} 
$email_html.="</table></body></html>";
//
// send the email with attachment
$eol = PHP_EOL;
$email_subject="Jethro Report: ".$reportname;
$file_name=$reportname.".csv";
$content = chunk_split(base64_encode($csv_string));
$uid = md5(uniqid(time()));
$header = "From: ".$email_from.$eol;
$header .= "MIME-Version: 1.0".$eol;
$header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"";
$message = "--".$uid.$eol;
$message .= "Content-type:text/html; charset=iso-8859-1".$eol;
$message .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
$message .= $email_html.$eol;
$message .= "--".$uid.$eol;
$message .= "Content-Type: text/csv; name=\"".$file_name."\"".$eol;
$message .= "Content-Transfer-Encoding: base64".$eol;
$message .= "Content-Disposition: attachment; filename=\"".$file_name."\"".$eol.$eol;
$message .= $content.$eol;
$message .= "--".$uid."--";
 if (mail($email_to, $email_subject, "$message", $header)) {
 echo $reportname."  mail send ... OK";
 } else {
 echo $reportname."  mail send ... ERROR!";
 }

**Comment by s4069b** [comment]
I WILL tidy this report emailing script because it has potential to be very useful. (actually, I ran a quick test script and swifmail IS working for me - I logged a service request some time back but realise now I never got back to re-check it). 

If the script runs with an ini file (similar to the date reminder script) then the ini file can be used to send a particular report to a 'group' or to over-ride email/s. (e.g. to send list of people who have missed church to the pastoral care 'group', or send birthdays to the Sunday school teachers or...).

In fact one ini file could be used to send particular reports to particular groups or individuals each day of the week. Monday - absences report to pastoral care group, Tuesday -newcomers report to welcomers group, Wednesday - people to pray for to the prayer group, Friday -birthday report to Sunday school teachers group. You could have any number of reports sent each day.

You could do away with the need for the 'date reminder' script by creating a report instead. 

A related thought - which may be helpful with 'easy jethro' too.  It's possible you could set-up only one single master cron script for each database and use an arrangement of ini files saved in a single folder with the name of the ini file corresponding to a cron-time-interval-code (min-hour-day-month_weekday) (e.g. 0_9_1_1_1_date_reminder.ini or 0_9_1_1_2_report_send.ini  or 0_9_1_1_5_roster_reminder.ini or 5_1_1_1_1_task_reminder). The master script checks every half-hour for any scripts required to be run.  
In Jethro you could have the option when viewing a report - to set-up reminders. Or when setting up a roster-view - to setup reminders, or?

**Comment by s4069b** [comment]
Here is a re-write using the email.class (swiftmailer).

This is a basic php script to send a Jethro-pmm REPORT as an html EMAIL with a copy of the report TABLE and with the same report ATTACHED as a .csv file. 

usage:  php  /path/to/email_report.php /path/to/email_report.ini 

at this stage the ini file only contains the following
- report number
- from email address
- from name
- to email address

I will attempt to insert the code below, but the preview looks a bit odd, so I have attached both files as a .zip.


------- email_report.php ------
`<?php
/*****************************************************************
This script will send the results of a report in an email and also attached as a .csv file. 

usage:  php /path/to/this-script-and-path.php /pathe/to/variables-in-a-file.ini

Possible application could be:
- email a list of people who have missed church for three sundays to the minister
- email a list of newcomers to welcome coordinator
- email upcoming birthdays to the Sunday School coordinator
- generate a regular report (e.g. monthly) of childsafe training details for childsafe administrator

The recipient/s of the email need not be giving user access to Jethro. 

You can adjust the format of the report in Jethro without needing to change this script or the cron job that calls it. 

With a bit of work this script could be modified to send a report to a 'group' and/or an over-ride email or emails. 
Or you could work a bit harder and use one ini file to send multiple different reports. 

******************************************************************/
//
//read the ini file
//
if (empty($_SERVER['argv'][1]) || !is_readable($_SERVER['argv'][1])) {
	echo "You must specify an ini file as the first argument \n";
	echo "Eg:  php date_reminder.php my-config-file.ini \n";
	exit;
}
ini_set('display_errors', 1);
$ini = parse_ini_file($_SERVER['argv'][1]);
//
//setup the includes etc
//
define('JETHRO_ROOT', dirname(dirname(__FILE__)));
set_include_path(get_include_path().PATH_SEPARATOR.JETHRO_ROOT);
if (!is_readable(JETHRO_ROOT.'/conf.php')) {
	trigger_error('Jethro configuration file not found.  You need to copy conf.php.sample to conf.php and edit it before Jethro can run', E_USER_ERROR);
	exit();
}
require_once JETHRO_ROOT.'/conf.php';
if (!defined('DSN')) define('DSN', constant('PRIVATE_DSN'));
require_once JETHRO_ROOT.'/include/init.php';
require_once JETHRO_ROOT.'/include/user_system.class.php';
$GLOBALS['user_system'] = new User_System();
$GLOBALS['user_system']->setPublic();
require_once JETHRO_ROOT.'/include/system_controller.class.php';
$GLOBALS['system'] = System_Controller::get();
//
// Check that we have a report
//
if (!(int)$ini['REPORT_ID']) {
	trigger_error("No Report ID found - correct your config within ".__FILE__, E_USER_ERROR);
	echo "have no report";
}
//
// Use the report to generate the subject and content of the email using the output buffer, then clear the buffer
//
$report = $GLOBALS['system']->getDBObject('person_query', (int)$ini['REPORT_ID']);
$reportname = $report->getValue('name');
if (empty($reportname)) $reportname = 'Jethro-Report-'.date('Y-m-d_H:i');
ob_start();
$report->printResults('csv');
$csv_string = ob_get_contents();
ob_end_clean();
//
// turn csv into html table for email content
//
$csv_array = preg_split("/\\r\\n|\\r|\\n/", $csv_string);
$rows=(count($csv_array)-1);
$x=0; 
$email_html="<html><head><title>HTML email from Jethro-pmm</title></head><body>This is the result of a report generatated from Jethro-pmm<br><br> <i>(If the rest of this email is blank (and the attached .csv file empty) then the report returned no results.</i><br><br><h2>Report name: ".$reportname."</h2><br><br>";
  $email_html.="<table border='1' cellpadding='5' cellspacing='1'>";
while($x < $rows) {
    $line = explode(',',$csv_array[$x]);
	$email_html.="<tr>";
     	if ($x==0) {
     	foreach ($line as $cell) {$email_html.="<th>".(str_replace('"', "", $cell))."</th>";}
	} else {
     	foreach ($line as $cell) {$email_html.="<td>".(str_replace('"', "", $cell))."</td>";}
	}
 	$email_html.="</tr>";	
  $x++;
} 
$email_html.="</table></body></html>";
$email_subject="Jethro Report: ".$reportname;
$file_name=$reportname.".csv";
//
// send the email with .cvs attachment
//
require_once JETHRO_ROOT.'/include/emailer.class.php'; 
	$message = Emailer::newMessage()
	  ->setSubject($email_subject)
	  ->setFrom(array($ini['EMAIL_FROM'] => $ini['EMAIL_FROM_NAME']))
	  ->setBody("Jethro report in html format with .csv attachment")
	  ->addPart($email_html, 'text/html')
	  ->setTo($ini['EMAIL_TO']);
	$attachment = new Swift_Attachment($csv_string, $file_name, 'text/csv');
	$message->attach($attachment);    
	$res = Emailer::send($message);
	if (!$res) {
		echo "Failed to send report (".$reportname.") to ".$ini['EMAIL_TO']."\n";
	} else {
		echo "Sent report (".$reportname.") to ".$ini['EMAIL_TO']."\n";
	}`

------ email_report_sample.ini -----

`; Edit the values below and save as another filename
;
; Then run   php email_report.php /path/to/my/config.ini
;
REPORT_ID=4;
EMAIL_FROM='email@address.com';
EMAIL_FROM_NAME='no-reply';
EMAIL_TO='emailrecipient@address.com';`

--------------------


[Archive.zip](https://github.com/tbar0970/jethro-pmm/files/1162363/Archive.zip)

**Comment by vanoudt** [comment]
Really like the look of this!

Personally, I'm not the biggest fan of .ini files to run things like this. I'd much rather have something in the database - so that I don't have to SSH in to change something as simple as what reports get emailed to me etc.

I notice that this hasn't been merged, though... could you repopen this issue until then? 
Also, @s4069b : do you have a github account - that way you could put in a formal pull-request for this... (Though I'm sure Tom can take care of it without that!)

**Comment by s4069b** [comment]
I updated this script so that 
- the ini file can include more than one 'to' address and 
- so that you can choose if you want the report attached or not. 

I continue to have issues with swiftmailer on our server, so I also included the option of using php mail() (just change 0 to 1 in the ini file). 

[Archive.zip](https://github.com/tbar0970/jethro-pmm/files/1169418/Archive.zip)

**Comment by s4069b** [comment]
I would like to be able to give the option of emailing a report to a 'jethro-pmm group' (so long as it does not contain too many email addresses) - so for example the 'pastoral care group'.  

But I don't really know where to start.

**Comment by tbar0970** [comment]
You'll want something like

$group = $GLOBALS['system']->getDBObject('person_group', $groupid);
$members = $group->getMembers();
$recipients = Array();
foreach ($members as $m) {
    $recipients[] = $m['email'];
}

BTW when I committed your v1 script into the Jethro code I made a handful
of changes.  Can you make sure you've incorporated them into your work in
progress so I don't have to re-apply them when I merge.

(Or even better, install GIT so we can use that to manage the integration -
that's what it's for!)

**Comment by s4069b** [comment]
thanks for the info re groups.

and sorry about messing you around with 'versions'.  I will have a read on how to use GIT before making any further comments.

**Comment by s4069b** [comment]
I just submitted my first ever pull request. should I close this 'issue' now?

**Comment by tbar0970** [comment]
Pull request looks good.  Let's close this and I'll merge the pull request when I can.
