### ISSUE TITLE
Copying service item copies wrong personnel

### ISSUE THREAD

**Issue by andrew-david** [tbar0970/jethro-pmm#385]
Really grateful for the copying service items feature - it's a big time-saver.

Just a little issue: when I copy last week's service items, it also copies last week's personnel - even when the personnel is set up to be dependent on the weekly roster. It's obviously easy to work around (deleting the personnel and saving, then Jethro autocompletes correctly from the roster) - would it be tricky to fix permanently?

**Comment by tbar0970** [comment]
Thanks for reporting.  This has been fixed in Issue #351 which will be in the next release, due out within the week!
