### ISSUE TITLE
script to send a print/email version of Sunday's roster to the persons listed in the roster

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#391]
I'd like to write a php script to send a print/email version of Sunday's roster to each of the persons listed in the roster. 

I have a little routine which I am sure could be replaced with a php script and set to run every Thursday or Friday.

1. display a roster view for the coming Sunday (or display a roster view for the next 7 days would be sufficient to capture the roster for Sunday)
2. click on 'show the print/email version'
3. select all and copy (the print/email version)
4. click on 'email all listed persons'
5. enter subject line "roster reminder for Sunday"
6. paste the 'print/email version' of the roster view into the email
7. hit send. 

I know how to get php to send an email etc. But any tips / pointers / or **help with  SQL query or existing jethro code for step 1. 2. and 4. would be fantastic**. Otherwise I'll start hacking away next week some time and see what I can come up with.

**Comment by vanoudt** [comment]
You should be able to get all that without having to write any SQL... Have
look at the db_objects/roster_view.class.php file, and methods
printSingleViewTable()

Sounds like a great idea!

Pet peeve: Just not another ini file though! 😀

**Comment by s4069b** [comment]
Thanks for the pointers.
re ini files - I don't have the confidence to get in and hack away at the main jethro code and contaminate the database! If I did then a two-stage roster reminder might be the go. 
1. email the roster coordinator person (or someone?) and tell them to check the upcoming roster roster
2. once that person has checked it - it gets sent.
Or you could check off weeks ahead of time. 
Or choose to bypass the 'checking' step.
etc
but then again... most often 'simple' is best... so scrap all that... and stick with ini files  😀

**Comment by tbar0970** [comment]
An alternative approach here - which I've often thought about- is to email each assignee individually: 
"This Sunday you've been allocated to...."
(I think this is recorded in a separate issue).

**Comment by tbar0970** [comment]
There's also code you might find useful in 
calls/call_display_roster.class.php

**Comment by s4069b** [comment]
Thanks for the pointers. 
Here are the two key bits of code.
1. build the html for the roster table
ob_start();
$view->printView($start_date, $end_date, FALSE, TRUE);
$longstring = ob_get_contents();
ob_end_clean();

2. build the string of email addresses
$emails="roster-coordinator@yourchurch.org.au";
$assignees=$view->getAssignees($start_date, $end_date);
foreach($assignees as $row => $innerArray){
    if (!empty($innerArray['email'])){
    $emails.=','.$innerArray['email'];
  }
  }

Now it they just need putting together into a script.

My thoughts.
- roster coordinator email could be set through admin (I'm not game to do that part)
- or roster coordinator email could be over-ridden by the member/s of a particular group - so the veritable becomes a group number
- or the roster coordinator email and group can be over-ridden by a hard-set email address in an .ini file (yes bring on those .ini files!)

two emails to be sent
- one to the assignees
- one to the coordinator including a note listing those assignees w/o an email

The first email (to the assignees) should include a link to the full roster and a note about what to do if they can't do the task assigned to them.

Does all that sound about right?

**Comment by s4069b** [comment]
I'll come back and complete this later

<?php
/*****************************************************************
This?
******************************************************************/
//
//setup the includes etc
//
define('JETHRO_ROOT', dirname(dirname(__FILE__)));
set_include_path(get_include_path().PATH_SEPARATOR.JETHRO_ROOT);
if (!is_readable(JETHRO_ROOT.'/conf.php')) {
	trigger_error('Jethro configuration file not found.  You need to copy conf.php.sample to conf.php and edit it before Jethro can run', E_USER_ERROR);
	exit(1);
}
require_once JETHRO_ROOT.'/conf.php';
define('DB_MODE', 'private');
//if (!defined('DSN')) define('DSN', constant('PRIVATE_DSN'));
require_once JETHRO_ROOT.'/include/init.php';
require_once JETHRO_ROOT.'/include/user_system.class.php';
$GLOBALS['user_system'] = new User_System();
$GLOBALS['user_system']->setPublic();
require_once JETHRO_ROOT.'/include/system_controller.class.php';
$GLOBALS['system'] = System_Controller::get();
require_once JETHRO_ROOT.'/db_objects/roster_view.class.php';
//
// begin
//
$roster_id = 1;
$view = $GLOBALS['system']->getDBObject('roster_view', $roster_id);
				$start_date = date("Ymd");
				$end_date = date('Ymd', strtotime("+6 day"));
ob_start();
$view->printView($start_date, $end_date, FALSE, TRUE);
$longstring = ob_get_contents();
ob_end_clean();
$emails="";
$assignees=$view->getAssignees($start_date, $end_date);
foreach($assignees as $row => $innerArray){
    if (!empty($innerArray['email'])){
    $emails.=','.$innerArray['email'];
  }
  }
echo $emails;
echo $longstring;
?>

**Comment by tbar0970** [comment]
Looks good.

I think an INI file is the best approach at this stage, since
a) the parameters are too numerous and too complex to be passed via the command line
b) you might want to run several iterations of the script with different parameters (eg one per congregation)

Down the track we could think about moving some of the settings to the roster_view object as you describe above.  The tricky bit here is that not everyone will have a cron job set up on their server and if it's not, we don't want to give them the false impression that emails will get sent.  The way to solve this is to have some flag in the database that records when the cron job last ran, which the web interface can look at to see if the cron job is active.  This is all extra work!

**Comment by s4069b** [comment]
If i've done it correctly there should be a pull request for this.
I'm sure it can be improved by having others look at it.
Should I close this issues now? (I'm not 100% on the protocol here).

**Comment by s4069b** [comment]
I removed my last pull request and have added another - this time roster_reminder.php and roster_reminder_sample.ini are more complete.
