### ISSUE TITLE
User with permission to View Services can't view the details/runsheet

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#395]
User with the permission to 'Services - view' can view the list of services, but can't click on the service in order to view the songs/prayers etc.

In order to allow the user into that view, I've given her the permission 'Services - edit individual'. Is there a way for a user to be able to see the details without permission to edit them?

**Comment by tbar0970** [comment]
If she has the "services - view" permission then she should be allowed to view service run sheets.
Will fix.
