### ISSUE TITLE
mailchimp_sync.php stopped working after upgrade to Jethro-pmm v2.20.0

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#396]
Started getting this error after upgrade the other day. Only just had a chance to have a look at it - but I'm not sure what the error means?

Fatal error: Class 'DrewM\MailChimp\Mailchimp' not found in /public_html/jethro/scripts/mailchimp_sync.php on line 50

**Comment by tbar0970** [comment]
It means Jethro can't find a file it needs.
I haven't experienced this anywhere else.
Are you sure you replaced all the files in the upgrade properly?  
If there was a mix of older code with the new mailchimp_sync script it would explain this problem.

**Comment by s4069b** [comment]
Thanks. That was my first guess. Not that I quite follow what line 50 is calling for?
I have checked and the directory structure and the version of the mailchimp_sync script and it all appears to be consistent with the latest version.

If I run the old version of mail chimp_sync in the new directory structure I get this error:
Fatal error: Call to undefined function check_db_result() in /home1/churchj9/public_html/jethro/scripts/mailchimp_sync_old.php on line 95

**Comment by s4069b** [comment]
I had another look and can't figure it out. I installed Jethro-pmm on another computer and repeated the same error.

My work-around at the moment - is to download MailChimp.php from here https://github.com/drewm/mailchimp-api/tree/master/src
and load it into a new 'mail chimp' director in the jethro/scripts director
and insert this this line in bold into mailchimp_sync.php
require_once 'vendor/autoload.php';
**include('mailchimp/MailChimp.php');** 
use \DrewM\MailChimp\Mailchimp;

**Comment by funkydan2** [comment]
Sorry not to be any help, but I've just run the script manually (normally it runs via cron) and get the same error as @s4069b. It was an upgrade, but I followed the process I normally do - renaming the old folder, and then unzipping the new version, so there shouldn't be old scripts around.

**Comment by tbar0970** [comment]
OK thanks, I'll look into this.

**Comment by tbar0970** [comment]
OK, I still haven't managed to replicate this problem myself.

First question: What version of PHP are you using?  (I'm on PHP7)

Second question: Does changing line ~40 from
`require_once 'vendor/autoload.php';`
to
`require_once dirname(dirname(__FILE__)).'/vendor/autoload.php';`
make any difference?

**Comment by funkydan2** [comment]
Hi Tom, I'm running on PHP 7.18.

Changing that line doesn't fix the problem, but throws a different error:
`PHP Fatal error:  Uncaught Exception: cURL support is required, but can't be found. in /var/www/html/jethro/vendor/drewm/mailchimp-api/src/MailChimp.php:183`

**Comment by funkydan2** [comment]
Actually, strangely, this cURL error on line 183 comes up now whether I put dirname in at line 48 or not. This morning the error was that it wasn't finding the drewm class.

**Comment by funkydan2** [comment]
So used my brain - since I'm running Jethro on my own server I installed the php-curl package and now it's working.

**Comment by s4069b** [comment]
is it working now with or without the change around line 40 (I don't have access to the server to fault-find at the moment)?

**Comment by funkydan2** [comment]
Without the change.

**Comment by s4069b** [comment]
I guess that means cURL is a server perquisite - unless you manually load MailChimp.php from here https://github.com/drewm/mailchimp-api/tree/master/src and adjust the code?

**Comment by s4069b** [comment]
OK I have run phpinfo() and this it what it says
php 7.0.12
curl enabled 7.24.0

I tried testing the both the original file and the change at line ~40.  both continue to throw the error.
I have reverted to the work around and it's doing the job at the moment.  Wait and see if anyone else has an issue. sounds like it's a server setup issue?

**Comment by tbar0970** [comment]
Yes, sounds like it has to be some server setup issue. Maybe you could post the whole of phpinfo() result here and I'll look for any clues?

**Comment by tbar0970** [comment]
OK, I've now replicated it on one of my servers. Not sure what's going on but I suspect it's a capitalisation problem since it's occuring on linux (case sensitive) but not windows (case insensitive).

**Comment by tbar0970** [comment]
Fixed in v2.21.1 just released.

**Comment by s4069b** [comment]
Thank you. Just installed 2.21.1. Working nicely.
