### ISSUE TITLE
Need to define SMTP_PORT in conf.php?

### ISSUE THREAD

**Issue by funkydan2** [tbar0970/jethro-pmm#397]
With @s4069b having worked on a roster reminder email script, I've had a play with getting automated roster reminders sent.

For my mail server ([Zoho](http://mail.zoho.com)) I wasn't able to connect to the mail server without adding the line
`define (SMTP_PORT, '465');`
to conf.php.

However, this isn't in the sample configuration file and I also couldn't see where you could set the SMTP port in the web interface.

Not sure if this is a bug, or I've missed the setting somewhere else.

**Comment by s4069b** [comment]
yes I forgot to mention that. My understanding is that swiftmailer accepts that variable, but it happens not to be specified in the config file.  
i.e. I think it's just something missed in the config file.
In my case the server blocks all ports that would work for smtp hence the php mail() alternative for the roster reminder script.

**Comment by funkydan2** [comment]
...and this variable is also required for the email_report.php script to work.

**Comment by s4069b** [comment]
yes and the date_reminder script and any other jethro emails

**Comment by tbar0970** [comment]
Pull request has fixed the sample config file.

We should also add it to the DB to make it editable in the system config page.
