### ISSUE TITLE
Invalid characters can be passed to SMS gateway

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#401]
The most common character set for SMS messages is GSM0338.
Jethro currently does no filtering of characters
which can mean if somebody types in a funny character (eg non-breaking-space) into the "message" box, that char gets passed through to the SMS gateway, which may or may not handle it well.

Jethro should (perhaps configurably) strip out any non-GSM0338 chars before calling the SMS gateway.

**Comment by vanoudt** [comment]
Got a draft solution to this, and the pasting of HTML at the same time!
Will probably get around to tidying it up in the next week or so...

**Comment by vanoudt** [comment]
Eventually put in the PR for this - #411  :-) It does currently require setting the SMS_ENCODING define...

**Comment by tbar0970** [comment]
Resolved in last release
