### ISSUE TITLE
Undefined index when importing some CSVs

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#41]
Undefined index: email 
Line 80 of /home/jethro/code/2.9.4/templates/person_list.template.php

Request: Array
(
   [view] => admin__import
   [groupid] => 55
)

Array
(
   [0] => Array
       (
           [file] => /home/jethro/code/2.9.4/templates/person_list.template.php
           [line] => 80
           [function] => _handleError
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
                   [0] => 8
                   [1] => Undefined index: email
                   [2] => /home/jethro/code/2.9.4/templates/person_list.template.php
                   [3] => 80
                   [4] => [Object/Array]
               )

```
   )
```

   [1] => Array
       (
           [file] => /home/jethro/code/2.9.4/db_objects/family.class.php
           [line] => 267
           [args] => Array
               (
                   [0] => /home/jethro/code/2.9.4/templates/person_list.template.php
               )

```
       [function] => include
   )
```

   [2] => Array
       (
           [file] => /home/jethro/code/2.9.4/include/db_object.class.php
           [line] => 503
           [function] => _printSummaryRows
           [class] => family
           [type] => ->
           [args] => Array
               (
               )

```
   )
```

   [3] => Array
       (
           [file] => /home/jethro/code/2.9.4/db_objects/family.class.php
           [line] => 222
           [function] => printSummary
           [class] => db_object
           [type] => ->
           [args] => Array
               (
               )

```
   )
```

   [4] => Array
       (
           [file] => /home/jethro/code/2.9.4/views/view_10_admin__5_import.class.php
           [line] => 292
           [function] => printSummary
           [class] => family
           [type] => ->
           [args] => Array
               (
                   [0] => 
                   [1] => [Object/Array]
               )

```
   )
```

   [5] => Array
       (
           [file] => /home/jethro/code/2.9.4/include/system_controller.class.php
           [line] => 153
           [function] => printView
           [class] => View_Admin__Import
           [type] => ->
           [args] => Array
               (
               )

```
   )
```

**Comment by edwhiting** [comment]
What are the steps to reproduce this?  Do you have an example CSV file?

**Comment by tbar0970** [comment]
I suspect it could be provoked by trying to perform an import without an "email" column in the CSV. Email is not a required field, so this should quietly make it blank.

**Comment by tbar0970** [comment]
No longer occurring
