### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#412]
I am trying to set up version 2.21.1. I have merged some data from an older version on an older PC into this newer version.

In the previous version, there was a date filed of which you could like a field from a drop down box (say to track the dates of working with Children Checks) along with a note.

I have noticed in this newer version there isn't a way of linking a date with a field from a drop down box and a note.

for example
![image](https://user-images.githubusercontent.com/32403035/31038042-d16ac274-a5b7-11e7-9578-e0e4d5acda10.png)

there is only provision for the drop down box

and for the date field
![image](https://user-images.githubusercontent.com/32403035/31038100-4058c604-a5b8-11e7-8d0e-23b3c598af81.png)

I see that there is a check box to enable a note to be attached to the date field.

This is my question:

Is it possible to have a field from the drop down list (like in the first screen shot) to be linked to the date field (as the note for the date field is linked).

thank you for your assistance.

**Comment by vanoudt** [comment]
Interesting idea.... at the moment we just have multiple custom fields 
set up for this sort of thing... (that is, one custom date field per 
parameter (baptism, WWC, etc.)).

**Comment by tbar0970** [comment]
Hi Glen

In the old version, when editing a person, it gave you a dropdown box to select a field (eg "baptism date") and then the input boxes to enter the date value and note.

In the new version, when editing a person, it lists out *all* the fields you've configured (eg "baptism date") and gives you the boxes to enter a value for each.  So the logic is the same but the inteface is a bit different.

When upgrading an old database, old date fields are converted into new custom fields.

Based on your screenshots, it looks like you need to add several custom fields, called "baptism date", "marriage date", etc etc - all of type "date".

For WWCC it's usually best to have a text field called "WWCC Number", a date field for the expiry date, etc.
