### ISSUE TITLE
Problem upgrading

### ISSUE THREAD

**Issue by mpedant** [tbar0970/jethro-pmm#414]
Hi

I'm trying to upgrade from 2.14 (sorry!) to the latest version.  I've followed the instructions, including running all of the SQL updates, but on trying to log-in to my new install I get the following:

<code>Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE symbol = 'NOTES,PHOTOS,DATES,ATTENDANCE,ROSTERS&SERVICES,SERVICEDETAILS,DO' at line 3' in /path/to/install/include/config_manager.class.php:139 Stack trace: #0 /path/to/install/include/config_manager.class.php(139): PDO->exec('UPDATE setting\r...') #1 /path/to/install/include/config_manager.class.php(54): Config_Manager::saveSetting('NOTES,PHOTOS,DA...', Array) #2 [internal function]: Config_Manager::migrateEnabledFeatures() #3 /path/to/install/include/config_manager.class.php(14): call_user_func(Array) #4 /path/to/install/include/init.php(57): Config_Manager::init() #5 /path/to/install/index.php(38): require_once(' in /path/to/install/include/config_manager.class.php on line 139</code>

Not really sure where to start troubleshooting this.  Any ideas?

Thanks.

**Comment by tbar0970** [comment]
hi @mpedant you've discovered a bug, which I just fixed in the commit above.  If you download config_manager.class.php from https://raw.githubusercontent.com/tbar0970/jethro-pmm/9af17160c53137a808b886c6c812b61dcf5cc32c/include/config_manager.class.php and use it to replace the file in the include folder of your Jethro system, it should be resolved.

**Comment by mpedant** [comment]
Thanks Tom, I'll give that a try when I've summoned up the energy!

Mark.

**Comment by Dav9000** [comment]
Tom,
I'm upgrading from v2.18.2 to v2.21.2, and I got the same error as mpendant.
I downloaded the config_manager.class.php file from your link, and now I'm getting the message -

Warning: PDO::quote() expects parameter 1 to be string, array given in /var/www/jethro/include/jethrodb.php on line 94

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE symbol = 'ENABLED_FEATURES'' at line 3' in /var/www/jethro/include/config_manager.class.php:139 Stack trace: #0 /var/www/jethro/include/config_manager.class.php(139): PDO->exec('UPDATE setting\r...') #1 /var/www/jethro/include/config_manager.class.php(54): Config_Manager::saveSetting('ENABLED_FEATURE...', Array) #2 [internal function]: Config_Manager::migrateEnabledFeatures() #3 /var/www/jethro/include/config_manager.class.php(14): call_user_func(Array) #4 /var/www/jethro/include/init.php(57): Config_Manager::init() #5 /var/www/jethro/index.php(38): require_once('/var/www/jethro...') #6 {main} thrown in /var/www/jethro/include/config_manager.class.php on line 139

The v2.21.2 version of config_manager.class.php that I used originally has these lines -

		self::saveSetting(ENABLED_FEATURES, $value);

		self::saveSetting(LOCK_LENGTH, $secs/60);

The version of config_manager.class.php that I downloaded from your link has these lines -

		self::saveSetting('ENABLED_FEATURES', $value);

		self::saveSetting('LOCK_LENGTH', $secs/60);

The single quotes around ENABLED_FEATURES and LOCK_LENGTH seem to be the only differences between the 2 versions.

Any help appreciated.

Dav9000

**Comment by tbar0970** [comment]
Hi @Dav9000 
I looked at this again and my previous fix was insufficient.  
Can you try this new version of config manager:  https://raw.githubusercontent.com/tbar0970/jethro-pmm/ae93206efb0d90e5ff6a7a44a1ef370def64c36e/include/config_manager.class.php

Let me know if the problem persists.

**Comment by Dav9000** [comment]
Thanks Tom. That solved the problem.

Dav9000

**Comment by Dav9000** [comment]
Tom,
I'm ok with this issue being closed. I don't think I have permissions to close it because I'm not the originator.
Dav9000
