### ISSUE TITLE
More flexible status options

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#419]
Currently the status "contact" is built-in and cannot be renamed or removed.
This is because there is a business rule attached to it - only contacts can have congregation = blank.
It would be nice to be able to remove or rename the "contact" option
AND to be able to configure which of the status options allow blank congregations.

**Comment by GatesheadBen** [comment]
+1

To keep the interface as simple and intuitive as possible for admins it would be useful to be able to change the label of the contact field (I've been asked for "community/friend".

**Comment by tbar0970** [comment]
This is covered in #1035
