### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by gbfarah** [tbar0970/jethro-pmm#42]
When installing Jethro , I get the following mysql error after completing first page of the installer

_doQuery: [Error message: Could not execute statement] [Last executed query: CREATE TABLE person_group_headcount ( `date` DATE NOT NULL, `person_groupid` INT(11) NOT NULL, `number` INT(11) NOT NULL, PRIMARY KEY (`date`, `person_groupid`), CONSTRAINT FOREIGN KEY (`person_groupid`) REFERENCES `_person_group` (`id`) ) Engine=InnoDB;] [Native code: 1005] [Native message: Can't create table 'jethro.person_group_headcount' (errno: 150)]
SYSTEM ERROR (ERROR)
Database Error: _doQuery: [Error message: Could not execute statement] [Last executed query: CREATE TABLE person_group_headcount ( `date` DATE NOT NULL, `person_groupid` INT(11) NOT NULL, `number` INT(11) NOT NULL, PRIMARY KEY (`date`, `person_groupid`), CONSTRAINT FOREIGN KEY (`person_groupid`) REFERENCES `_person_group` (`id`) ) Engine=InnoDB;] [Native code: 1005] [Native message: Can't create table 'jethro.person_group_headcount' (errno: 150)]

Any ideas. I'm keen on evaluating this for my church with probable move to easy jethro as we grow

**Comment by tbar0970** [comment]
Thanks for reporting.  This is a problem caused by the way the new headcount feature tries to create its database references. I will fix shortly.

**Comment by gbfarah** [comment]
Many thanks. Let me know and I can give it a try .... and God bless :)

**Comment by tbar0970** [comment]
Fixed in v2.10.2
