### ISSUE TITLE
create_function is deprecated in PHP7.2

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#429]
PHP create_function() appears to be used in the db_objects classes.

In PHP7.2 this causes messages like this to appear in the logs
[Thu Dec 28 14:14:27.424627 2017] [php7:notice] [pid 919] [client 127.0.0.1:46004] Function create_function() is deprecated - Line 50 of /DATA/htdocs/jethro/db_objects/abstract_note.class.php, referer: http://scott/jethro/index.php?view=_edit_person&personid=1
and Jethro displays 
An error occurred. Please contact your system administrator for help.

**Comment by tim-pearce** [comment]
I can fix this, but I've never contributed to a github (or any online) project before so it may take me a while to figure out how to contribute.

**Comment by tbar0970** [comment]
Merged
