### ISSUE TITLE
Locking Problem After v2.21.2 Upgrade

### ISSUE THREAD

**Issue by Dav9000** [tbar0970/jethro-pmm#433]
Hello,

I have upgraded our Jethro system from v2.18.2 to v2.21.2.

I get this error whenever I tried to edit anything -

"Lock warning
Your lock on this object has now expired. You cannot save the changes you have made. Would you like to reload the form and try again?"

If I click Yes the message prints again.

If I click No I get a read-only version of the screen.

It seems to happen whatever I try to edit.  Just clicking on Edit in someone's details triggers the error.

When I run this -

    SELECT * FROM db_object_lock ORDER BY objectid, userid

I get -

+----------+--------+-----------+-------------+---------------------+
| objectid | userid | lock_type | object_type | expires             |
+----------+--------+-----------+-------------+---------------------+
|      266 |    266 |           | person      | 2018-01-08 14:51:44 |
+----------+--------+-----------+-------------+---------------------+

I am not person number 266. Number 266 logged in on the 8th January and changed their password.  This happened before the upgrade.  I didn't notice any problems at the time, but I don't think I tried to edit anything.

After I get the "lock on this object has now expired" error message, db_object_lock looks like this -

+----------+--------+-----------+-------------+---------------------+
| objectid | userid | lock_type | object_type | expires             |
+----------+--------+-----------+-------------+---------------------+
|        4 |      1 |           | person      | 2066-01-21 12:37:49 |
|      266 |    266 |           | person      | 2018-01-08 14:51:44 |
+----------+--------+-----------+-------------+---------------------+

I am user number 1.  In that instance I was trying to edit person number 4.

When I log out of Jethro, the first line in db_object_lock disappears.

Number 266 is not in the office today.  If they were I'd try to get them to log in to see if that clears the lock.  I can't reset their password and log in as them because I can't edit their record.

I could delete the row from db_object_lock using mysql, but I don't know what other tables and views need to be adjusted.

Any help appreciated.

Thanks and Regards,
Dav9000

**Comment by Dav9000** [comment]
User number 266 sent me their password.
I logged in as them, and logged out again.  The row in db_object_lock disappeared!

Tragically, it didn't fix the problem.  I get the same error whenever I try to edit anything.

Regards,
Dav9000

**Comment by Dav9000** [comment]
PS.

It might have something to do with the expiry date of the lock being in the year 2066 -

+----------+--------+-----------+-------------+---------------------+
| objectid | userid | lock_type | object_type | expires             |
+----------+--------+-----------+-------------+---------------------+
|        4 |      1 |           | person      | 2066-01-21 14:16:49 |
+----------+--------+-----------+-------------+---------------------+

If the system always assigns an invalid value to the expiry date for a lock, that might trigger a "lock expired" error message.

Regards,
Dav9000

**Comment by tbar0970** [comment]
Can you go to the system configuration page in jethro and check the lock length setting. I wonder if it went wonky in the upgrade.  If no insights there can you check the date on your server...

**Comment by Dav9000** [comment]
Tom,
That was indeed the problem.
Lock length in the system configuration page was set to 25260398.666667
When I changed it to 10 everything worked.
Thanks,
Dav9000
