### ISSUE TITLE
show 'blank' weeks in roster view

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#434]
I think this is a feature request.

At the moment roster views exclude dates where there is no-one assigned to a roster role in the roster view - even if there is a 'service' that day... or a 'service' with a 'topic' or with 'notes'. 

**The down-side to this behaviour** - it makes it difficult to say "have a look at the rosters and see where there are gaps". Or if we print a roster view out (for people to manually add names to) there will be weeks missing. 

My work-around at the moment is to create a new roster task called "_" and a new 'person' named "0 _" and then assign that person to the "_" task ever week (or date). Then include the "_" roster task in each of the roster views ... as the far right column.

**Comment by tbar0970** [comment]
I'd call this a bug.  If there's a service, it should show in the roster.  Will fix.

**Comment by tbar0970** [comment]
Recently fixed.
