### ISSUE TITLE
Send mailchimp campaigns from within Jethro

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#451]
Currently, Jethro can sync a mailchimp list against a saved report in Jethro using a command line script.  This is useful for maintaining a mailchimp list but doesn't provide a quick way to send a church-wide email from within Jethro.  Users have to open mailchimp, create a new campaign, choose a template, etc etc.  Other church databaseses make it easier to mail in bulk from within the database itself.

Mailchimp email beamer comes close to bridging the gap but it doesn't support attachments.

However keeping mailchimp in the equation is valuable - it is very good at managing spam scores, handling unsubscribes etc.

It would therefore be valuable for Jethro users to be able to compose and send mailchimp campaigns from within Jethro.

Steps to implement:
1. Add a new system setting called MAILCHIMP_API_KEY.
1. Add a new property to the report (person_query) object called: mailchimp_list_id.  This can be editing when configuring a report, IF MAILCHIMP_API_KEY has been set.
1. Add a new button next to each item in the list of person reports: "Send mailchimp campaign". 
 This opens a new page where the user can enter subject, content and file attachments.  The "from" address is the current user's email.  
1. After the user clicks "send", Jethro submits the campaign to Mailchimp. The success/error response from mailchimp is displayed to the Jethro user.  They are also given a link to view the status of the campaign in mailchimp.
1. The existing mailchimp-sync script should be updated so that if no arguments are passed in the command line then it gets them from the database fields above.

**Comment by tbar0970** [comment]
Resource: https://isabelcastillo.com/create-send-mailchimp-campaign-api-3

**Comment by tbar0970** [comment]
Plus we already have a mailchimp API library bundled with Jethro.

**Comment by tbar0970** [comment]
Todo: attachments. Need to create a zip file and use the "archive" property - https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/content/#
https://kb.mailchimp.com/campaigns/ways-to-build/import-a-zip-file-to-create-a-campaign?utm_source=mc-api&utm_medium=docs&utm_campaign=apidocs&_ga=2.198103720.64584041.1520409756-1445216893.1518859511

**Comment by s4069b** [comment]
Thanks for update v2.22.0 
I like the idea of handling/syncing mailchimp lists through Jethro like that. Much better than multiple complex cron jobs. 
Can I check - if I send a campaign using the link in the report list then will the emails send as simple text or a default basic html? (I notice the comment about not using templates).
And am I correct in thinking that attachments remain 'todo' at this stage?
Even if I still login through mailchimp to send campaigns (with attachments) it's still great to handle list syncing through Jethro. Particularly if (like me) you use more than one mailchimp list. 
Thanks again.

**Comment by tbar0970** [comment]
Hi @s4069b 

Campaigns sent through Jethro send as rich text HTML - it just doesn't (yet) support choosing a template to wrap around it.

Attachments are working.
