### ISSUE TITLE
open mailto links in new window/tab for gmail

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#453]
Currently, if gmail is your mailto handler, then when you click a mailto link in Jethro it opens in the same window.  That's fine while you're composing the email, but once the email sends you're left in a dead-end - "where has my jethro gone"?

One way to combat this would be to add target=_blank or similar to all mailto links.  However this would open a new window/tab for users that *don't* use gmail (eg outlook, mac mail etc) and leave this blank window/tab behind.

We would need some more sophisticated solution:  Perhaps open a new window with a Jethro page which prints a mailto link, clicks it with Javascript, then waits to see if the page unloads (which means the browser has naviated to gmail etc).  If after 5 seconds the page is still there, that would mean that some other mailto handler has been launched and it should run window.close() or equivalent.

**Comment by vanoudt** [comment]
Sounds like a great idea! It's really annoying when I send using gmail -
which I tend to do a lot!

The accepted solution on
https://stackoverflow.com/questions/45359575/mailto-link-open-in-new-tab-only-if-web-mail-client?rq=1
has some code to do exactly what you've just described... perhaps that's
where you got your inspiration from? :-P



------------------------------

**Comment by tbar0970** [comment]
No, I re-invented that wheel all by myself!  Thanks for that discovery - my googling somehow missed that.
