### ISSUE TITLE
Add Family Error in v2.22.0

### ISSUE THREAD

**Issue by totalrecaller** [tbar0970/jethro-pmm#457]
I updated Jethro to v2.22.0 from v2.14.4 and ran all the database upgrade scripts. When I tried to add a new family in the new version, I get the below error:

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'status_last_changed' at row 1

Attached is the debug details of the error.

![error](https://user-images.githubusercontent.com/38366959/38762741-a99737a4-3fd2-11e8-9455-02d73d0a7c6a.png)

**Comment by tbar0970** [comment]
Thanks for reporting.  Can you tell me what version of mysql you're using?

**Comment by totalrecaller** [comment]
MySQL Community Server 5.6.38

**Comment by tbar0970** [comment]
Hi @totalrecaller 

It looks like this is a MySQL strict mode issue (https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date).  You can probably fix it quickly by turning on the Jethro setting that disables MySQL strict mode:\.  In your conf.php:
```
define('STRICT_MODE_FIX', TRUE);
```
Let me know if that works.
