### ISSUE TITLE
service notes do not show in 'show the print/email' version of roster views

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#464]
I have a roster view set-up which includes the 'service fields' - 'notes', 'topic', 'sermon text'

When I display/edit the roster assignments I can see all 3 service fields. 
However when I 'show the print/email' version of the roster view the 'notes' field is retained in the form of a column, but each row is blank.  Meanwhile the 'topic' and 'sermon text' columns and content appear fine. 

I'm guessing this is not the intended result?

**Comment by tbar0970** [comment]
This is pretty much intended.... Have a look at your system config page and you'll find a setting called "Show Service Notes Publicly".  If you set it to "yes" then I reckon that column will be filled.

This setting is mostly intended for the /public portal but the print/email view is a kinda "public" presentation of the roster too.  Some people include things in the notes that they don't want going out far and wide.

**Comment by s4069b** [comment]
Great. Thanks for the quick response. 
It all makes sense now - including having the option to mute the notes.
