### ISSUE TITLE
Error when member login only partially configured

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#480]
If you enable member login
but neglect to fill in the from address etc
then when somebody tries to register in the members area they get an error
about swiftmailer invalid address etc.

Two things:
1) The system config page should raise an error if you try to turn on member rego but don't fill in the other required fields
2) If member rego is improperly configured the members interface shouldn't function at all.

**Comment by tbar0970** [comment]
+1

**Comment by jefft** [comment]
After clicking 'Create New Account', the would-be new member sees a stacktrace:

`Fatal error: Uncaught Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. in /srv/www/jethro/tip/app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 345`
...

**Comment by tbar0970** [comment]
Raising an error on the system config page was too much work.  But I've added a "configuration incomplete" message on the members area, which an admin should notice quickly enough.
