### ISSUE TITLE
Column not found 'person_query.mailchimp_list_id' in field list

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#495]
Hi,
I finally got around to upgrading... everything appears to work apart from reports. When I view reports I see an error and get an email which details the error. 
I'm wondering what I have broken? did the sql update fail to run correctly?
any pointers appreciated
thanks

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'person_query.mailchimp_list_id' in 'field list' 
Line 162 of /home/xxx/public_html/jethro/include/jethrodb.php

USER:       1 
REFERER:    https://xxx/jethro/?view=services__list_all
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

REQUEST: 
Array
(
   [view] => persons__reports
   [JethroSession] => xx5
   [_ga] => GA1.3.1308239975.1486198547
   [wp-settings-3] => libraryContent=browse&advImgDetails=show&editor=tinymce&imgsize=large
   [wp-settings-time-3] => 1526857578
   [ucp_tabs] => 0
   [_wpfuuid] => xx

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/jethrodb.php
           [line] => 162
           [function] => execute
           [class] => PDOStatement
           [type] => ->
           [args] => Array
               (
               )

       )

   [1] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/db_object.class.php
           [line] => 998
           [function] => queryAll
           [class] => JethroDB
           [type] => ->
           [args] => Array
               (
                   [0] => SELECT person_query.id, person_query.name, person_query.created, person_query.creator, person_query.owner, person_query.mailchimp_list_id
				FROM person_query
					WHERE (((person_query.owner IN (NULL,'1')) OR (person_query.owner IS NULL)))
					ORDER BY person_query.name
                   [1] => [Object/Array]
                   [2] => [Object/Array]
                   [3] => 1
                   [4] => 1
               )

       )

   [2] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/db_object.class.php
           [line] => 977
           [function] => _getInstancesData
           [class] => db_object
           [type] => ->
           [args] => Array
               (
                   [0] => [Object/Array]
               )

       )

   [3] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/system_controller.class.php
           [line] => 211
           [function] => getInstancesData
           [class] => db_object
           [type] => ->
           [args] => Array
               (
                   [0] => [Object/Array]
                   [1] => OR
                   [2] => name
               )

       )

   [4] => Array
       (
           [file] => /home/xxx/public_html/jethro/views/view_3_persons__3_reports.class.php
           [line] => 119
           [function] => getDBObjectData
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
                   [0] => person_query
                   [1] => [Object/Array]
                   [2] => OR
                   [3] => name
               )

       )

   [5] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/system_controller.class.php
           [line] => 183
           [function] => printView
           [class] => View_Persons__Reports
           [type] => ->
           [args] => Array
               (
               )

       )

   [6] => Array
       (
           [file] => /home/xxx/public_html/jethro/templates/main.template.php
           [line] => 90
           [function] => printBody
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
               )

       )

   [7] => Array
       (
           [file] => /home/xxx/public_html/jethro/include/system_controller.class.php
           [line] => 131
           [args] => Array
               (
                   [0] => /home/xxx/public_html/jethro/templates/main.template.php
               )

           [function] => require
       )

   [8] => Array
       (
           [file] => /home/xxx/public_html/jethro/index.php
           [line] => 58
           [function] => run
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
               )

       )

)

**Comment by vanoudt** [comment]
How odd. Did you apply the 2018-upgrade-to-2.22.sql file? That should have
added the column in.

It can be a bit confusing, but you have to ensure you apply all of the sql
upgrades since your last install...

Automatic database upgrades would, eventually, be a nice addition! 😃

Good luck!

**Comment by s4069b** [comment]
thanks 
yes it looks like something is not working for the sql upgrade on our live installation. 

everything works fine on my backup install at home - with the same data.  I just don't have time at the moment to explore why it's failing on the live install. I don't recall seeing any errors when running the sql in phpmyadmin.

**Comment by vanoudt** [comment]
How odd!

(I know it doesn't quite fix it, but if it's the same data, why not purge
the live database and replace it with a copy of the backup?)

Nick

------------------------------

**Comment by s4069b** [comment]
This is embarrassing. I knew I didn't have time to do the upgrade so I rushed. And in my haste I forgot that on the last upgrade I had changed to a new database (ie instead of backing-up). I applied the sql upgrade to the old database and of course did not see the effect of it in the new database. 
Thought I had better own up to it!!

**Comment by vanoudt** [comment]
😀 an easy thing to do!!
