### ISSUE TITLE
Exporting Contacts to a CSV file

### ISSUE THREAD

**Issue by malyork** [tbar0970/jethro-pmm#497]
Hello,

I would like to export my contacts to a CSV file from Jethro. Can you please tell me how to do this?

Thank you,

Mal York.

**Comment by tbar0970** [comment]
You can export a person report as CSV (Persons > Reports).  Configure a report to show the persons you want to export, with the columns you need, then when you're viewing the results there's an "Export CSV" link at the bottom.
