### ISSUE TITLE
Foreign key error when moving to another family

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#499]
I got this error :-
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`jethroRCOC`.`custom_field_value`, CONSTRAINT `custom_field_valuevalue_optionid` FOREIGN KEY (`value_optionid`) REFERENCES `custom_field_option` (`id`) ON DELETE CASCADE) - Line 628 of /DATA/htdocs/JethroRCOC/db_objects/person.class.php, referer: http://scott/JethroRCOC/?view=_move_person_to_family&personid=751
I have a custom field (Family_status) with values of 'Parent' or 'Child' but 'other' is allowed. With this person 'other' had been chosen with a value of 'friend'. (I was moving them to their 'real' family).
I was able to move them by changing familyid in the database. After this 'hack' I noticed the difference and was able to change family when I selected 'Child'.
I am on version 2.21.2

**Comment by tbar0970** [comment]
So to make sure I understand:
If you have a custom field of type 'select' which has the "allow other" setting ticked
and a person P has an "other" value for that field
then when you try to move P to a different family, you get the DB error above
?

Can you paste the backtrace from the error message?

**Comment by tim-pearce** [comment]
Yes, you have understood correctly.

Where do I find the traceback? All I got was an error on the screen and the above in the httpd error log.
Do I need to try this in a 'development' environment?

Tim

**Comment by tim-pearce** [comment]
Found the setting at the end of the conf file.
(Note: my line numbers may be slightly different to yours).
Fatal Error (Exception)

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`jethroRCOC`.`custom_field_value`, CONSTRAINT `custom_field_valuevalue_optionid` FOREIGN KEY (`value_optionid`) REFERENCES `custom_field_option` (`id`) ON DELETE CASCADE)
Show Details

Line 628 of File /DATA/htdocs/JethroRCOC/db_objects/person.class.php
	Array
(
    [0] => Array
        (
            [file] => /DATA/htdocs/JethroRCOC/db_objects/person.class.php
            [line] => 628
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO custom_field_value
				(personid, fieldid, value_text, value_date, value_optionid)
				VALUES (751,2,NULL,NULL,'friend')
                )

        )

    [1] => Array
        (
            [file] => /DATA/htdocs/JethroRCOC/db_objects/person.class.php
            [line] => 569
            [function] => _saveCustomValues
            [class] => Person
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /DATA/htdocs/JethroRCOC/views/view_0_move_person_to_family.class.php
            [line] => 33
            [function] => save
            [class] => Person
            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /DATA/htdocs/JethroRCOC/include/system_controller.class.php
            [line] => 129
            [function] => processView
            [class] => View__Move_Person_To_Family
            [type] => ->
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /DATA/htdocs/JethroRCOC/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

)

**Comment by tbar0970** [comment]
Thanks for that.  I'll look into it.
