### ISSUE TITLE
Timezone Warning Issue

### ISSUE THREAD

**Issue by malyork** [tbar0970/jethro-pmm#500]
Hi, can you please help me with this timezone warning issue. We have been using Jethro for a few years now and never had this issue. Can you please help me here? Thanks.

The following warning has come up on our home page:

SYSTEM ERROR (WARNING)
strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

Warning: error_log(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/westryde/public_html/jethro/include/system_controller.class.php on line 246

**Comment by tbar0970** [comment]
In your Admin > System Configuration page, check that a valid value has been set in the "Timezone" field:
![image](https://user-images.githubusercontent.com/2133676/41230505-6920b9c4-6dc3-11e8-9e14-4443aabf539d.png)
then click save at the bottom of the screen.
If you've set the timezone and the problem persists please post here again.

**Comment by malyork** [comment]
Hi Tom,

Thanks for this. Please see a screen shot from when I goto Admin>System Configuration:


It will not let me do what you so. Any further advice?

Thanks,

Mla.


Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by tbar0970** [comment]
Hi Mal
Replies to these emails become posts on the github site but attachments don't seem to work. Can you paste the screenshot into the issue?

**Comment by malyork** [comment]
<img width="1260" alt="screen shot 2018-06-11 at 10 10 10 pm" src="https://user-images.githubusercontent.com/40017029/41232557-1b69276e-6dca-11e8-9e17-e8cd764f0da2.png">

Did that work?

**Comment by tbar0970** [comment]
This looks to me like an upgrade was done wrongly, so that the TIMEZONE setting is missing from the database.  Do you have similar errors elsewhere on the System Configuration page?

As a quick fix, someone with access to your server (eg the person who set up Jethro for you) could edit the Jethro conf.php file and add this line:
define('TIMEZONE', 'Australia/Sydney');

**Comment by malyork** [comment]
Yes. I have access to the database and will look for the Jethro cons.php file. I will let you know how it goes.

Thanks,

Mal.


Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by malyork** [comment]
Hi Tom,

Sorry, where is the Jethro conflict.php file?

I am on the server and cannot find it (I did a search and it did not come up).

Thanks,

Mal.


Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by tbar0970** [comment]
If you're in the server's file manager, then in your Jethro folder will be the file called conf.php...

**Comment by malyork** [comment]
Thanks Tom,

Sorry, I am having a shocker. Can you please tell me what line 246 should be in the following file:

(/home/westryde/public_html/jethro/include/system_controller.class.php

Thanks,

Mal.


Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by malyork** [comment]
<img width="351" alt="screen shot 2018-06-12 at 2 08 03 pm" src="https://user-images.githubusercontent.com/40017029/41269706-1836334a-6e4a-11e8-8d5b-ea00e0cd46e1.png">

Hey Tom,

I can't see the cons.php file anywhere. I did a search. Is this the issue, it did not come across in the upgrade. Shall I just do the next upgrade, do you think that would fix the problem?

Mal

**Comment by tbar0970** [comment]
Your Jethro folder will be under public_html.  The file you want is conf.php (short for configuration) not cons.php.

If you've accidentally modified system_controller file I suggest replacing it altogether with this one: https://raw.githubusercontent.com/tbar0970/jethro-pmm/master/include/system_controller.class.php

**Comment by malyork** [comment]
You are such a legend … This is so helpful and I feel that I am almost there.

Thanks.

What line shall I change in the conf.php file to define('TIMEZONE', 'Australia/Sydney’)?

Thanks,

Mal.


Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by tbar0970** [comment]
Safest thing would be to add it as the second last line of the file.

**Comment by malyork** [comment]
When I do that, I go to open Jethro and nothing comes up at all.

Would it be better to change the whole of the conf.php like I did with the other file you sent me?

When I try to log into Jethro now, this comes up:

Warning: main(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/westryde/public_html/jethro/index.php on line 57

Fatal error: Call to private System_Controller::__construct() from invalid context in /home/westryde/public_html/jethro/index.php on line 57



Malcolm York
Senior Minister

p. (02) 9874 1926, m: 0404 489 485
a. 14 Bellevue Ave, West Ryde, NSW, 2122

**Comment by tbar0970** [comment]
We sorted it.
