### ISSUE TITLE
Age Bracket is_adult field empty and something strange

### ISSUE THREAD

**Issue by GatesheadBen** [tbar0970/jethro-pmm#506]
I've had a report that congregation members are reverting back to the default non-adult age bracket.  I've not been able to reproduce this but **I've noticed that that original age bracket has is_adult=0 whereas all the others have that field empty.  The field is varchar(255) which doesn't seem right?**

Should all non-adult age brackets have is_adult as 0 or blank?

Thanks,
Ben

**Comment by tbar0970** [comment]
You're right that varchar(255) isn't quite right.  Looks like it was a mistake in the upgrade script. I've got a fix coming for that.  But I'm not sure if it would actually break anything

Could your original symptom be caused by Issue #466 ?

**Comment by GatesheadBen** [comment]
I don't think so.  The report was that the team had been going through moving congregation members from children to youth and youth to adults but felt that they kept coming across records they had already updated.  I've not had any other reports of the problem.
