### ISSUE TITLE
Database error installing v2.24.1

### ISSUE THREAD

**Issue by andrewfn** [tbar0970/jethro-pmm#535]
- OS: Ubuntu 16.04
- MySQL: 5.7.23
- PHP: 5.6.37

After filling out the first page of the installer, I get the error:

### Jethro PMM Installer
**Fatal error:** Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'details' can't have a default value' in /home/nlcrm/include/installer.class.php:110 Stack trace: #0 /home/nlcrm/include/installer.class.php(110): PDO->query('\n\t\t\tCREATE TABL...') #1 /home/nlcrm/include/installer.class.php(33): Installer->initDB() #2 /home/nlcrm/templates/installer.template.php(15): Installer->printBody() #3 /home/nlcrm/include/installer.class.php(19): include('/home/nlcrm/tem...') #4 /home/nlcrm/index.php(51): Installer->run() #5 {main} **thrown in /home/nlcrm/include/installer.class.php on line 110**

I have repleted this several times with the same result.
Any help would be very much appreciated

**Comment by andrewfn** [comment]
A few hours of research and I determined it might be my version of MySQL
STRICT mode was introduced as default in 5.7
I found this issue which solved the problem: https://github.com/tbar0970/jethro-pmm/pull/260

**Comment by tbar0970** [comment]
Thanks for raising this, it will be good to keep working towards strict-mode compatibility
