### ISSUE TITLE
Members interface - email address sometimes hidden

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#539]
In the members interface, "people" page, each person is shown in a box.
If their email address is long, it shifts down a line instead of being next to the mobile number
and it gets cut off by the box, so is invisible.

**Comment by GatesheadBen** [comment]
I can't reproduce this issue on Chrome or Edge.

**Comment by alwr** [comment]
I noticed this tonight.  It happens with much shorter email addresses when there is a person photo showing.  Varying the width of the browser window can make email address appear as the text rewraps.

It appears to be that only 3 lines fit - the div has a height of 72px, and the line-height is 20px.
Changing line-height to 15px makes 4 lines appear comfortably, but it still wraps badly if the width is not sufficient to show the whole email address.

Any ideas on a neat solution?

**Comment by tbar0970** [comment]
The problem is that when the viewport size hits 600px wide, the box becomes 49% of screen width.  49% of 600px is often not enough to fit mobile plus email, so it drops to the next line and gets cropped off.
Tried various things. Making the box height auto leads to other problems because of unpredictable image sizes.  So I've made text-overflow visible for this box, and moved the breakpoint to 700px so it's less likely to overflow anyway.

**Comment by alwr** [comment]
Thanks Tom.  I've implemented the change, but the email address often ends up over the next person in the family.
On a decent computer screen (>980px wide) making the family list wider helps, and it still seems to scale OK when narrow.

```
#member-list {
    max-width: 140ex;
```
