### ISSUE TITLE
Install error using localhost XAMPP

### ISSUE THREAD

**Issue by econg** [tbar0970/jethro-pmm#542]
Installed Jethro using Yohan Perera guide for windows setup. Get all the way through to "Set up the database". I then get this error.
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'editor' in C:\xampp\htdocs\Jethro\include\installer.class.php:110 Stack trace: #0 C:\xampp\htdocs\Jethro\include\installer.class.php(110): PDO->query('\n\t\t\tCREATE TABL...') #1 C:\xampp\htdocs\Jethro\include\installer.class.php(33): Installer->initDB() #2 C:\xampp\htdocs\Jethro\templates\installer.template.php(15): Installer->printBody() #3 C:\xampp\htdocs\Jethro\include\installer.class.php(19): include('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\Jethro\index.php(51): Installer->run() #5 {main} thrown in C:\xampp\htdocs\Jethro\include\installer.class.php on line 110
Should I have set up a table in the XMAPP install?

**Comment by tbar0970** [comment]
I think this is a mysql strict mode issue. can you edit your conf.php file, find the line about STRICT_MODE_FIX and un-comment it:

```define('STRICT_MODE_FIX', TRUE);```

Let me know if that helps.

**Comment by econg** [comment]
Sorry, did that also. Still failed. Don't understand why it says "Invalid default value". by definition, default means some already programmed value is wrong.

**Comment by econg** [comment]
Just for something to try, I downloaded and installed Churchinfo. I followed their simple instructions using XAMPP and PHP, and it worked first go!!! It appears to be in the setting of Tables in Jethro.

**Comment by tbar0970** [comment]
I've tracked this down to a bug in Jethro. The fix above will be released soon. Thanks for reporting.

**Comment by econg** [comment]
Eagerly awaiting

**Comment by tbar0970** [comment]
Released in https://github.com/tbar0970/jethro-pmm/releases/tag/v2.25.0
