### ISSUE TITLE
Bulk updates don't take on the first attempt

### ISSUE THREAD

**Issue by GatesheadBen** [tbar0970/jethro-pmm#545]
I need to investigate this more but on both my staging and live environments bulk updates frequently do not work the first time e.g.

1) Choose a group
2) Select all
3) "With selected persons" "set field"
4) Choose a change to make
5) Click Go
6) Confirmation "are you sure you want to bulk update these persons"
7) Green message appears to confirm the change has been made
BUT THE CHANGE HAS NOT BEEN MADE

Repeating the process always works.
Both environments are currently running 2.23.1

I will investigate and upgrade both environments and post some more details soon.

**Comment by tbar0970** [comment]
This was fixed in issue #460
