### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by econg** [tbar0970/jethro-pmm#547]
Me again!!! Should I be using PDO instead of MDB2??? If so, how do I install PDO (I'm a complete ludite). Has Jethro a nice simple install guide for installing using XAMPP as a localhost????

**Comment by econg** [comment]
Done all that. Load "localhost/jethro/". Jethro loads. Fill out first page with all required info, press "Set up data base". Thinks, then fails with previously mentioned error.

**Comment by tbar0970** [comment]
Fixed in issue #542
