### ISSUE TITLE
Absence figures look wrong

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#549]
I have a report that selects those with an attendance of less than 1% over the past 6 weeks.

How come I get people who have attended during those 6 weeks - and it shows attendance as 0% for them.

I just want to know who hasn't attended for the last few weeks.

**Comment by tbar0970** [comment]
This report should not show anyone who has attended in the last 6 weeks.

What kind of attendance are you reporting on?  Group and  congregation attendance are distinct, so if you run a report showing "people whose attendance at [youth group] is less than 1%" the people who are listed may still have attended their congregation on a sunday.

**Comment by tim-pearce** [comment]
At present I don't record congregation attendance. Everyone in the list has an attendance of 0%.

**Comment by tbar0970** [comment]
This is a strange one. Can you post some screenshots of your report config and some attendance data for people shown in the results?

**Comment by tim-pearce** [comment]
I've added some code to my copy of view_3_persons__3_reports.class.php, so I can test the SQL but when I run the SQL in phpMyAdmin, I get an empty result!?

**Comment by tim-pearce** [comment]
I've taken a part of the query and modified it
SELECT personid, SUM(present), COUNT(*) FROM attendance_record ar2 WHERE ar2.date >= '2018-08-28' AND groupid = 2 GROUP BY personid
I now see why it is odd.
We haven't had playgroup for all of the (in this case) past 8 weeks.
The query uses an 'absolute' date of 8 weeks ago!

**Comment by tbar0970** [comment]
The interface says "...whose attendance has been .... over the last [x] weeks".
The code uses that number to construct a date X weeks in the past
(person_query.class.php lines and 1065 and 1220)
and uses that in the query.
So I don't see a problem here...

Are you expecting it to look at "the last 8 weeks that playgroup was on" ? That's not how it works.

**Comment by tbar0970** [comment]
?
