### ISSUE TITLE
Reports not filtering on membership status

### ISSUE THREAD

**Issue by GatesheadBen** [tbar0970/jethro-pmm#555]
![image](https://user-images.githubusercontent.com/12513058/47624011-4d240a00-db0f-11e8-88dc-6091b72440b7.png)

We have a report which wants to show leaders from 5 groups.  3 of these groups are categories, 2 are groups.  The report incorrectly shows members of the groups.  I think this is because the WHERE clause is like:
(group = 1) or (category = 2) and (membership = 3) and MYSQL is evaluating that to be
(group = 1) or (category = 2 and membership = 3).

The query I've captured is from the general log is below and this works as expected if I add extra brackets to the two where clauses to make them
((group = 1) or (category = 2)) and (membership = 3))

I'm not yet sure
1) if I can consistently reproduce this behaviour (with other reports etc.) and
2) where I'd put a fix like that into the code!

SELECT 
	CONCAT(pg.name, ' (#', pg.id, ')'),
	p.id AS ID,
	`p`.`first_name` AS 'p.first_name',
	`p`.`last_name` AS 'p.last_name',
	`p`.`email` AS 'p.email'
				
FROM person p
	JOIN family f ON p.familyid = f.id
	JOIN person_group_membership pgm ON p.id = pgm.personid
	JOIN person_group pg ON pg.id = pgm.groupid
	JOIN age_bracket absort ON absort.id = p.age_bracketid 
				
WHERE
	(p.status = '0')
	AND 
	(p.id IN 
	
	(SELECT personid
		FROM person_group_membership pgm
		JOIN person_group pg ON pgm.groupid = pg.id
		**WHERE 
			((pgm.groupid IN (147,79))
			OR (pg.categoryid IN (50,49,53))
			AND pgm.membership_status IN ('3'))))
	
	AND 
		((pgm.groupid IN (147,79)) OR (pg.categoryid IN (50,49,53)) 
		AND pgm.membership_status IN ('3'))**
				
GROUP BY p.id, pg.id
ORDER BY pg.name, `p`.`last_name`, p.last_name, p.familyid, absort.rank, IF (absort.is_adult, p.gender, 1) DESC, p.first_name
;

**Comment by tbar0970** [comment]
Thanks for the report and the diagnosis. I'll figure out where we can fix the bracketing when constructing the query.

**Comment by GatesheadBen** [comment]
Excellent, thanks.  For now (as a work around) , I've added and extra pair of brackets to person_query.class.php as per https://github.com/GatesheadBen/jethro-pmm/commit/ea2c611d24f25c42f90f6297e44fba7e0147d19a

**Comment by tbar0970** [comment]
That commit was part of the note-ordering pull request, to which it didn't relate!
But the extra brackets were the right solution so I've committed them directly (above).
