### ISSUE TITLE
Problems with version 2.10.4

### ISSUE THREAD

**Issue by russarundel** [tbar0970/jethro-pmm#56]
Since installing 2.10.4, I have had the following problems:

Attempting to display attendance without selecting congregation gives
Fatal error: Call to a member function printFieldValue() on a non-object in /home/nightshi/public_html/care/views/view_6_attendance__2_display.class.php on line 168

Attempting to add a note to and existing note results in a 403 html error.

Attempting to add a new note to an existing person results in an error reporting email
Undefined index: save_option 
Line 474 of /home/nightshi/public_html/care/db_objects/person_query.class.php

**Comment by tbar0970** [comment]
OK, three problems here.
Number 1 is clear enough.
Can you explain exactly what steps you followed to produce number 2 and number 3.
THanks.

**Comment by russarundel** [comment]
Problem 2: Tried to reproduce and didn't get the error this time! Sorry.

**Comment by russarundel** [comment]
Ok, have found that long text in the comment field produces the problem. Example text:

I rang her this morning and she is naturally upset with xxxxxx's circumstances.  They have discovered the reason for the virus (which she identified but I cannot remember) and the normal treatment is penicillin.  However xxxxxx is allergic to penicillin and they are trying to find an alternative antibiotic.  xxxxxx seems to be stabilised but the danger continues that the virus could move to her brain.  xxxxxx continues to be in pain and they have trouble finding veins.

The strategy is to insert a catheter into her chest and drip-feed the antibiotics for four weeks.  Then this will be followed by a six week oral course.  

xxxxxx appreciated the call and the prayer at the end.

**Comment by tbar0970** [comment]
I've tried adding a comment to a note, using the text above, and don't get any errors.  Can you please test again.
