### ISSUE TITLE
Roster Reminder Script... at Christmas and Easter....

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#571]
Our weekly Music Roster went out yesterday using the fantastic roster reminder script. 
However, one of the musicians let me know they received the roster reminder when they are not playing this Sunday. 

I believe what has happened is that the script sent a reminder to everyone on a music roster item in the next week... with Christmas being under a week away, the Christmas Day musicians were also included in the email. But the script only includes one day's roster. 

Perhaps a 'solution' to this would be for the script to include more than one day's roster?  In which case Christmas day (and Good Friday) roster reminders will go out nice and early ... attached to a Sunday reminder?

That proposed solution may not be so easy to pull-off? I don't have time to play with this at the moment.

**Comment by tbar0970** [comment]
I've looked into this and I think your diagnosis is correct IF  the LIST_NOT_TABLE option is enabled. Do you have that option turned on?

If so, line 216 of the roster_reminder.php script is the culprit - looks like it only pays attention to the first row of the roster.  Table-format wouldn't have that problem.  Need more time to set up a proper test case.
