### ISSUE TITLE
issue with notes - error when trying to edit/comment?

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#576]
Not sure what I've broken, could it have happened during a recent upgrade? However I did it... when I try to edit/comment a note attached to a person Jethro throws an error and I receive this email. 

Call to a member function getValue() on null 
Line 31 of /...l/jethro/views/view_0_edit_note.class.php

USER:       1 
REFERER:    .../jethro/?view=persons&personid=674
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

REQUEST: 
Array
(
   [view] => _edit_note
   [note_type] => person
   [noteid] => 0
   [JethroSession] => vt02cc5buvu2fson3vjgs49qp6
   [wordpress_logged_in_a53ed30bd318baa55077955ba23c7675] => ...
   [wp-settings-3] => libraryContent=browse&advImgDetails=show&editor=tinymce&imgsize=large
   [wp-settings-time-3] => 1542408445
   [_ga] => GA1.3.1308239975.1486198547
   [_wpfuuid] => a60d0ed9-a1df-4f63-87ec-fc46fe39f7e0
)

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /../jethro/include/system_controller.class.php
           [line] => 130
           [function] => processView
           [class] => View__Edit_Note
           [type] => ->
           [args] => Array
               (
               )

       )

   [1] => Array

**Comment by tbar0970** [comment]
Hi there
It looks like the note id in the request is 0 which shouldn't happen.
Can you post the steps you  followed (exactly what you clicked) to perform the note editing.

**Comment by s4069b** [comment]
Thanks for asking me to do that... it made me notice a couple of things. 

I get the error when I attempt to access the note from the 'person' screen... for example from this page../jethro/?view=persons&personid=674

But I only get the error when I access a note that 'requires action'. 


Interestingly I do NOT get the error if I attempt to access the note from the list of notes for immediate action .. ie this page https://kpc.org.au/jethro/?view=notes__for_immediate_action

**Comment by s4069b** [comment]
correction... the error occurs for notes that do not require action... but not for 'family' notes.

**Comment by tbar0970** [comment]
OK, still can't replicate it myself.
For a note that experiences this problem, can you post the URL that the "edit/comment" link links to?
I assume you're not using the 'edit original note" link ?

**Comment by s4069b** [comment]
thanks for trying. Maybe it's one of those ones where I'll think of some things to try if I leave it alone for a bit?

The results of that little exercise are odd. 

If I open person x who has three notes and then go to their 'notes' .. I land on this url https://xx.org.au/jethro/?view=persons&personid=631. 

On that page I see the three comments and I can click on edit/comment for any of the three.

the first note throws the error with  url - https://xx.org.au/jethro/?view=_edit_note&note_type=person&noteid=0
the second note throws the error with  url - https://xx.org.au/jethro/?view=_edit_note&note_type=person&noteid=1
the third note opens a note UNDER ANOTHER USER'S NAME with the url - https://xx.org.au/jethro/?view=_edit_note&note_type=person&noteid=2

Does that make any sense / trigger any ideas?

**Comment by s4069b** [comment]
Yes it appears the sequential URLs is the issue. If I look at a different person's record the notes still link to the same URL's.  (ie note 0 for the first, 1 for these second, 2 for the third....)
It is just a coincidence that note number 2 exists. If there were a note 0 or a note 1 then I presume I would see those notes (but I'm guessing they've been deleted). 

I am using v2.26 (and so wonder if I did something wrong with the update?)
would it hurt to re-run the sql query?

I am using PHP Version 7.0.33

**Comment by s4069b** [comment]
OK I re-copied the v2.26 files and tried re-running the update sql code (which did not change anything that I'm aware of) and the error continues. 

However I did notice i accidentally clipped some of the original error email... not that it appears to add much value. 

Call to a member function getValue() on null 
Line 31 of ../public_html/jethro/views/view_0_edit_note.class.php

USER:       1 
REFERER:    ..jethro/?view=persons&personid=90
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

REQUEST: 
Array
(
   [view] => _edit_note
   [note_type] => person
   [noteid] => 0
   [JethroSession] => shiae83666v60f6i7dgv5d1584
...
)


BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /...public_html/jethro/include/system_controller.class.php
           [line] => 130
           [function] => processView
           [class] => View__Edit_Note
           [type] => ->
           [args] => Array
               (
               )

       )

   [1] => Array
       (
           [file] => /.../public_html/jethro/index.php
           [line] => 58
           [function] => run
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
               )

       )

)

**Comment by s4069b** [comment]
I'm out of my depth with the code. But for whatever reason when I view url: jethro/$view=persons&personid=90#notes (or any other person id)
the "list_notes.template.php"  code manages to misplace the correct $id variable when handling  this line of code:
"<a class="pull-right link-collapse" href="?view=_edit_note&note_type=<?php echo $type; ?>&noteid=<?php echo $id; ?>"><i class="icon-wrench"></i><?php echo _('Edit / Comment')?></a>"

Instead of $id being the note number, it ends up as a sequential number (0 1 2) depending on how many notes (either family or personal) are attached to the person. If there's just one note, then $id=0.

That's about as close as I can get to working this out.

**Comment by tbar0970** [comment]
I figured it out.  The bug only occurs when you have the "notes list order" set to "descending" - which in my test system I oridingally didn't.  Fix will come out in the next release. In the meantime you can apply the one-line fix above if you like!

**Comment by s4069b** [comment]
Thank you! For the time being I changed the 'notes list order' setting... and yes, it's working.
