### ISSUE TITLE
Search for a person with a ' in their name throws an error

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#584]
from the 'home' screen, enter all or part of a person's name in the search box. A name which includes a ' and Jethro throws an error:

Forbidden Error Page
If you arrived here due to a search or clicking on a link click your Browser's back button to return to the previous page. Thank you.
IP Address:

**Comment by tbar0970** [comment]
I can't replicate this.  Can you tell me what browser you're using, and post some exact URLs (with domain name redacted) to give some more insights.

**Comment by s4069b** [comment]
sorry for the slow reply. I can replicate the error on any browser, and on Mac or Windows. 

I did wonder at first if it was a Mac related thing (I usually use Mac and would have entered the names with ' in them using Mac). But the search failing would not be connected with the names saved in the database.

The error page has this url  .../jethro/?view=_mixed_search&search=d%27

The server is running php 7.0.33

Not sure what else might relevant or helpful?

**Comment by tbar0970** [comment]
OK, it must be something to do with your server config.

That "forbidden error page" you're getting isn't part of Jethro itself, and when I search for " d' " in my system I get to the equivalent URL with no error.

Can you have a look at your HTTP and PHP error logs and HTTP access log to see if there are any clues?

**Comment by tbar0970** [comment]
Closing this for now, please re-open if you need further input
