### ISSUE TITLE
Custom field names do not wrap in person view

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#590]
We have a couple of custom fields which have unavoidably LONG NAMES. 

In the 'person view'  the long names make the 'name' column in the 'person details' box so wide it pushes the content column  to the right so that even basic details like the person's name are clipped off. Widening the browser window does not widen the 'person details' box. 

If the custom field names would 'wrap' then this effect would not be experienced.

Our dodgy work-around is to view in 'edit' mode to be able to see the person's full details.

**Comment by tbar0970** [comment]
+1

**Comment by tbar0970** [comment]
Thanks for reporting. This is indeed a problem, which is already recorded in Issue #347 .  I will bump up the priority of fixing that one.
