### ISSUE TITLE
Jethro loses data when marking attendees with over 1000 people

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#6]
When the Record Attendance form has over 1000 people, Jethro will fail to record the attendance selections of the last ones. In the Apache error log we see:
```
PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer: https://jethro.coastec.net.au/?view=attendance__record&age_bracket=&for_type=congregationid&congregationid%5B%5D=1&congregationid%5B%5D=2&congregationid%5B%5D=&attendance_date_d=08&attendance_date_m=2&attendance_date_y=2015&params_submitted=1
```

PHP is silently restricting the submitted HTTP POST data to 1000 users (even if most are 'unknown').

**Comment by jefft** [comment]
I'm not very experienced at githubbing - perhaps I should have raised the bug first, then the [pull request](https://github.com/tbar0970/jethro-pmm/pull/5)

**Comment by tbar0970** [comment]
Thanks for diagnosing this problem Jeff.  
PHP has that limit to protect against denial-of-service attacks, so I'd like to avoid raising it unecessarily.  Also, as you've realised, the question is "how much is enough?"!

So the alternative fix I've put in is for Jethro to check, when printing the attendance form, whether it's printing more fields than the server can process, and to show an error if there are too many people to handle.  See https://github.com/tbar0970/jethro-pmm/commit/50efe9e28b4ae5d1769985271a299b9d31d4b68f
