### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by mpedant** [tbar0970/jethro-pmm#600]
Hi

I've just run a couple of updates on Jethro systems; one worked, the other seemed not quite to work.

1. Updating an install from 2.19 to 2.27 worked fine.  I ran the SQL update routines in turn, and the system seems to be working correctly.

2. Updating another install from 2.14 to 2.27 seems not to have worked.  I ran the SQL update routines in turn in exactly the same way (just using more of the routines).  I was able to log in fine, but none of the Persons or Families appear in the front-end.  Persons / List All returns "No persons in this range", and including archived persons is the same.  When I look at the database however, all of the Person and Family records appear to be there.

Under Groups / List all, the lists are there, with a number of members showing, but when I click through to a Group it has zero members

*edit* could this be connected with me working on a copy of the database, and the copy database has a different name?

Please help!

**Comment by tbar0970** [comment]
Hmm. This will be something to do with the "person" view in the DB.
Did you by any chance move to new hosting at the same time as doing the upgrade?

Try running this SQL on the database:
```
DROP VIEW person;
CREATE VIEW person AS
SELECT * from _person p
WHERE
getCurrentUserID() IS NOT NULL
AND (
(`p`.`id` = `getCurrentUserID`())
OR (`getCurrentUserID`() = -(1))
OR (
	(
	(not(exists(select 1 AS `Not_used` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`()))))
	OR `p`.`congregationid` in (select `cr`.`congregationid` AS `congregationid` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`()))
	)
	AND
	(
	(not(exists(select 1 AS `Not_used` from `account_group_restriction` `gr` where (`gr`.`personid` = `getCurrentUserID`()))))
	OR `p`.`id` in (select `m`.`personid` AS `personid` from (`person_group_membership` `m` join `account_group_restriction` `gr` on((`m`.`groupid` = `gr`.`groupid`))) where (`gr`.`personid` = `getCurrentUserID`()))
	)
)
);
```

**Comment by mpedant** [comment]
Yes, I'm moving the install to new hosting.  Had the same issue both on new hosting and on new install at existing hosting.
Your explanation makes sense and the SQL looked very convincing, but has not done the trick (see attached for the SQL results).  The "Families" tab also (still) returns nothing (which I didn't mention in the initial Github request, sorry!)
    On Monday, 8 April 2019, 12:35:33 BST, Tom Barrett <notifications@github.com> wrote:  
 
 
Hmm. This will be something to do with the "person" view in the DB.
Did you by any chance move to new hosting at the same time as doing the upgrade?

Try running this SQL on the database:
DROP VIEW person;
CREATE VIEW person AS
SELECT * from _person p
WHERE
getCurrentUserID() IS NOT NULL
AND (
(`p`.`id` = `getCurrentUserID`())
OR (`getCurrentUserID`() = -(1))
OR (
	(
	(not(exists(select 1 AS `Not_used` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`()))))
	OR `p`.`congregationid` in (select `cr`.`congregationid` AS `congregationid` from `account_congregation_restriction` `cr` where (`cr`.`personid` = `getCurrentUserID`()))
	)
	AND
	(
	(not(exists(select 1 AS `Not_used` from `account_group_restriction` `gr` where (`gr`.`personid` = `getCurrentUserID`()))))
	OR `p`.`id` in (select `m`.`personid` AS `personid` from (`person_group_membership` `m` join `account_group_restriction` `gr` on((`m`.`groupid` = `gr`.`groupid`))) where (`gr`.`personid` = `getCurrentUserID`()))
	)
)
);

**Comment by mpedant** [comment]
Figured it out.  Because I was upgrading across so many versions, I didn't see the all-important notes against a much earlier upgrade about the import of settings from conf.php to the database.  I spotted those once I figured it would be worth a try updating to 2.19 first (since the install I took from 2.19 to 2.27 worked fine).

Thanks for getting back to me with the SQL though, much appreciated.

**Comment by tbar0970** [comment]
Glad you solved it - thanks for sharing what the cause/solution ended up being.
