### ISSUE TITLE
Your site has been limited within the past 24 hours message

### ISSUE THREAD

**Issue by willymec** [tbar0970/jethro-pmm#603]
I'm getting a message - Your site has been limited within the past 24 hours message. The site runs great except not showing all the members pictures on attendance if over 20 people on the attendance I have one group that has 68 people. Only shows some randomly, never all of them. The ones that don't show have a x or blank depending on what device or web browser. I'm told it's using up all the shared hosting resources.  The process limit count on a shared plan is 35. And it will fault out and cause pics to not show. I really need the attendance to show all the peoples pictures in each group.
Thank you

**Comment by tbar0970** [comment]
Hi there

This will be an issue with your hosting, not Jethro.  That sort of message is not generated by Jethro itself.  When you include pictures on the attendance page, the browser has to fetch all those image files from the server.  Your server seems not to like being asked to do so much work at once.  Only your hosting provider can solve this.

**Comment by willymec** [comment]
So do i need to have it hosted on a non shared hosting service? Can you recommend a hosting service?
Thank you

**Comment by GatesheadBen** [comment]
Hi Willymec,
It’s not the shared hosting specifically but some thing(s) about the particular host that are the issue.

If you are in the uk I’d recommend 34sp.com as they are currently hosting a few instances of JethroPMM for me but I’ve also got customers with different sorts of sites on OVO, Bluehost and Fasthosts.

The Easy Jethro service in Australia is brilliant and I couldn’t match their prices for a similar service - if you wanted me to host, manage, maintain and backup an instance of Jethro for you (including domain name and https/ssl) it would cost me around £20 per month.

If you want some UK based Jethro advice give me a shout.

Ben

**Comment by willymec** [comment]
So do I need a VPS or dedicated server to run Jethro with over 50 members with pics in attendance taking.
Are we saying the shared hosting cant do it?

**Comment by tbar0970** [comment]
Jethro can run fine on shared hosting.  (Although VPS/dedicated has better security).
It's just that this particular host has bandwidth/traffic restrictions that are problematic.

**Comment by willymec** [comment]
Ok i switched to new server and it fixed the problem.  The only other thing i have is iphone related, when i revisit the attendance record page more than 3 times the images stop showing unless i clear history on my iphone, or view the details of the person then go back to attendance record and they all show again.  This does not happen on any other device.

**Comment by tbar0970** [comment]
Glad you solved the hosting issue.
The iphone issue is interesting. Can I get you to write that up in a new issue please, with as much detail as possible.
