### ISSUE TITLE
jethro-2.27.0.zip and TrojanDownloader:VBS/Schopets.N

### ISSUE THREAD

**Issue by ozcj** [tbar0970/jethro-pmm#604]
I downloaded jethro-2.27.0.zip but windows detected TrojanDownloader:VBS/Schopets.N and deleted the file. Is the release file infected or is it some kind of false positive?

Maybe this file: jethro-2.27.0.zip->resources/ckeditor/plugins/specialchar/dialogs/lang/pt.js

**Comment by tbar0970** [comment]
I've tried to replicate this.  Downloading the Jethro Zip in MS edge on Windows 10, windows scanned the file and found no threats. I've inspected pt.js and there is nothing suspicious in there.
So I think this must have been a strange false positive on your scanner. Can you please try again.

**Comment by tbar0970** [comment]
Initially I could not replicate this. But i've just got a notificatiow now. Let me investigate further.

**Comment by tbar0970** [comment]
There's something strange with MS virus scan going on.
Download #1 in chrome - got a warning.
Download #2 in chrome - no warning
Download in MS Edge - no warning
I've inspected the file and there's no virus there - it just an array of portugese labels.
I'm going to delete that file (from an unused ckeditor  plugin) to try to avoid any further trouble.

**Comment by ozcj** [comment]
Thanks. How do I download the package minus that file?
