### ISSUE TITLE
iphone not showing photos

### ISSUE THREAD

**Issue by willymec** [tbar0970/jethro-pmm#605]
When i revisit the attendance record page more than 3 times the images stop showing unless i clear history on my iphone, or view the details of a person then go back to attendance record and they all show again. But, then if I go back to record attendance again there gone again. This does not happen on any other device only on iPhone 7 and x so far I've tried. iPads work fine.
Scenario is I go to record attendance for a group called Experienced Adults. I choose show photos and mark people present and absent and then save all attendances. I then have late people come in and I go back to record attendance page, and mark that person present.
![IMG_3070](https://user-images.githubusercontent.com/42074925/58899084-ec663c80-86b0-11e9-930f-36a20e9df33e.PNG)
 All is good unless I go a third time and record another late person, then the photos are blank white boxes.
![Image-1](https://user-images.githubusercontent.com/42074925/58899187-23d4e900-86b1-11e9-819a-8182ae72a756.jpg)
Note I always have photos checked.
We have been using ipads and didn't notice this until we started using our iphones.

**Comment by tbar0970** [comment]
Thanks for the report.  I assume this in mobile safari?  Do you have Jethro saved to your home screen ("standalone safari") or do you just open safari app first and go to Jethro?

**Comment by willymec** [comment]
Yes mobile safari. Saved to my home screen yes

**Comment by willymec** [comment]
Added this to the public_html .htaccess

` # DISABLE CACHING
 <IfModule mod_headers.c> 
 Header set Cache-Control "no-cache, no-store, must-revalidate"
 Header set Pragma "no-cache" 
 Header set Expires 0 
 </IfModule> `

**Comment by willymec** [comment]
If I open safari app first and go to Jethro then all photos show, only when I use the home screen Jethro does it not show the photos.

**Comment by tbar0970** [comment]
I really think the cause of this has to lie somewhere outside of Jethro itself, either in the hosting or something to do with the mobile browser.  If you have any further info to narrow it down, please reopen the issue.
