### ISSUE TITLE
Dodgy autoload calls when zend_guard_loader installed

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#61]
Because _getFields is a non-static function but sometimes gets called statically we hit the problem discussed at http://stackoverflow.com/questions/3517789/scrambled-class-name-passed-to-spl-autoload-call-via-call-user-func

Solution: Make it a static function and always call it statically.

**Comment by RoystonS** [comment]
We're in the middle of trying to upgrade to 2.10.x and are hitting this exact problem with Jethro. :-(  

Would be happy to help test out patches.

**Comment by tbar0970** [comment]
I'll let you know when I have some patches.  In the meantime, your best bet is to turn off zend_guard_loader.  If you're using cpanel hosting this is (sometimes?) possible via the "choose php version" page.

**Comment by tbar0970** [comment]
Resolved in revision 6eacc20, to be released in v2.14
