### ISSUE TITLE
unserialize errors

### ISSUE THREAD

**Issue by GatesheadBen** [tbar0970/jethro-pmm#617]
Hi All,
I don't know what has happened (my host recently migrated us to a new server but there are are a few admins who could've also done something silly) but we have broken Jethro. 
We are seeing unserialize errors all over the interface.  (for example this one on the home screen)
![image](https://user-images.githubusercontent.com/12513058/67642428-a893fe00-f903-11e9-9ad3-86fd6ed4c5ea.png)

I don't think anyone has been in MySQL and created a corrupt entry so I wondered if you had any troubleshooting advice for me:
* Do you think it is an issue with Jethro and a recent version of PHP?
* Do you think it is a problem with Collation/CharSet?
* Do you think it can only be a corrupt entry in the database somewhere?

I've restored the site to a different server so we can continue working but it would be useful to do the Root Cause Analysis for interest and to stop it from happening again.

Any advice on where to look next gratefully received!

Thanks,
Ben

**Comment by tbar0970** [comment]
Hi Ben. A collation/charset issue would be a likely culprit.  Can you either turn on the option to show error details in conf.php, or inspect your error log file, and post here the backtrace of the error so we can see exactly where it's coming from?

**Comment by tbar0970** [comment]
Thinking further about this (not sure if you solved it already).

"Offset 0 of 1 bytes" suggests to me that something that should be an empty string (or null) has somehow had 1 byte inserted during your db migration. 1 1-byte string would never be a valid serialised value

**Comment by GatesheadBen** [comment]
Hi Tom,
No I didn’t solve it yet. I moved the site onto a server with an earlier version of PHP and moved on.  There is a good amount of data in that instance so it is probably a combination of the data, Jethro and the PHP version.  I need to set aside a couple of evenings to see if I can reproduce it on a second server.

Feel free to close it for now and I’ll re-open if and when i do that investigation and find it reproduceable.

Thanks

Ben
