### ISSUE TITLE
Upgrade problem with 2.10

### ISSUE THREAD

**Issue by robcinoz** [tbar0970/jethro-pmm#62]
I followed the upgrade process to upgrade from 2.7 to 2.10 everthing went fine including the sql upgrade scripts. or so I thought. after running the scripts I was able log into Jethro but when I logged out I got the following error.
Fatal error: Could not generate random string in /home/bomaderr/public_html/jethro/include/general.php on line 658

Now we cannot acccess it at all.

**Comment by robcinoz** [comment]
This is severe.....Please help!

**Comment by tbar0970** [comment]
Hi there

This is because your server doesn't provide a good random number generator.  See the 2.9.5 release notes for a workaround:  https://github.com/tbar0970/jethro-pmm/releases/tag/v2.9.5
