### ISSUE TITLE
Add username to response headers to permit tracking and auditing

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#621]
It would be nice if an administrator could see which users are logging in to Jethro (cf #304), specifically so that unused accounts can be deactivated. If Jethro added a `X-Jethro-User:` header to HTTP responses, then in Apache's `LogFormat` directive I could specify `%{X-JETHRO-USER}o` and see who is making the requests.

**Comment by GatesheadBen** [comment]
+1
To temporarily fulfill this audit requirement I've been adding a line to the login process to add a row to a new table.

**Comment by tbar0970** [comment]
If the objective is to see what accounts are unused then Ben's approach is better than just writing to the apache logs

**Comment by jefft** [comment]
This feature request was implemented in Jethro 2.33.0 in https://github.com/tbar0970/jethro-pmm/pull/851. I use it with the Apache logging directive:
`LogFormat "%v:%p %a %{X-Jethro-Session}o %{X-Jethro-User}o %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D uid=%{X-Jethro-UID}o" vhost_combined_timed`
