### ISSUE TITLE
Jethro ical calendar feeds are invalid (no DTSTAMP)

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#623]
On the Jethro home page, in the "Upcoming Roster" section, there is a "Subscribe" link which generates a personal iCal roster.

The generated iCal is not valid, according to the icalendar.org [validator](https://icalendar.org/validator.html). Specifically, entries are lacking DTSTAMPs:

![image](https://user-images.githubusercontent.com/205995/70283115-3244be80-1814-11ea-9be0-60a3a5a8384a.png)

The calendar still imports fine in Google Calendar, but I'm not sure about other implementations.

**Comment by tbar0970** [comment]
@eb3nezer do you have a sec to look at this?

**Comment by jefft** [comment]
Also, I've discovered that Jethro's .ics calendar output cannot be parsed by fastmail.com's calendars, because there is some whitespace after the `DTEND` date:
![image](https://user-images.githubusercontent.com/205995/70848330-11d7cc80-1ec4-11ea-952a-8345d257b817.png)
This causes a perl CaleDAV parser to break:
```
Syncing to your Test Jethro Roster calendar has been disabled:
[5775c23a-e5cb-4eb4-b251-1d99941d78c9]
 The calendar data was invalid: Date '20191208T150000Z ' was neither a DATE or DATETIME value 
at /home/mod_perl/hm/ME/CalDAVTalk.pm line 2105.
 ME::CalDAVTalk::vDate("20191208T150000Z ") called at /home/modperl/hm/ME/CalDAVTalk.pm line 1385
... 
```
