### ISSUE TITLE
Roster Reminder Script can't handle Christmas

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#629]
The roster reminder script does not behave when 25th December is not a Sunday. For example this year our weekly (Wednesday afternoon) Music roster reminder for Sunday 29th December was sent to the correct people, but included the details from the Christmas Day rosters. 
I'm a bit scatter-brained at the moment, but I think we need:
1. a separate cron job to handle Christmas rosters (perhaps setup to send on 21/22 Dec)
2. a step in the regular roster reminder script which 'ignores' the roster for 25th December when it's not a Sunday. Or when 25th December lands between the date of sending the roster reminder and the date of the next Sunday. 
Or something like that. 

Of course all this will also apply for Good Friday too.

**Comment by tbar0970** [comment]
See also #571 
I had a quick look at this and couldn't immedaitely spot the problem, Further investigation required.

**Comment by tbar0970** [comment]
Looks like there's an unanswered diagnostic question there in #571
