### ISSUE TITLE
Link From sourceforge.net Not Working

### ISSUE THREAD

**Issue by Dav9000** [tbar0970/jethro-pmm#63]
Hello,

This message at SourceForge.net -

http://sourceforge.net/p/jethro-pmm/discussion/679836/thread/93fb13f6/

says to click this link to get to GitHub -

https://github.com/tbar0970/jethro-pmm/issues.

Clicking the link gives a 404 error, because the full stop at the end is included in the link.

**Comment by tbar0970** [comment]
Thanks, I've fixed the note in sourceforge.

**Comment by Dav9000** [comment]
Thanks!

On Fri, Jul 3, 2015 at 1:27 PM, tbar0970 <notifications@github.com> wrote:

> Thanks, I've fixed the note in sourceforge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbar0970/jethro-pmm/issues/63#issuecomment-118221802>.
>



-- 
David Farmer
Admin
St John's Darlinghurst
02 9360 6844
0401 775556

**Comment by Dav9000** [comment]
Hi Tom,

Test email.  Just ignore.
