### ISSUE TITLE
Pagination of non-Western names

### ISSUE THREAD

**Issue by jjss46** [tbar0970/jethro-pmm#630]
Hi,

I'm from Hong Kong.  We use Chinese to input First name and Last name for Persons and for Families Name.  The filter for these 2 sections are A-M and M-Z.  This causes the records in Chinese cannot be displayed.  

Please advise how to fix it so the records can be shown.

Thanks
Jeff

**Comment by tbar0970** [comment]
Hi Jeff, thanks for raising this.
A church here in Sydney is using jethro with lots of Korean names so I've just asked them how it's working for them.
If needed I can alter this page to cope with chinese pagination.
in the meantime, I think this  and families > list all are the only pages affected by this problem. So you should be OK to use the rest of Jethro.

**Comment by tbar0970** [comment]
It turns out the Korean church isn't using Jethro for Korean names. 
I'll work on making the pagination multi-lingual-aware.
Can you point me to any standards for how to paginate lists of Chinese names?

**Comment by jjss46** [comment]
For Chinese Name, we use Last name to paginate.

Also for Chinese, we display Last Name and the First Name, (no space between the last name and first name). a bit different from English name.
I think it will be good to have an option to select how to display name system wise.

**Comment by tbar0970** [comment]
Thanks. Yes, for Chinese, "last name" and "first name" are not good labels!

In your conf.php file you can add the following to rename them:
```
define('PERSON_FIRST_NAME_LABEL', 'Given name');
define('PERSON_LAST_NAME_LABEL', 'Family name');
```

I'll work on fixing the pagination issue first. Controlling the order of names system-wide will be harder.

**Comment by tbar0970** [comment]
But another question re pagination:
In English we have 26 letters to divide by.
In Chinese, I believe it's many many more possible characters that a name could start with!
How does dividing into pages work?

**Comment by tbar0970** [comment]
Hi Jeff

I just ran a test and entered a person 陈 陈 into one of my systems.  They came up in the first page of Persons > List All and Families > List All.  So they're not invisible.  Are you seeing some different behaviour on your system? Database character sets can be a factor; my system has
 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci for the _person and family tables. Are you using something differrent?

**Comment by jjss46** [comment]
Maybe I have to update my version.

I think you can use the last name to do the pagination.
