### ISSUE TITLE
public area not enabled

### ISSUE THREAD

**Issue by gersona** [tbar0970/jethro-pmm#633]
I keep getting the following error message when trying to view a roster in public area
`The public area is not enabled for this Jethro System. You may like to view the members area `

I have set the roster visibility to **Show in public area** and provided the credentials to access the database in `conf.php` file

I'm using the latest release so far, **that is 2.27.0**

**Comment by s4069b** [comment]
I assume you mean the you have set 'show in public area' for the 'roster view' which you have setup.  But have you also gone into 'Admin' - 'System Configuration' and scrolled down to  'public area' and set the dropdown to 'yes' for 'public area enabled' ?

**Comment by tbar0970** [comment]
@s4069b is on the money.

**Comment by gersona** [comment]
@s4069b yeah, i also enabled the public area option from System Configuration

**Comment by s4069b** [comment]
Interesting. I'm also using 2.27.0 and the only way I can trigger the message "the public area is not enabled for this Jethro System..." is if I set the dropdown in 'Admin-System Configuration' to 'no' for 'public area enabled'. 

At the risk of making you want to crack me one... did you scroll to the bottom of the page in 'Admin' - 'System Configuration' and hit 'save'. (in other words if you go back in - is 'yes' still selected for 'public area enabled'. 

Otherwise I'm out of ideas, sorry.

**Comment by gersona** [comment]
i did hit save button.  
but i finally found where the problem came from, there was a missing row in the `setting` table of the database, the one that defines the **PUBLIC_AREA_ENABLED** var (as found in the `2019-upgrade-to-2.27.sql` file). 
Since I didn't upgrade from an earlier version, I didn't run any SQL script from the **upgrades** folder.   
So i manually ran the following queries taken from the latest upgrade file, and my problem was solved.
(it seems they are missing from the initial database setup process in **installer.class.php**)

```mysql
INSERT INTO setting
(rank, heading, symbol, note, type, value)
SELECT rank-1, heading, 'PUBLIC_AREA_ENABLED', 'Whether to allow public access to certain info at <system_url>public', 'bool', 1
FROM setting WHERE symbol = 'SHOW_SERVICE_NOTES_PUBLICLY';

UPDATE setting SET heading = '' WHERE symbol = 'SHOW_SERVICE_NOTES_PUBLICLY';
```

**Comment by s4069b** [comment]
well done! I'd never have thought to look there.

**Comment by tbar0970** [comment]
Thanks for tracking this down. Will fix.
