### ISSUE TITLE
First installation page is failing

### ISSUE THREAD

**Issue by obedmr** [tbar0970/jethro-pmm#636]
After setting up the database, web server and `config.php` file it's showing the following error:

```
 Fatal error: Uncaught Error: Call to undefined function _() in 
 /var/www/html/include/db_object.class.php:714 Stack trace: #0 
 /var/www/html/include/installer.class.php(465): db_object->getFieldLabel('first_name') #1 
 /var/www/html/include/installer.class.php(41): Installer->printForm() #2 
 /var/www/html/templates/installer.template.php(15): Installer->printBody() #3 
 /var/www/html/include/installer.class.php(19): include('/var/www/html/t...') #4 
 /var/www/html/index.php(51): Installer->run() #5 {main} thrown 
 in /var/www/html/include/db_object.class.php on line 714
```

**Environment:**
- Nginx
- php-fpm
- PHP  7.4.2
- Jethro - latest from github.com

**Comment by tbar0970** [comment]
Hi,
This would be because PHP's gettext module isn't installed on your server.
Looks like you're on a dedicated server? You can probably install a package/RPM to add gettext support to your PHP. See https://stackoverflow.com/questions/1882067/what-php-needs-to-work-with-gettext
