### ISSUE TITLE
PHP 7.2 and Jethro v2.27.0

### ISSUE THREAD

**Issue by garrettcam** [tbar0970/jethro-pmm#638]
The `each()` function is deprecated. Line 156 of `views/view_0_edit_note.class.php`
Variable passed to `each()` is not an array or object - Line 156 of `views/view_0_edit_note.class.php`

**Comment by garrettcam** [comment]
also in error log, but I don't understand

`array_key_exists()` expects parameter 2 to be array, null given - Line 414 of `include/db_object.class.php`

**Comment by tbar0970** [comment]
I've removed calls to each() in commit a9a999d967259442923d761ace095513b7d2bd7e
The other errors seem like they are a follow-on issues, although I can't quite figure out why. Please post again if you see similar problems in 2.28
