### ISSUE TITLE
"Persons>List All" Moves To The Last Records On The Page

### ISSUE THREAD

**Issue by Dav9000** [tbar0970/jethro-pmm#64]
Hello,

I recently upgraded from v2.9.2 to v2.10.4.

Since then I've noticed the "Persons>List All" function automatically scrolls to the bottom of the screen, so you can see "With selected people" is the last line displayed, but only if the user does not have "Persons & Families - add/edit/group" permissions.

**Comment by tbar0970** [comment]
No longer occurring.  TEsted in Safari and Chrome on Mac.

**Comment by tbar0970** [comment]
Reported to be still occurring on Firefox, 49.0.1.  With the -private-window option.

**Comment by tbar0970** [comment]
>  only if the user does not have "Persons & Families - add/edit/group" permissions.

**Comment by Dav9000** [comment]
Tom,
This problem has gone away in my upgrade from v2.18.2 to v2.21.2.
I am closing this issue.
Regards,
Dav9000
