### ISSUE TITLE
Installation failure on invalid datetime error

### ISSUE THREAD

**Issue by TheNiteCoder** [tbar0970/jethro-pmm#641]
I tried installing Jethro and when I finished entering all the setup information and I click the Setup the database and it fails displaying this message:
` Fatal error: Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `jethro`.`congregation`.`print_quantity` at row 1 in /var/www/html/include/db_object.class.php:228 Stack trace: #0 /var/www/html/include/db_object.class.php(228): PDO->query('INSERT INTO con...') #1 /var/www/html/include/db_object.class.php(195): db_object->_createFinal() #2 /var/www/html/include/installer.class.php(378): db_object->create() #3 /var/www/html/include/installer.class.php(36): Installer->createInitialEntities() #4 /var/www/html/templates/installer.template.php(15): Installer->printBody() #5 /var/www/html/include/installer.class.php(19): include('/var/www/html/t...') #6 /var/www/html/index.php(51): Installer->run() #7 {main} thrown in /var/www/html/include/db_object.class.php on line 228`

**Comment by tbar0970** [comment]
Thanks for reporting. This is related to recent versions of MySQL becoming more pedantic about default values. A fix for this was committed recently (revision ec4d25) and will be in the next release coming out in the next week.
