### ISSUE TITLE
feature request search on +61... phone numbers

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#642]
It would be really handy if we could search (from /home) for mobile numbers in +61... (international format) and have Jethro be smart enough to look for 04... instead.  Or even to be able to search on 'partial' numbers.   I only appear to have success if I enter a phone number 100%

**Comment by tbar0970** [comment]
Done. Relies on SMS_INTERNATIONAL_PREFIX and SMS_LOCAL_PREFIX settings being set.
