### ISSUE TITLE
Bugs with send-sms bulk action if no persons selected

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#643]
Hi,

We've just upgraded to 2.28.1 (great work btw!). We have SMS integration set up.

We're able to SMS individuals, but SMSing anything to a group breaks. Here I've created a sample group containing 2 users, and tried to send:

![image](https://user-images.githubusercontent.com/205995/76387020-03f9f080-63ba-11ea-9d84-0d83599e6ca3.png)

This happens on Safari and Firefox (73.0.1).

The Javascript is minified unfortunately so I can't dig much further. Is there is a way to run with unminified JS?

**Comment by tbar0970** [comment]
To use non-minified JS you could temporarily remove include/version.txt

Can you use dev tools to monitor network traffic while attempting to send, and look at the response the server gives? It should contain JSON but my suspicion is there's a PHP error message in there.

**Comment by tbar0970** [comment]
Just tested this on my prod system (using the bulk action tool to send SMS) and it worked OK. Could be related to your SMS config ?

**Comment by jefft** [comment]
I figured out the problem: I wasn't checking any checkboxes of users to SMS. I just kinda assumed "I've picked the group, now let's SMS them". 

Jethro behaves rather poorly if no checkboxes are checked:
- If I pick "the selected persons" and hits Send, then nothing much happens. The button changes from "Send" to "Sending..." and back to "Send", but no-one is messaged (obviously).
- If I pick  "the adults in the selected persons families", then I get the "AJAX error sending SMS" shown in the screenshot. Jethro is returning a HTML error message where the Javascript callback is expecting JSON, hence the 'unexpected character' error. The error message is because Jethro's family.class.php is a "show me the adults in this person's family" SQL, but the SQL is invalid because no users are selected.

So the PHP backend could handle the "no persons selected" case a bit more gracefully. The nicest fix would be for the frontend to disable the "Send" button until some recipients are selected.

**Comment by tbar0970** [comment]
THe other bulk actions have a prompt box that says "you haven't selected any persons - would you like to perform this action on all the persons listed?".  The send-sms action should do the same.  And, the adults-in-families option should be more robust.
