### ISSUE TITLE
'Undefined offset: 0' running action_plan.class.php after update to v2.28.1

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#644]
Hi, 

I updated our installation to v2.28.1 this morning and encountered this error when running an action plan on a family (error email pasted below). 

The result of running the action plan was otherwise as expected (as far as I can tell) with all five family members added to the desired group. 

Line 531 is this one - "	if ($groupMarkPresent[$i]) { "

--------
Undefined offset: 0 
Line 531 of /home/.../public_html/jethro/db_objects/action_plan.class.php

USER:       1 
REFERER:    https://.../jethro/?view=families&familyid=311
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

REQUEST: 
Array
(
   [view] => _execute_plans
   [personid] => Array
       (
           [0] => 670
           [1] => 671
           [2] => 673
           [3] => 674
           [4] => 672
       )

   [planid] => Array
       (
           [0] => 17
       )

   [plan_reference_date_d] => 12
   [plan_reference_date_m] => 3
   [plan_reference_date_y] => 2020
   [JethroSession] => k5i2amro4dl606gai4431hi8r2
   [wp-settings-3] => libraryContent=browse&advImgDetails=show&editor=tinymce&imgsize=large
   [wp-settings-time-3] => 1568333048
   [_wpfuuid] => a60d0ed9-a1df-4f63-87ec-fc46fe39f7e0
)

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /home/.../public_html/jethro/views/view_0_execute_plans.class.php
           [line] => 26
           [function] => execute
           [class] => Action_Plan
           [type] => ->
           [args] => Array
               (
                   [0] => person
                   [1] => 671
                   [2] => 2020-03-12
               )

       )

   [1] => Array
       (
           [file] => /home/.../public_html/jethro/include/system_controller.class.php
           [line] => 130
           [function] => processView
           [class] => View__Execute_Plans
           [type] => ->
           [args] => Array
               (
               )

       )

   [2] => Array
       (
           [file] => /home/.../public_html/jethro/index.php
           [line] => 58
           [function] => run
           [class] => System_Controller
           [type] => ->
           [args] => Array
               (
               )

       )

)

**Comment by tbar0970** [comment]
Thanks for reporting. I've saved a fix for the next release. If you edit and re-save your existing action plans it *might* stop this error from recurring in the meantime.

**Comment by s4069b** [comment]
thanks - I manually applied your fix
