### ISSUE TITLE
Jethro fails on import

### ISSUE THREAD

**Issue by TheNiteCoder** [tbar0970/jethro-pmm#648]
I was importing the church's data into Jethro and I had every field and it asked me to confirm the import. I hit the confirm button and was confronted with this screen.
![jethrosad](https://user-images.githubusercontent.com/40039930/76793638-c02d2f80-679b-11ea-9aa3-4615fbdf4bc2.png)

**Comment by tbar0970** [comment]
Sorry to hear of this frustration. We'll need to dig up a more precise error message. Can you have a look at your error log for any clues? I ran an import on my system a few days ago without issues, so it's likely to be something that only happens on your server.

**Comment by TheNiteCoder** [comment]
Where are the logs located? I can not seem to find them.

**Comment by tbar0970** [comment]
It varies depending on the server. If you're using cpanel/plesk there will be a main menu item for logs. If you have command line access you can look in /etc/logs/httpd or /etc/logs/php (again it varies according to your OS). There will be apache logs and PHP logs - it's worth looking in both.

**Comment by TheNiteCoder** [comment]
I got this error when I imported: `
[php7:notice] [pid 588] [client 192.168.1.10:58210] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'value_text' at row 7 - Line 662 of /var/www/html/db_objects/person.class.php, referer: http://192.168.1.150/?view=admin__import
` Which I am assuming is a text field with limited size that is trying to hold a large amount of text. Is there is a way to create a custom field that holds more characters?

**Comment by tbar0970** [comment]
Your diagnosis is right.
Custom text fields only hold 255 characters.
Normally MySQL just quietly truncates anything too long (which isn't ideal but at least keeps things moving).  But in your case MySQL is being more fussy (it's getting more fussy with age) and throwing this error, which is disrupting the import process.
For now, can I suggest you just find a way to cap your text values at 255 chars.
For longer things you can have a "note" column in your import which saves as a person note. That can be longer.

**Comment by TheNiteCoder** [comment]
That fixed everything thanks!
