### ISSUE TITLE
Email report script: 'current notes' column is empty

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#652]
When I use the roster reminder script as a cron job - I get this error "Fatal error: Your SMS config includes the _USER_MOBILE_ keyword but there is no current user! "

And when I use the email_report script as a cron job - 'notes requiring action' appear blank. 

Both issues would be related to the cron job not being run by a Jethro user. But I can't think of a workaround for each.

**Comment by tbar0970** [comment]
> When I use the roster reminder script as a cron job - I get this error "Fatal error: Your SMS config includes the USER_MOBILE keyword but there is no current user! "

As you say, this is because there is no current user, so no "from" number to use. The workaround is to change the SMS config so it doesn't include that keyword.

> And when I use the email_report script as a cron job - 'notes requiring action' appear blank.

Ah yes, this would be a new one, since note visibility has become more complex. It's probably fair for the cron job to see all notes... will work on this.

**Comment by tbar0970** [comment]
This fix will be in the next release. You can fix it in the interim you can run the following SQL (which won't interfere with the fortcoming upgrade)
```
DROP VIEW abstract_note;
create view abstract_note as
select an.* from _abstract_note an
WHERE ((an.assignee = getCurrentUserID() AND an.status = 'pending')
OR (`getCurrentUserID`() = -(1))
OR (48 = (SELECT permissions & 48 FROM staff_member WHERE id = getCurrentUserID())));
```
