### ISSUE TITLE
Cannot minify jethro-2.9.4.js (easy fix)

### ISSUE THREAD

**Issue by edwhiting** [tbar0970/jethro-pmm#67]
Running jethro-2.9.4.js through YUICompressor fails, however only a small change is required to make this work and achieve a 30% reduction in the size of the file.

Line 1758:
```javascript
$('.radio-button-group').keypress(function(e) {
	var char = String.fromCharCode(e.which).toUpperCase();
	$(this).find('div').each(function() {
		if ($(this).text().trim() == char) {
			this.click();
		}
	});
});
```
Change `char` to `theChar` and it's all good; the file runs through YUICompressor without a problem.

**Comment by tbar0970** [comment]
Resolved in Ed's recent pull request.
