### ISSUE TITLE
Upgrade to 2.29 missing SQL table

### ISSUE THREAD

**Issue by The-Big-V** [tbar0970/jethro-pmm#671]
I've been trying to upgrade from 2.28.1 to 2.29, following upgrade instructions.

After upgrade, there is an error notice when I log in. Checking error_log gives me this message:

`Base table or view not found: 1146 Table 'user_dname.congregation_attendance' doesn't exist - Line 162 of /home/user/public_html/jethro_folder/include/jethrodb.php`

There is no mention of this table in the upgrade script, and it does not exist in my old (working) database.

**Comment by tbar0970** [comment]
Thanks for reporting. This is a bug caused by some code sneaking into 2.29 which wasn't ready for release :( Will fix soon.
