### ISSUE TITLE
inactive roster roles still appear in the /public page

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#679]
During COVID fun we have various roster roles that are not required (eg Morning Tea). It's possible to select NO in the Active drop-down under the roster role description. However the role description still appears in the list on the /public page. 
The only way to stop it appearing is to zero/delete the description entirely. Which will then mean needing to re-enter once COVID goes away. 
It would be ideal to have 'inactive' roles NOT show on the /public page. /public/?view=display_role_description

**Comment by tbar0970** [comment]
Yep this is a fair expectation. Will fix.
