### ISSUE TITLE
DB error ordering report by attendance 

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#68]
...if attendance not included as a column in results.

Database Error: _doQuery: [Error message: Could not execute statement]
[Last executed query: SELECT p.id as ID, `p`.`first_name` AS 'p.first_name', `p`.`last_name` AS 'p.last_name', p.id as view_link, p.id as checkbox
				FROM person p 
						JOIN family f ON p.familyid = f.id
						
				WHERE
					(p.status = '0')
	AND (p.congregationid = '2')
	AND (p.age_bracket = '0')
				GROUP BY p.id ORDER BY `Attendance` ASC, p.last_name, p.first_name]
[Native code: 1054]
[Native message: Unknown column 'Attendance' in 'order clause']

**Comment by edwhiting** [comment]
Fixed.

**Comment by edwhiting** [comment]
What are the steps to reproduce this?

**Comment by tbar0970** [comment]
Main menu: Persons > Reports
Create a new report
Sort results by "Attendance"
Do not add any extra columns to result
Show results
--> get SQL error above.

**Comment by tbar0970** [comment]
ALSO: 
Apparently,
if you do add attendance as a column
then the DB error goes away
but the sorting is not as expected - eg 100% to 0% - it's some random order.

**Comment by edwhiting** [comment]
Fixed.  I have made some changes to person_query.class and pushed them to my repo so that you can review them, if you wish, before merging.

**Comment by tbar0970** [comment]
Fixed in https://github.com/tbar0970/jethro-pmm/pull/81
