### ISSUE TITLE
Actions on group members broken under Safari

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#681]
After upgrading from 2.28.1 to Jethro 2.29.1, Safari users are reporting that Group actions are broken. After picking a group, when the "With selected person:" drop-down is changed (e.g. to 'Send SMS'), we expect to get an action-specific form (e.g. the SMS form), but in Safari nothing happens:

![image](https://user-images.githubusercontent.com/205995/99480141-9b80fb80-29ab-11eb-84b2-5379c7bd2b3c.png)
In the Safari web inspector we see a Javascript error, "Syntax error, unrecognized expression: a[target="_append":

![image](https://user-images.githubusercontent.com/205995/99480019-61aff500-29ab-11eb-86b7-5dc601315e79.png)

This appears to be a jQuery error, probably from this line:
https://github.com/tbar0970/jethro-pmm/blob/63fa609186b86580a1c72b190d45976096bd1a73/resources/js/tb_lib.js#L392

and probably from commit https://github.com/tbar0970/jethro-pmm/commit/403c60de9b4834766728b2bfbeb50d30d3f08454 in 2.29.0.

**Comment by tbar0970** [comment]
Thanks for reporting.

**Comment by tbar0970** [comment]
@jefft always submits the highest-quality bug reports.  Full marks.
