### ISSUE TITLE
'email members' on Group view page - link stopped working (perhaps in most recent update?)

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#683]
Does anyone else have this issue? 

How to reproduce:
1. select a group and view it. Click the '@ email members' link at the top right of the table. 
2. result = nothing happens. 
(I tried viewing the link which 'email members' triggers - https://jethro.xxx.xxx.xx/?groupid=xxx&call=email&print_modal=1 . If I paste that in a browser I see interesting weird stuff, certainly not email addresses) 

Workaround
1. select all group members
2. use dropdown at the bottom of the page to 'send email' 
3. result... that works, so long as the browser has pop-ups enabled. 

Is it just me?

thanks.

**Comment by s4069b** [comment]
Trying to think of any other changes apart from recently updating jethro to most recent version. I may have changed Apache 2.0 Handler to FPM/FastCGI on the server. I know it's using FPM/FastCGI now, but it may have been Apache 2.0 Handler perviously.

**Comment by tbar0970** [comment]
Yes, this is a bug in the latest version - see #675 
Fix coming out in the next version.
