### ISSUE TITLE
Error when saving Configuration UI after editing Age Brackets

### ISSUE THREAD

**Issue by Pastor-Steve-DIMOM** [tbar0970/jethro-pmm#684]
![Jethro_Screenshot](https://user-images.githubusercontent.com/74899123/99942081-14ca7680-2d3d-11eb-807c-0dd8836b6cfb.png)

When trying to save configuration UI after adding new entries to the age bracket section I get the following error details below.
-------------------------------------------------------------------------------------------------------------------------------------

Fatal Error (Exception)
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `A5c242G921B6`.`age_bracket`.`is_adult` at row 1

Show Details
Line 236 of File /var/www/html/Jethro_PMM/include/db_object.class.php
	Array
(
    [0] => Array
        (
            [file] => /var/www/html/Jethro_PMM/include/db_object.class.php
            [line] => 236
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO age_bracket (label, rank, is_adult, is_default)
				 VALUES ('Adult - Not Competent', '6', '', '0')
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/Jethro_PMM/include/db_object.class.php
            [line] => 203
            [function] => _createFinal
            [class] => db_object
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/Jethro_PMM/views/view_10_admin__6_system_configuration.class.php
            [line] => 431
            [function] => create
            [class] => db_object
            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/Jethro_PMM/views/view_10_admin__6_system_configuration.class.php
            [line] => 30
            [function] => processAgeBracketOptions
            [class] => View_Admin__System_Configuration
            [type] => ->
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/Jethro_PMM/include/system_controller.class.php
            [line] => 130
            [function] => processView
            [class] => View_Admin__System_Configuration
            [type] => ->
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/html/Jethro_PMM/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

**Comment by tbar0970** [comment]
Thanks for reporting.
Fixed in commit 8607278c65553982b557dd1eeef8e2a14932ef12
Will be released in next version of Jethro.
