### ISSUE TITLE
css

### ISSUE THREAD

**Issue by awucweb** [tbar0970/jethro-pmm#685]
Hi I recently installed Easy Jethro on our webserver which we also run wordpress at https://awuc.org.au/easyjethro/ I also added a subdomain - https://our.awuc.org.au/

Installed ok but the css doesn't load and in the Dev tools I get the error

Failed to load resource: the server responded with a status of 404 () /easyjethro/resources/css/jethro-2.29.1.css:1 

I can see that the file jethro-2.29.1.css in the path /easyjethro/resources/css/ is there.

Wondering if it's a permission issue?

If you have any ideas that would be great

**Comment by awucweb** [comment]
I went back and installed 2.27 and the css was loaded but in 2.28.1 and 2.29.0 and in 2.29.1 (first attempt) it didn't load

**Comment by tbar0970** [comment]
Hi,
This does sound rather like a permissions error.  
Can you also check the permissions of the other files in the CSS directory. I think that error message is saying that jethro-2.29.1.css is trying to load another file - probably  resources/css/jquery-ui.min.css

(BTW a terminological note: What you're running is Jethro, but NOT Easy Jethro, which is the commercial hosting service)

**Comment by awucweb** [comment]
Thanks Tom, I'll play with version 2.27 at the moment. 

Yeah got the terminological not - just what I named the folder :-)

**Comment by awucweb** [comment]
I've installed 2.29.1 locally and the css is fine so will close this issue.
