### ISSUE TITLE
Error attempting to 'Configure' the last ad-hoc report

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#688]
If I create an ad-hoc report I can't edit/reconfigure it. When I try (either from the 'view' screen of the report, or from the top of the list of reports) I get a system error. 

------------------------------------------------------------------------------------------------------
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'TEMP' for column `jethro`.`db_object_lock`.`objectid` at row 1 
Line 871 of /var/www/......../include/db_object.class.php

USER:       1 
REFERER:    https://......../?view=persons__reports&queryid=TEMP
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

REQUEST: 
Array
(
   [view] => persons__reports
   [queryid] => TEMP
   [configure] => 1
)

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /var/www/......../include/db_object.class.php
           [line] => 871
           [function] => query
           [class] => PDO
           [type] => ->
       )

**Comment by tbar0970** [comment]
Thanks for reporting.
This code hasn't changed recently but I suspect recent MySQL versions are being more strict rather than just converting it to zero.

**Comment by tbar0970** [comment]
I can't reproduce this in 2.30.0 on php 5.3, or in my latest dev version on php8.  It's possible that it only manifests on recent php versions, and that other recent unreleased changes have fixed it. Please let me know if it still occurs after the next release comes out.

**Comment by jefft** [comment]
This can be replicated in Jethro 2.31.1 using php 7.2 and php 7.4, with MariaDB 10.3.32:

- Go to Persons -> Reports and 'Create a new report'.
- The parameters of the report don't matter, just click 'Save and view results'
- Click 'Back to list of results'
- The first line should be 'Last ad-hoc report'. Click 'Configure'.

![image](https://user-images.githubusercontent.com/205995/147903093-65277a6b-e834-4343-b5e4-56378fc07913.png)

Stacktrace:
```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'TEMP' for column `jethro`.`db_object_lock`.`objectid` at row 1
Line 916 of /srv/www/jethro/2.31.1/include/db_object.class.php

USER:       536
REFERER:    https://jethro/?view=persons__reports
USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

REQUEST:
Array
(
    [view] => persons__reports
    [queryid] => TEMP
    [configure] => 1
)


BACKTRACE:
Array
(
    [0] => Array
        (
            [file] => /srv/www/jethro/2.31.1/include/db_object.class.php
            [line] => 916
            [function] => query
            [class] => PDO
            [type] => ->
            [args] => Array
                (
                    [0] => INSERT INTO db_object_lock (objectid, object_type, lock_type, userid, expires)
                                VALUES (
                                        'TEMP',
                                        'person_query',
                                        '',
                                        '536',

                                        NOW() + INTERVAL '120' MINUTE)
                )

        )

    [1] => Array
        (
            [file] => /srv/www/jethro/2.31.1/views/view_3_persons__3_reports.class.php
            [line] => 75
            [function] => acquireLock
            [class] => db_object
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /srv/www/jethro/2.31.1/include/system_controller.class.php
            [line] => 186
            [function] => printView
            [class] => View_Persons__Reports
            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /srv/www/jethro/2.31.1/templates/main.template.php
            [line] => 94
            [function] => printBody
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

    [4] => Array
        (
            [file] => /srv/www/jethro/2.31.1/include/system_controller.class.php
            [line] => 128
            [args] => Array
                (
                    [0] => /srv/www/jethro/2.31.1/templates/main.template.php
                )

            [function] => require
        )

    [5] => Array
        (
            [file] => /srv/www/jethro/2.31.1/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                )

        )

)
```
