### ISSUE TITLE
Roster Availability

### ISSUE THREAD

**Issue by awucweb** [tbar0970/jethro-pmm#692]
Hi Tom,
Thanks for the update and the addition of the checkin with integrated QRCode.

This is a feature request which I can't see has been requested before. Before we do a new roster we send out an email to the team to indicate on a spreadsheet what weeks they are / are not available with a Yes/No/Maybe. 

I thought It would be great if this could be incorporated into the Members area so that a user could login and from the Service Dates listed they could give this indication and then a csv could be made available from the backend to download or perhaps if a user has indicated No for that date then they are excluded from the drop down for that day on the roster assignment.

I hope the above is of interest and I'd be keen to hear if other uses do anything similar.

**Comment by tbar0970** [comment]
Hi there

Yes - thanks for raising this.  I've been thinking about it, but it seems hadn't put it in an issue.

The current workaround in Jethro is to add a roster role called "away" and watch out for clashes between that role and others.  But a better approach would be like you suggest:
* In the members area members can enter "planned absences" for certain periods
* In the control centre, admins can do the same on people's behalf
* When rostering, people with planned absences are greyed-out in the roster assignment dropdowns
* When marking attendance, planned absences could be indicated, so the roll marker realises that person is likely to be absent.

This wouldn't cover the "maybe" or "prefer not" scenario, but I think trying to cover that would add more complexity than it's worth.  Interested to hear others' opinions on this.

**Comment by tim-pearce** [comment]
I second this.
Our church does not currently use Jethro for Sunday rosters but our administrator is looking into it.
I use Jethro for youth groups and play group. Our administrator is considering Jethro because we are already using it.

**Comment by tim-pearce** [comment]
I hope to begin some work in this area soon.
My version of the roster edit/view page differs somewhat from the 'official' version so I will need to reconcile that.
I don't have 'public' access so the admin person is the one who updates things.
My first change would be to exclude people from the dropdown list if they are marked as 'absent' in that volunteer group for that date. (I checked that you can mark people present/absent) for a future date in the record attendance area.

**Comment by tim-pearce** [comment]
In the attendance record for an individual, make it possible to record for a date that has not been entered in the record attendance function. Perhaps even allow for a range.

**Comment by tim-pearce** [comment]
Replicate a roster. In other words, if you have a roster for a given period then create a new roster for another period with all the same people in the same positions except where they are not available or no longer in the group.

**Comment by tim-pearce** [comment]
In display roster assignments (but not edit) only display lines where there is data for that roster view. I use document merge here and currently I also have the rosters for the Thursday play group - I don't want both of them interleaved.

**Comment by tim-pearce** [comment]
Turn the data for document merge 'sideways'. Currently the roster for playgroup has the date down the side and the roles across the page. Our current church roster is arranged with the dates across the page and roles down the page. 
I think I should be able to 'rotate' the data to suit.

**Comment by awucweb** [comment]
Hey Tim that's great to hear. Let me know if you need a tester for your work.
