### ISSUE TITLE
MySQL8 incompatibility means settings don't load, leading to undefined constant errors

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#693]
I have just updated my server from UBUNTU 18.04 to 20.04
In the process I've gone to PHP 7.4 (from 7.2 I think).
I am now getting a lot of errors of the form -
Use of undefined constant XXX - assumed 'XXX' (this will throw an Error in a future version of PHP)
I started to define them in my config.php but I keep coming across more of them!

**Comment by tbar0970** [comment]
There might be some niggles with PHP7 but shouldn't be constant errors like this.
can you post some examples of the constants it's complaining about?

**Comment by tim-pearce** [comment]
I added this to my conf.php
> define('SYSTEM_NAME','Rockingham Church of Christ');
define('MEMBER_LOGIN_ENABLED','false');
define('CHUNK_SIZE','1024');>
I also found this at the end of the file
>define('SHOW_ERROR_DETAILS', TRUE);>
I will try changing that to false!

`

**Comment by tim-pearce** [comment]
Now it just tells me an error occurred in various parts of the system without telling me what the error is!

**Comment by tim-pearce** [comment]
I have created define statements in my conf.php for all the items in my setting table thus ensuring they are defined. Don't know why they were not set from the table?
Unless that is something to do with the MySQL update?

**Comment by tbar0970** [comment]
Hi Tim

The fact that the rows in your settings table haven't become PHP constants shows something is wrong. It's worth figuring out.  Could there be a mysql permissions problem with Jethro reading from the settings table?  Can you try connecting to mysql using the exact credentials Jethro uses, and see if you can select all from setting ?

**Comment by tim-pearce** [comment]
Using phpmyadmin and those credentials there is no problem.

**Comment by tim-pearce** [comment]
Found the problem at line 40 in function getSettings in includes/config_manager_class.php
`$SQL = 'SELECT symbol, s.* from setting s ORDER BY s.rank';`
I added the s. in front of rank. I expect rank is a reserved word in mySQL 8.
There is an try catch which masks the fact that an error has occurred.

**Comment by tbar0970** [comment]
Ah, well done.  You're right about the reserved word - https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R

So you've now been able to remove those constants from your conf file, and Jethro is reading them OK from the database?

That try-catch is to cope with the installation situation where the table doesn't yet exist.  I will try to handle that differently so that errors like this aren't concealed.

**Comment by tim-pearce** [comment]
I only removed one but that one is now definitely coming out of the database.

**Comment by tim-pearce** [comment]
I upgraded to 2.30.0 again 
The upgrade script tripped over the rank field. I fixed that by wrapping it in back ticks (`).
I then went to update the site name back to it original name and got a problem with the rank field here
Line 314 of File /var/www/html/Jethro/views/view_10_admin__6_system_configuration.class.php
Found 3 references to rank in that script. Changed them to `rank`.
