### ISSUE TITLE
Cannot upgrade to 2.30 with MySQL 8

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#694]
Now on UBUNTU 20.04 when I try to update the database when I get to
ALTER TABLE attendance_record
ADD COLUMN checkinid INT(11) DEFAULT NULL;
It says this is an invalid value for 'date'. I tried various values such as 0, '1000-01-01' and '0000-00-00' but all with the same result!

**Comment by tim-pearce** [comment]
MySQL version is 8.0.22

**Comment by tbar0970** [comment]
There must be something more to the picture here.
The original query is adding a column of type INT - why would MySQL be complainig about default value for date?  Hmm.
Can you send the results of SHOW CREATE TABLE attendance_record?

**Comment by tim-pearce** [comment]
I can now start MySQL with sql_mode set but I have changed it to
sql_mode = "NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
Maybe this will make a difference!
Have to do other stuff now.

**Comment by tim-pearce** [comment]
See recent comment on issue #693

**Comment by tbar0970** [comment]
So, once you solved the "rank" problem discovered in #693 did the rest of the upgrade end up working OK? If so we can close this issue and just fix that one.

**Comment by tim-pearce** [comment]
I haven't tripped over the issue again, but there are parts of the system I don't use so there could still be some instances lurking in the code!
