### ISSUE TITLE
MYSQL8 or PHP7.4 lock always expired

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#697]
When I try edit any person I get
	
Lock warning
Your lock on this object has now expired. You cannot save the changes you have made. Would you like to reload the form and try again?

I can't get past this!

In db_oblect_lock I see
objectid | userid | lock_type | object_type | expires |  
777 | 1 |   | person | 2072-03-22 09:38:24
778 | 1 |   | person | 2072-03-22 09:39:46

phpmyadmin reports "Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available."

Deleting all rows from the table does not resolve the issue!

**Comment by tim-pearce** [comment]
I tried adding a default to the switch statement at about line 2924 of Jethro-2.30.0.js but that did not work!
For now I have commented out the contents of ShowLockExpiryWarning and ShowLockExpiredWarning.
I also observe "Empty string passed to getElementById(). jethro-2.30.0.js:2:10386" in the console of my browser.

**Comment by tim-pearce** [comment]
I have resolved my problem by editing the Lock length in settings.
It was some weird long number. I tried to set it to 15 (minutes) but it insisted that was not valid and gave me two real numbers close to that. I now have it at 15.783333!

**Comment by tbar0970** [comment]
OK so somehow your lock length setting became extremely big.  My best guess is something weird happened in your DB migration or upgrade?
The browser enforces a whole number for the lock length setting.  When I tried to set mine to 15.783333 I got this:
![image](https://user-images.githubusercontent.com/2133676/107936327-9f3a1380-6fd6-11eb-95cd-b31d6e9fb94e.png)

**Comment by tim-pearce** [comment]
(I can't manage to get a screen shot)
Using a different browser (Brave) on a different PC I still get the same error telling me to use 14.783333 or 15.783333!

**Comment by tbar0970** [comment]
I reckon this is a bug specific to that browser.

**Comment by tim-pearce** [comment]
Nope. Exactly the same on two different browsers on two different computers!

**Comment by tbar0970** [comment]
Wow. Which other browser is doing it?

**Comment by tim-pearce** [comment]
Both computers are running Artix Linux
On the 'other' computer it was Firefox (85.0.2)
On this computer -
Brave (1.20.103 based on Chromium 88.0.4324.152)
Seamonkey (2.53.5)
Firefox (85.0.2)
I will try on a Windows PC next time I am at the church.
(I am using http within the local network at church. To access remotely I use ssh and map port 80 on the server to port 8080 on my local PC)

**Comment by tim-pearce** [comment]
The mystery remains!
I tried it with Firefox on Windows 10 in the office and it still insists on that number.
I thought maybe it was a MySQL issue but when I look in the settings table it looks no different to any of the other 'int' fields in there!
I do recall seeing some code somewhere to do with a change of meaning for that field.

**Comment by tbar0970** [comment]
OK. I wonder if something weird in the DB upgrade has caused a decimal value to get into that field, and the browsers are requiring that you add or substract integers from that.  If you clean up the value in mysql directly, I expect it will go away?

**Comment by tim-pearce** [comment]
I changed the value in the database to 15 and was able to change it to 14 in the front end.
Maybe, when I had to manually set those constants, I got that one wrong somehow.
