### ISSUE TITLE
Checkin

### ISSUE THREAD

**Issue by aesme** [tbar0970/jethro-pmm#702]
I like the new ideas of check-in. Is it possible to only display the check-in Tab? I don't understand the purpose of the "Raw View" how to remove it.

**Comment by tbar0970** [comment]
Hi,
I don't see the "raw view" link when I go to the checkin page.
Are you navigating to it from the attendance > checkins page ?
![image](https://user-images.githubusercontent.com/2133676/109490723-bc91d600-7adc-11eb-85bd-e971070e57dc.png)
