### ISSUE TITLE
Sorting within families

### ISSUE THREAD

**Issue by kristanslack** [tbar0970/jethro-pmm#703]
I may be missing something (very likely, I'm a new Jethro user), but the sorting within a family unit for reports seems to be based around the age category. But what if within a family there are adult children who still live at home. In that case it becomes a lot less clear who are the primary adults in that family.

This arose because I'm using the families 'contact list' report section, and some alphabetically antecedent adults are being put first in a family even though they are actually the adult-children living at home.

Is there any way of a family having a persons with a 'primary' category (that can allow multiple adults to be primary, rather than the weird  'primary'/then 'spouse'option)?

**Comment by tbar0970** [comment]
Yes, the sorting is by age bracket, and Jethro doesn't have a concept of "position in family".
You might like to create a "young adult" age bracket to get those "non-primary" adults out of the way :)
