### ISSUE TITLE
Attendance running total

### ISSUE THREAD

**Issue by kristanslack** [tbar0970/jethro-pmm#704]
It would be really help to have a running total when attendance is being marked. That way, when we know that there were N visitors, we could simply add that to the running total - rather than needing to save and then go back in.

That is, we don't do a headcount (kinda relying on Jethro to do that after marking people present) - but we are always aware of how many visitors/guests are there.

**Comment by s4069b** [comment]
I really like this feature in v2.34.0. Thank you!

**Comment by s4069b** [comment]
Actually, after playing around a bit more, I just noticed a minor formatting glitch. If the Congregation/Group you're marking attendance for does not have long names, then this word-wrap happens. 
Not sure how to stop the text wrapping. Might have a look later. 

<img width="670" alt="Screenshot 2023-08-29 at 8 46 06 am" src="https://github.com/tbar0970/jethro-pmm/assets/29622389/2856851b-8287-4119-83c0-3b380189a119">

**Comment by s4069b** [comment]
This 'fixes' the formatting. Hope nothing else broke?

db_objects/attendance_record_set.class.php
change line 357 from class="muted" to class="muted nowrap"

![Screenshot 2023-08-29 at 10 17 51 am](https://github.com/tbar0970/jethro-pmm/assets/29622389/991c37a1-e5d1-400a-a7a8-367f9b8df172)
