### ISSUE TITLE
Combination of group-restriction and congregation-restriction on user accounts

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#712]
User accounts can be restricted, such that they can only see persons in certain groups or certain congregations.
Currently, if you specify one group *and* one congregation in the restrictions for a user account,  it seems that user can only see persons who are in BOTH that group and that congregation.
This issue is to discuss and perhaps implement a change whereby the account would be restricted to seeing persons who are in EITHER the specified group OR the specific congregation.  
Input welcome.

**Comment by tbar0970** [comment]
Todo: Look how many EJ systems have the combo of cong and group restrictions for an account.

**Comment by s4069b** [comment]
Been trying to think of examples of when 'either' congregation or group might apply. We used congregation restrictions and group restrictions (eg Youth Group or Kids Church or Growth Group...). Used  group + congregation too (eg access to music Music teams by congregation). But application of congregation OR group are not readily coming to mind?

**Comment by tbar0970** [comment]
@s4069b  do you have one big "music team" group for the whole church, and you grant access for an account to see "music team members who are in congregation X" ?  
(There's another church who wants to be able to grant an account to "see everyone in congregation X, plus all the roster volunteers in groups ABC")

**Comment by tbar0970** [comment]
(Note to self: 7 EJ systems have accounts with both kids of restriction at once)

**Comment by tbar0970** [comment]
It really depends if we think of this as a "restriction" or a "permission".  It's currently labelled as a restriction, and the more you add things the more restricted you are.

**Comment by tbar0970** [comment]
Of the current restrictions I can see, nobody looks like they are relying on the "AND" logic. It's generally "restrict to congregation X and to groups A,B,C which are related to congregation X". The congregational restriction is essentially redundant in these cases.  We could change the logic and, as part of the upgrade, remove the congregation restriction, and the result would be the same.
