### ISSUE TITLE
Where is the 'add person' button?

### ISSUE THREAD

**Issue by shuhytabulk** [tbar0970/jethro-pmm#717]
I've been able to set up my database by importing to Jethro from CSV. However, now I want to add a new child to a family. I have add/edit/group permissions, and no restrictions. (I've also set the system to allow 'restricted users can add', just in case.) But my persons dropdown does not have the 'add' option, nor does the persons list. See pics.
![2021-07-26 15_25_52-Jethro PMM - PMPC - Editing User Account for Benjamin Shuhyta](https://user-images.githubusercontent.com/87963448/126937481-c8901ff9-32e9-494d-8788-52fbc56288cb.png)
![2021-07-26 15_27_36-Jethro PMM - PMPC - All Persons](https://user-images.githubusercontent.com/87963448/126937568-e2c78fe9-c438-4a2b-bdca-feb87b0d78aa.png)

**Comment by brett-mcgirr** [comment]
Look in the "Families" menu. Once you've found the family you can add the child as a new member to the family.

**Comment by shuhytabulk** [comment]
> Look in the "Families" menu. Once you've found the family you can add the child as a new member to the family.

Ah! Thank you so much.
