### ISSUE TITLE
Format contact list

### ISSUE THREAD

**Issue by shuhytabulk** [tbar0970/jethro-pmm#720]
Hi. The 'generate contact list' feature in the families tab is very helpful, but is there a way to change the formatting and fields:
a. change font size for family name
b. change the arrangement of the fields
c. change the fields to include [family.members] rather than individual names.

Cheers, B.

**Comment by tim-pearce** [comment]
If you create a report and then select the document merge option you can create a document that is formatted however you want.

**Comment by tbar0970** [comment]
For the contact list, you can certainly change the formatting but the fields are pretty much fixed (apart from the options when you generate the list).

The formatting (fonts etc) use paragraph styles in word, so you can edit those styles after downloading the DOCX.  You can also upload a template file that contains modified styles.  Download this file: https://github.com/tbar0970/jethro-pmm/blob/master/resources/contact_list_template.docx?raw=true  then modify the style definitions, then save it in the Documents area of Jethro, in a folder called `Templates`, as `contact_list_template.docx`.  Jethro will then use it as the basis for contact lists it generates.

@tim-pearce, I don't believe the document-merge bulk action supports grouping results by family, does it?
