### ISSUE TITLE
Give services their own categories rather than by congregation

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#722]
We have two services on Sunday. The system currently only allows for one per day.
I propose that a service be associated with a group category (not a group). This partly assumes that there is a link table so you can see all groups subordinate to a category, not just the immediate subordinate.
This could then link into the rostering function.

**Comment by brett-mcgirr** [comment]
This would be useful for my church too, which has ad hoc services (e.g. around Christmas) and currently requires us to duplicate much of the setup for the second service.

**Comment by tim-pearce** [comment]
We don't use any detailed run sheets for our services.
We have a couple of documents that list the outline of the service and what songs etc. are required. All our songs etc. are handled in Easyworship.
I propose to associate a service with a category group and then associate a roster view(s) with that group. Then over in the Display/Edit rosters only display rosters for those services related to the view plus any not related to any (for backward compatibility).
The question is - does this clash with creation of run sheets?

**Comment by tbar0970** [comment]
The current limit is one service *per congregation* per day.
Do you guys have several services on one day for the same congregation?

**Comment by tim-pearce** [comment]
Short answer is yes, although we are dropping back to one again - for a while.

**Comment by tbar0970** [comment]
Further thinking on this:

It's fairly coincidental that currently each service has to belong to one *congregation*.  Wanting to do rosters/run sheets for things that aren't actually congregations leads create 'fake congregations' for youth group etc, which just adds confusion.

Also: Some churches have everyone in one big Jethro congregation, and use groups to capture who comes to church when (this allows a person to be in several of these groups).

SO: what we could do is break the connection between congregation and services, and instead create an __event_type__ entity to which services would belong.  Event types could be "9am service", "10.30 service", "Wednesday playgroup" etc.  Each service would belong to one event type.

This would be much simpler than an approach that attaches services to a congregation AND some other distinguishing entity.

Thoughts?

**Comment by tbar0970** [comment]
> I would add to that to associate roster views to event types as - for instance - I don't want to see the the Sunday service dates for play group and Sunday rosters don't want to see the play group dates.
Ah, I see what you mean.  When editing the roster for a Wednesday playgroup, you wouldn't want Sundays to show up.  This filtering already occurs thanks to the link between roster_role and congregation.  If there is no 6pm service on a certain date, that date doesn't show up when editing a roster consisting of 6pm-related roles.  This link would need to be updated so that a roster role would now belong to an event_type rather than a congregation.

I do think using the group_category table for this purpose would be confusing because many group categories won't have anything to do with services.  Typical group categories are things like "all volunteers", "bible study groups", "outreach contacts" etc.  Most of these don't line up with event types. 

Question: in your current setup do you have several congregations, or everyone in one big congregation?

**Comment by tbar0970** [comment]
Notes to self about the work required to introduce a "service type" entity:

- congregation_service_component table would become service_type_service_component
- roster_role.congregationid would become roster_role.service_typeid
- roster_role_service_field.congregationid would become roster_role_service_field.service_typeid
- service.congregationid would become service.service_typeid

Upgrade process:
- create the service_type table
- insert into service_type select * from congregation where meeting_time <> ""  -- keep the IDs the same
- rename the columns in the other tables
- change the foreign keys on the other tables

**Comment by tbar0970** [comment]
For attendance purposes, do we need to maintain a link between a service and a congregation (or group)?  - "These are the people we expect to come to this kind of service" ?

**Comment by kristanslack** [comment]
So did this feature come about? We've just started night church, knowing that some people will gather then (because of shift work) and sometimes in our morning congregation. We want accurate numbers for each (rather than having to mark someone as attending a different service like 10AM when they actually came to the PM service).

It would be really helpful for service attendance to not be connected so tightly to congregations.

**Comment by tbar0970** [comment]
> So did this feature come about? 
Still in the pipeline

>We've just started night church, knowing that some people will gather then (because of shift work) and sometimes in our morning congregation. We want accurate numbers for each (rather than having to mark someone as attending a different service like 10AM when they actually came to the PM service).

This is a slightly different issue.  THe "one congregation per person" restriction would continue.  If it's important for you to record the exact service a person came to, best to create a *group* representing attendance at each service.

**Comment by kristanslack** [comment]
Is it not possible for a headcount to belong to a service or a group, and not a congregation? The service is (nominally) a particular gathering of a congregation (the ‘congregating’ of the congregation), and the group might be a group which gathers also. Would it work to have a master ‘gathering’ category, which all services would belong to, and some groups would also?

**Comment by tbar0970** [comment]
Some churches don't use 'services' in Jethro at all.  But they do record attendance & headcounts for congregations and groups.  

When we introduce service-categories, we will automatically create a service-category related to each congregation.

So after that, we should be OK to have each headcount related to either a service-category or a group.  This will work even if there are no actual services.

**Comment by tbar0970** [comment]
This has, in effect, been implemented in #834 - a congregation can now function as a "service container" rather than a "person container" (or it can be both)
