### ISSUE TITLE
Jethro rejects apostrophe in an email address

### ISSUE THREAD

**Issue by wayneschuller** [tbar0970/jethro-pmm#73]
I have a church member who has an apostrophe in their email address - it works ok from gmail.

However Jethro won't let me enter it into the database.

**Comment by edwhiting** [comment]
Need more information for this:
 - which version of Jethro are you using?
 - which form in Jethro rejects apostrophes in the email address?  What are the steps to reproduce the defect?
 - which browser, what version?
 - which operating system?

I tried to reproduce this in the latest version of Jethro in Firefox v38.2.1 on Linux but it appears to be working perfectly.

Regards,
Edward

**Comment by tbar0970** [comment]
I can't reproduce on chrome/mac either.

**Comment by tbar0970** [comment]
@wayneschuller ?

**Comment by wayneschuller** [comment]
Currently am trying to get my jethro setup working again - will recheck my bug again soon.

**Comment by wayneschuller** [comment]
Ok I can't reproduce the bug - I can't remember what the test case was.
