### ISSUE TITLE
Permissions: Reports ‑ save shared reports not working as expected

### ISSUE THREAD

**Issue by NeilAtw** [tbar0970/jethro-pmm#737]
When a user account has the 'Reports ‑ save shared reports' permission unticked, they cannot edit existing reports (changes not saved), and new reports cannot be saved.
Expected behaviour is that reports for viewing by that user only should be able to be edited and saved.

**Comment by tbar0970** [comment]
"Cannot edit existing reports" is more or less correct behaviour - they shouldn't be able to save config changes to existing reports that are visible to everyone.

But "reports not saved" (even for a brand new report) is a confirmed bug.

**Comment by NeilAtw** [comment]
Hi Tom,
RE: "Cannot edit existing reports" is more or less correct behaviour  - Agree, if the report is set to visible to everyone, but 99% of our reports are set to 'only visible to me' - So does that classify as a bug?

**Comment by tbar0970** [comment]
Yes - a genuine bug - fixed in the commit above.  Will be in the next release.
