### ISSUE TITLE
File Permissions in Latest Release (2.31.1)

### ISSUE THREAD

**Issue by in-principio** [tbar0970/jethro-pmm#745]
I recently updated Jethro on our server to 2.31.1 and the CSS/Javascript did not run when I loaded it.

After some investigation, I found that the file permissions of this release were different than the file permissions of the previous release we were using (2.28.1). 

I manually went in and changed all of the directories to 755 and files to 644 and that resolved the issue.

**Comment by tbar0970** [comment]
i checked today and all the files and folders in git have correct permissions as above.
I'll have to check the release process to see if it is messing them up prior to packaging.

**Comment by tbar0970** [comment]
Fixed in release script
