### ISSUE TITLE
Feature request: Forms linked to Jethro

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#753]
Hi again, it would be great to have the ability to create a form using Jethro, and to then have the form publicly viewable, embedded in a website, or sent via email. The responses could be saved in Jethro, staff notified when there's a new response, and then have an option for a new contact to be created from the details in the form, or an existing contact updated. 

Thanks, Andrew (St Jude's Randwick EJ user).

**Comment by tbar0970** [comment]
Yep, good idea, covered in issue #724. Let's continue the conversation there.
