### ISSUE TITLE
installing Jethro and copying database from another computer

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#757]
I am trying to install Jethro on a new computer. I am using XAMPP 8.1.2

I have created a database and user / password for the database

Created a directory xampp/htdocs/Jethro

I have extracted files from "jethro-2.31.1.zip" to xampp/htdocs/Jethro

Edited the the conf file to the relevant locations 

type "localhost/Jethro" in address line

and I get the following error message:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1030 Got error 194 "Tablespace is missing for a table" from storage engine InnoDB in C:\xampp\htdocs\Jethro\include\jethrodb.php:162 Stack trace: #0 C:\xampp\htdocs\Jethro\include\jethrodb.php(162): PDOStatement->execute() #1 C:\xampp\htdocs\Jethro\include\config_manager.class.php(43): JethroDB->queryAll('SELECT symbol, ...', NULL, NULL, true) #2 C:\xampp\htdocs\Jethro\include\config_manager.class.php(6): Config_Manager::getSettings() #3 C:\xampp\htdocs\Jethro\include\init.php(49): Config_Manager::init() #4 C:\xampp\htdocs\Jethro\index.php(38): require_once('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\Jethro\include\jethrodb.php on line 162

Once I get this installed, I then would like to copy the database over from a different computer.

When I tried simply copying the database into mysql/data and then typing localhost/Jethro, it was coming up with an error:

Fatal error: THis system has no user accounts - it has not been installed properly in C:/xammp_8_1_2/htdocs/Jethro/include/user_system.class.hph on line 160

note that I have copies of the database from Jethro version 2.27.1 (I think) and also the database which has had all the upgrade sql files run to 2.31.1

Thank you for any help you can offer.

**Comment by GlenMcDonald** [comment]
I started again - reinstalled xampp, downloaded Jethro files, created a new database and created a new user for the database, edited the conf file and ran Jethro

This time it launch, but came up with a blue error box in the Initial user account (just before the First name Box). 

In the username field was the entry <div class=

and next to the username field was the words: "An error occurred. Please contact your system administrator for help. " class="compulsory" maxlength="255" size="30" autocomplete=new-password" />"

I went and entered the information as requested. 

Came up with 98 blue Error messages boxes with the words: "An error occurred. Please contact your system administrator for help."

Under these error boxes / messages was:

Installation Complete!
You can now [log in to the system](http://localhost/Jethro/) to start work.

I click on the link and I am able to log into Jethro, but there are alot of error boxes throughout the different screens

I tried copying the database from the other computer into mysql/data/

It came up with an error (I didn't not it but along the lines of no user)

I copied the generated database from the installation back into its place, and it now comes up with another error

I have tried a number of times to delete the database and user and recreate them and run Jethro again (trying to restart the whole process) and I am now getting this error:

Notice: MySQL database is not empty. Installer is aborting in C:\xampp\htdocs\Jethro\include\installer.class.php on line 16

I hope some of this helps diagnose what is going on.

Glen

**Comment by tbar0970** [comment]
Hi Glen.
Sorry to be slow to respond here.

First: If you want to copy an existing database across, you really need to export it as an SQL file from its original location, then import that SQL file onto your xampp system.  Copying the mysql data files is never a good way to do it.

It sounds like you're following the correct installation steps from the Jethro point of view.  But it sounds like there is something unhealthy in your mysql server.

If you're seeing "An error occurred. Please contact your system administrator for help." that's a generic front-end error message.  Have a look in your PHP error log or mysql error log for the full details.

To go back to your original problem:  I havne't seen that "tablespace is missing for table" error before, but there is some info about it here:  https://bobcares.com/blog/mysql-tablespace-is-missing-for-table/
