### ISSUE TITLE
Archived group with 'include on add family' still appears when adding family

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#758]
Just stumbled across that when adding a new family... thought I added them to the 'youth group' group... but it was last year's group which I had archived. Wondered where they got to when the kids didn't show up in the 'parental permission required' email this week.

**Comment by tbar0970** [comment]
Thanks for the bug report.  Will fix.
Semi-related comment: I've found it's useful to name groups "Youth Group 2021" etc to avoid the kind of confusion you mention. Then you can look at a person's archived groups and see they joined youth group in 2020, etc.

**Comment by s4069b** [comment]
You are a genius (with the Youth Group 2021 idea) - that is what I have been doing (But I neglected to select the option of adding the 2022 group to the add family dialogue plus didn't read properly when I added the family... ID10T error apparently)
