### ISSUE TITLE
Error: Can't get Jethro to run on server running PHP 5.5

### ISSUE THREAD

**Issue by ken-h** [tbar0970/jethro-pmm#76]
v2.11

My Jethro installation runs fine on my Dreamhost server running PHP 5.4 FastCGI, but if I change the server PHP version up to 5.5 FastCGI (or 5.6 FastCGI) I get a blank screen in place of the usual Jethro home page.

**Comment by tbar0970** [comment]
Hi Ken
Can you have a look in your PHP and Apache error logs for any clues.

**Comment by ken-h** [comment]
It turns out that this was an error on my part.  The default setup of PHP on Dreamhost is such that Pear support is not enabled unless you explicitly add the path to Pear in the server phprc file.  When I moved from PHP 5.4 to PHP 5.5 I lost my path information.  Once reinstated, Jethro worked once more.

You can close this issue...
