### ISSUE TITLE
Why are documents not opening

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#769]
I the last week or two I've noticed that when I do a document merge I no longer get the option to just open the document. I always get prompted to save the file.
This has happened on Windows and two flavours of Linux with Firefox and Brave!

**Comment by tim-pearce** [comment]
In Firefox there is an option to 'always ask' for a particular file type, but only for ones where you have used that file type before! Can't find such an option in Brave!

**Comment by tim-pearce** [comment]
Why do they do these things! I found this [https://www.mozilla.org/en-US/firefox/98.0/releasenotes/](url)

**Comment by tim-pearce** [comment]
Found this that tells you how to restore the old behaviour [https://www.askvg.com/tip-restore-classic-download-confirmation-prompt-in-mozilla-firefox/](url)

**Comment by tbar0970** [comment]
Thanks for sharing your findings :)
