### ISSUE TITLE
"Illegal mix of collations" error on roster assignments page

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#778]
Every time I try and access display roster assignment, edit roster assignments or define rosters views, it is coming up with an error "An error occurred. Please contact your system administrator for help."

On the define roster views, it also has the definition box: A roster view is a collection of roster roles, used when editing or displaying roster assignments. A roster role can be included in several roster views. You might like to create views such as "morning congregation" or "all preachers" and also the "Add View" link at the top right.

When I try to add a view, it comes up saying that the view is added but there is no way of seeing if it has or how to use the view.

Thank you for your help

![image](https://user-images.githubusercontent.com/32403035/161889476-0bec55c9-891a-44ed-8ccc-1423a64a4e54.png)

![image](https://user-images.githubusercontent.com/32403035/161889733-35555542-cec4-4f43-a486-bdde72465fac.png)

![image](https://user-images.githubusercontent.com/32403035/161889531-55087ca9-5a1c-4eb0-baac-5f5aa9b817a4.png)

![image](https://user-images.githubusercontent.com/32403035/161889630-c54d6c64-0794-4aff-a907-8ebca355761d.png)

**Comment by jefft** [comment]
The full PHP error is probably to be found in your webserver log file. Could you check there for clues?

**Comment by GlenMcDonald** [comment]
Thanks Jeff for pointing me in this direction.

I have checked the Apache error log and found the following errors (copied directly from the log file):

[Thu Apr 07 13:14:47.506238 2022] [php7:notice] [pid 4780:tid 1848] [client ::1:56336] SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'UNION' - Line 162 of C:\\xampp\\htdocs\\Jethro\\include\\jethrodb.php, referer: http://localhost/Jethro/?

[Thu Apr 07 13:16:00.703448 2022] [php7:notice] [pid 4780:tid 1856] [client ::1:56347] SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'UNION' - Line 162 of C:\\xampp\\htdocs\\Jethro\\include\\jethrodb.php, referer: http://localhost/Jethro/?view=rosters__display_roster_assignments

[Thu Apr 07 13:16:18.292564 2022] [php7:notice] [pid 4780:tid 1848] [client ::1:56348] SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'UNION' - Line 162 of C:\\xampp\\htdocs\\Jethro\\include\\jethrodb.php, referer: http://localhost/Jethro/?view=rosters__edit_roster_assignments

Each of these errors coincided with the time when I tried to access each of the “Display Roster Assignments”, “Edit Roster Assignments” and “Define Roster Views” Tabs.

I have checked the table for Roster views and there is data there, even though it doesn’t appear in the view (the heading View Name and Roles appear but no information under it.)

Also when I check for updates on Jethro, it states that I am running 2.31.1 but V2.31.2 is available. When I follow the link for the upgrade, it states the 2.31.1 is the latest version. I have also googled for the 2.31.2 but cannot find it.

Thank you for any help you can provide.

Glen

**Comment by jefft** [comment]
Databases are initially configured to store text in a certain encoding and with a certain collation. It appears that when creating or populating your database, somehow this is broken. This is generally a "wipe the database and try again from scratch" situation.

I thought modern MySQLs defaulted to utf8, and so should just work. Did you import this Jethro data from someplace else?

If you can connect to MySQL to issue SQL commands, you could check the relevant table's encoding and collation with:
```
MariaDB [jethro]> SELECT CCSA.character_set_name, T.table_collation FROM information_schema.`TABLES` T,        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation   AND T.table_schema = "jethro" and T.table_name='roster_view_role_membership';
+--------------------+--------------------+
| character_set_name | table_collation    |
+--------------------+--------------------+
| utf8mb4            | utf8mb4_unicode_ci |
+--------------------+--------------------+
1 row in set (0.001 sec)
```

It would also be interesting to see the output of the SQL (roughly) that the rosters table invokes:
```
(SELECT rvrm.order_num     as order_num,
        rr.id              as role_id,
        rr.title           as role_title,
        NULL               as service_field,
        rr.congregationid  as congregationid,
        rrc.name           as congregation_name,
        rr.volunteer_group as volunteer_group
 FROM roster_view_role_membership rvrm
          JOIN ( roster_role rr LEFT JOIN congregation rrc ON rr.congregationid = rrc.id )
               ON rvrm.roster_role_id = rr.id)
UNION
(SELECT rvdi.order_num      as order_num,
        NULL                as role_id,
        NULL                as role_title,
        rvdi.service_field  as service_field,
        rvdi.congregationid as congregationid,
        dic.name            as congregation_name,
        NULL                as volunteer_group
 FROM roster_view_service_field rvdi
          JOIN congregation dic ON rvdi.congregationid = dic.id)
ORDER BY order_num;
```

**Comment by tbar0970** [comment]
Thanks for raising that question about 2.31.2, which needed to be published and now is.
But upgrading to 2.31.2 won't resolve this issue.  Jeff's diagnosis above is useful.

**Comment by tbar0970** [comment]
It sounds to me like, somehow, the roster_view_role_membership table and the roster_view_service_field tables (or fields within them) have different collations.  I'm not sure how this would come up.  It'd be useful to know if you've recently migrated servers?

**Comment by GlenMcDonald** [comment]
No migration. It was a fresh install

**Comment by tim-pearce** [comment]
It is possible for there to be a problem with the SQL if the queries that make up the UNION have columns without identical data types.
Since no one else seems to have the problem it is more likely something in the database.
Here is an article about how to fix such a problem [https://bobcares.com/blog/mysql-dump-error-illegal-mix-of-collations-how-to-resolve/](url)
The recently added tables are created with utf8 encoding but there are multiple possible utf8 encodings available. Maybe the default for your database is different to what was created earlier for Jethro.

**Comment by GlenMcDonald** [comment]
Thank you for your advise.

Somehow there were a number of tables that were generated using uft8_general_ci which I am guessing has caused the conflict.

Through phpMyAdmin I have been able to change the Collations of all tables and columns to utf9_unicode_ci which seems to have rectified the issue (we will see as I populate the rosters!)

Thanks again for your support and help.

Glen

**Comment by tbar0970** [comment]
Glad to hear you got it sorted out. It remains a mystery how there could be different collations in those tables in a fresh install. Please re-open if this recurs or you find further clues.

**Comment by GlenMcDonald** [comment]
Thanks Geoff

I ran the first SQL results:

***@***.***


Results of the second SQL request:

***@***.***

I hope this helps

Thanks again for all your help

Glen
