### ISSUE TITLE
How to use / access planned absence

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#780]
I am trying to work out how to use / access planned absence. I am assuming that this is related to rostering.

Thank you for your support

**Comment by tbar0970** [comment]
Thanks for asking. Yes, it's related to rostering.  (And for docs on rostering in general, see https://easyjethro.com.au/support/rosters/)

You can add a planned absence in the control centre via a person's rosters tab.
In the members area, people can also add planned absences for themselves via the rosters page.
Eg "Tom is away on holiday 1 April - 1 May 2022".

When you go to edit roster assignments, Jethro will check which of your volunteers have planned absences for each date.  Volunteers with planned absences will be marked "absent" and be disabled in the roster's dropdown boxes, so you can't assign them to duties while they are absent.
