### ISSUE TITLE
Adding planned absense in the drop down list for roster choices

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#781]
A request for future development - when you choice the drop down list for populating the roster, it would be helpful if it could be indicated who is planned to be absent. Unless I am doing something wrong, it doesn't indicate this until after you have chosen the person and saved the rostered roles.

**Comment by tbar0970** [comment]
This is the current behaviour.
If Joe Bloggs has a planned absence 1 April - 15 April,
then when rostering for 7 April,  in the dropdown his name will be greyed out with the label "absent".
