### ISSUE TITLE
php 8.1

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#790]
Working on improvements to document merge I have been bitten by deprecations in php 8.1 particularly builtin function that will no longer accept nulls in place of a string.
In particular strpos, str_replace and htmlspecialentities.
This last one had me baffled as it pointed to line 122 of general.php even when the code was moved. Eventually I realised that the exception report, complete with all the formatting had been written to service notes in the database.
Some of these issues will be resolved when I submit my document merge changes/

**Comment by tim-pearce** [comment]
I've done a run through my dev system and so far have only come across 
Line 16,19 & 37 of File .../include/paginator.class.php
  Implicit conversion from float 65.44444444444444 to int loses precision
Changing 
$this->_slice_size - 1 
  to 
round($this->_slice_size - 1)
fixes the issue.
Using round() is consistent with the existing code on line 40.

**Comment by jefft** [comment]
Yes, Ubuntu 22.04 defaults to PHP 8.1, the Jethro installer page looks sad:

![image](https://user-images.githubusercontent.com/205995/189380656-6397292c-5b5a-4032-865a-461e1de1f0c2.png)

**Comment by tbar0970** [comment]
Fixed in #2cc6f45
