### ISSUE TITLE
Contact list to DOCX does not work

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#795]
At least not for me either on UBuntu server or my Artix dev machine.

I suggest using PHPWord as suggested at [https://code-boxx.com/convert-html-to-docx-using-php/](url). This also allows conversion to ODT and RTF.

Further to this I suggest adding a templating system for the contact list where users can create modified versions of the code to format the entries. In this system the template generates the HTML which is displayed on the screen or downloaded as HTML, DOCX, ODT or RTF. 

The template probably needs to be PHP so would require knowledge of PHP coding. Alternately the templates could system supplied only and only people like you and I would create new templates if people request them.

**Comment by tbar0970** [comment]
Working on my server.  You're on PHP7 ?

**Comment by tbar0970** [comment]
Anything in the error log?
Feature requests noted, but getting the current features functional on PHP7 will be a higher priority job.

**Comment by tim-pearce** [comment]
Hadn't considered the PHP 7 (& 8) possibility.
The messages are in the generated files. Trying to open in Word just says they are corrupt but Libreoffice recognises them as plain text so you get to see the contents.
I (think) I created the first with my dev system which is PHP 8 and the other on my production system which is PHP 7 (Ubuntu)
[Contact-List.docx](https://github.com/tbar0970/jethro-pmm/files/8937351/Contact-List.docx)
[Contact-List2.docx](https://github.com/tbar0970/jethro-pmm/files/8937354/Contact-List2.docx)

Saving the contact list to DOCX has never worked for me, but it's something I haven't been using.

**Comment by tim-pearce** [comment]
The error log from my dev system 
[error_log.txt](https://github.com/tbar0970/jethro-pmm/files/8937391/error_log.txt)

**Comment by jefft** [comment]
Contact List docx export doesn't work for me either, using Jethro 2.31.2 and php7.4-fpm. The stacktrace looks quite different though (see 
[stacktrace.txt](https://github.com/tbar0970/jethro-pmm/files/8945924/stacktrace.txt)).

**Comment by tbar0970** [comment]
@tim-pearce 's errors those look like errors related to PHP8 strict typing. I suspect jethro would fall afoul of those in many places.
@jefft 's errors are https://github.com/PHPOffice/PHPWord/issues/927
I will pull in a patch for that.  (I think we need to stick with that version of phpword for now to preserve php 5.3 compatibility a bit longer).
