### ISSUE TITLE
Bulk add users to group

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#806]
Currently, bulk-populating a new Group with users is a very slow person-by-person process:
![image](https://user-images.githubusercontent.com/205995/180039295-15f8db9f-0908-410b-8e27-3cb863325444.png)

Jethro rarely has an unmanageable number of users. Could we just list all users in a multi-select box (generously sized), let the user shift-click users they want to add, and bulk-add all those users at once?

**Comment by tbar0970** [comment]
Not sure about this one.

As it stands, it does support bulk-add in one sense:  You can keep searching and adding persons within that same modal, before clicking the "add members" button to add them all to the group.  So you don't have to reload the page for each person.

Systems often accumulate a few hundred persons pretty fast, so the multi-select box would get pretty huge.

Also, if you want to browse through persons and select some of them to add to a group, we can browse them in persons>list all, or persons> reports, tick some checkboxes, and use the add-to-group bulk action.  (Maybe it would be helpful to put a link to this from the modal shown above, to show the alternative approach).

**Comment by jefft** [comment]
> Also, if you want to browse through persons and select some of them to add to a group, we can browse them in persons>list all, or persons> reports, tick some checkboxes, and use the add-to-group bulk action. (Maybe it would be helpful to put a link to this from the modal shown above, to show the alternative approach).

I hadn't noticed that 'add to a group' option. Nice, thanks!

![image](https://user-images.githubusercontent.com/205995/180767743-0a55671d-a27e-47b3-a4db-764b04b10c09.png)
