### ISSUE TITLE
Where is 2.32?

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#819]
When I check for updates it says 2.32 is available (and I see some issues here for it) but when I follow the link it's not there!

**Comment by jefft** [comment]
Hi Tim,

2.32.0 is [tagged](https://github.com/tbar0970/jethro-pmm/tags) but has been discovered to suffer from a horrible bug, #818, so may not be formally released. If you comment out this line you should be fine:

https://github.com/tbar0970/jethro-pmm/blob/cf9feff346df0abcacd53574d477da2acdd9190c/include/init.php#L64

**Comment by tbar0970** [comment]
The shorter answer is:  It's been tagged but not yet publicly released. We run it on some systems we manage before releasing it into the wild. Will come out in a few days.
