### ISSUE TITLE
Error adding user to group when person lacks 'Persons & Families - add/edit/group' permission

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#82]
Our band leader tried to add a new member to the 'Band' group in the usual manner (Groups -> Search -> click group -> click "Add members" -> find person -> click "Add Members"). This resulted in a message "Error: Undefined view":

![jethro_error](https://cloud.githubusercontent.com/assets/205995/10445263/dc0faed8-71bb-11e5-9a7b-1896d9d1cb28.png)

(url: https://jethro.coastec.net.au/?view=_edit_group&action=add_member&groupid=55)

The band leader has a set of permissions that includes the _Groups - add/edit/delete_ permission:

![perms](https://cloud.githubusercontent.com/assets/205995/10445325/af63730a-71bc-11e5-93cf-c7b92776b282.png)

After some experimenting, it turns out that lack of _Persons & Families - add/edit/group_ permission is the culprit. To replicate:
- Pick a user
- Remove their _Persons & Families - add/edit/group_ permission
- Log out and back in again as that user (permissions are cached otherwise)
- Try to add a member to a group

So there is some confusion: which permission is required to manage group memberships?
- I would actually prefer if only the _Groups - add/edit/delete_ permission were needed. Our band leader shouldn't be able to add families, but should be able to add members to 'his' group. Thus the "Families" permission is more powerful (to my mind) than the "Groups" permission, and it would be nice to be able to grant only a lesser permission. 
- However if you decide that both _Groups - add/edit/delete_ and _Persons & Families - add/edit/group_ permissions are required, then the "Add Members" button should be hidden from users lacking either. Also the "Remove" links should be hidden when viewing a person with groups, as it is inconsistent that one can remove a group from a user but not re-add it.

**Comment by tbar0970** [comment]
Hi Jeff
Thanks for the typically thorough bug report!
The intention is that you only need the "persons & families - add/edit/delete" permission to add or remove people from a group.  A person's group memberships are seen as a property of the person.
The "groups - add/edit/delete" permission is for creating groups, changing their properties or deleting them.
The idea is that the latter is more of an administrator type action.

So, the controls for adding/removing persons from a group should only be shown if the user has "Persons & Families - add/edit/group" permissions.  I'll get this fixed.

**Comment by jefft** [comment]
Sure, thanks.

I can put this in a new feature request if you like, but in that case may I suggest that a new permission, "Groups -manage members", i.e. changing:

![jethro-current](https://cloud.githubusercontent.com/assets/205995/10474367/9b565f24-7281-11e5-93aa-0e732952fa23.png)
to:
![jethro-proposed](https://cloud.githubusercontent.com/assets/205995/10474366/9b529a1a-7281-11e5-8632-f47ad7018872.png)

Rationale:
- managing group memberships is a frequent operation, and frequently delegated to non-administrators. In our case we have  dozens of home group leaders and ministry leaders, all of whom may need to keep their Jethro groups up-to-date. We don't want these dozens of people to be able to edit person records OR group records - just memberships. 
- currently it's pretty unintuitive that the "Groups - add/edit/delete" permission does NOT let you edit the group memberships. Editing memberships is what "editing a group" primarily means to me.
- separating out a "manage members" permission makes the *Persons & Families - add/edit/delete* nice and symmetrical with *Groups - add/edit/delete*.

**Comment by tbar0970** [comment]
I've resolved the original problem here, and the enhanced permissions structure is in feature request #339
