### ISSUE TITLE
Misleading 'Email sent' message for members that don't have a registered email

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#821]
When someone goes to the /members section, and creates themselves an account, they see this page:

![image](https://user-images.githubusercontent.com/205995/187113729-ac6530cf-5136-43cb-afe1-ac1c1c2f72d9.png)

If the email address entered is unknown to Jethro, no email gets sent. The first two sentences are filthy lies. It's true, the third sentence explains this, but who has the patience to read three whole sentences?

Could the text be reworded?

```
Your password reset request has been received.
----------------------------------------------

If your email address is known to Jethro, you will be emailed a link to reset your password. If you do not receive an email, please:
- check your junk or spam folders
- try another email address you might be registered in Jethro as
- contact the Jethro administrator, %SYSADMIN_HREF%
```

**Comment by jefft** [comment]
The context: there are many SaaS apps where users self-register, and are then granted fuller permissions as required. It would be completely reasonable to assume this of Jethro: let users register themselves (on /members), and then grant them staff-level permissions are required.
But as we know, that's not how Jethro works (although perhaps it should - #264).

This 'Email sent' page is Jethro's first and only opportunity to tell people that they can't self-register.

**Comment by tbar0970** [comment]
Yeah good suggestion about changing the wording.
