### ISSUE TITLE
Documentation of Jethro PMM minimum system requirements

### ISSUE THREAD

**Issue by andrewfn** [tbar0970/jethro-pmm#83]
Having failed to install Jethro on one of my linux servers I wondered if maybe it did not meet the minimum system requirements. I have searched everywhere I can think of to find this documented. Maybe it could go into README.md? I am using:
- MySQL 5.1.40
- PHP 5.3.0
- Apache 2.2.3

**Comment by tbar0970** [comment]
Hi Andrew
You're right - it would be good to have those requirements in the readme. I'll add them.
The versions you mentioned will be fine for Jethro.  If you're having trouble with an installation it would be worth having a look at your httpd and php error logs.
Tom

**Comment by tbar0970** [comment]
Done
