### ISSUE TITLE
'Other' roster assignment feature doesn't enforce planned absences

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#831]
Generally, if someone has a planned absence on a certain date, Jethro won't let you assign them to anything for that date.
BUT if I have a roster role with a volunteer group, so that Jethro gives me a dropdown box when editing assignments, and I choose 'other' down the bottom and choose somebody that way, it does NOT stop me from choosing someone with a planned absence.  After I save, the roster shows me the exclamation-mark warning that the allocated person has a planned absence.
This should be fixed.

And possibly there should also be a way to override a planned absence - "yes I know they have a planned absence but roster them anyway", OR "assign them anyway and delete the planned absence for this particular date". That's more complex.

**Comment by tim-pearce** [comment]
I don't see the current behaviour as a problem unless it refuses to add them to the roster. Isn't this a way of overriding a planned absence?

**Comment by tbar0970** [comment]
If there's a planned absence, the current inteded behaviour is that jethro SHOULD refuse to add that person to the roster on that date.  But there's a gap in the enforcement of this, described above.

Ability to (knowingly) override a planned absence would be a new feature.
