### ISSUE TITLE
Deleting a congregation can leave orphaned services, triggering errors

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#834]
You can delete a congregation if if has no members.
But there seems to be no foreign key to either clean up services that belong to that congregation (ON DELETE CASCADE) or prevent the deletion of a congregation with services (ON DELETE RESTRICT).
This results in fatal errors on the edit-run-sheet page as it tries to look up the congregation for services that dont' exist.

Ways to fix:
* Easiest: simply add a foreign key with ON DELETE CASCADE to nuke services when a congregation is deleted.  However this might delete historical records which are worth keeping.
* Extension:  add a warning message that this will happen
* More elaborate solution: Provide a way to "retire" congregations so they can still exist and house their historical services.

Related: #722 - if we introduce service categories we should consider how to handle deleting/archiving a service category

**Comment by tbar0970** [comment]
Thought bubble:
Currently a congregation with its meeting_time set is treated as "services enabled"
We could add another field/flag which represents "persons enabled"
A congregation which has neither "services enabled" nor "persons enabled" is effectively archived - it doesnt' appear anywhere except the congrergations page.
This might be the easiest way to implement https://github.com/tbar0970/jethro-pmm/issues/722 - you could have some 'congregations' which are only used for services, not for containing persons.

**Comment by jefft** [comment]
To replicate:

- Create a new congregation
- In Services -> List All and click 'Edit Schedule'. In the new congregation column, add a Title for the first week. This defines a service for that week.
- Back on the Services page, you will now see a '+' icon in the new congregation's column. Click this to create a run sheet.
- Add an item to the runsheet. It doesn't matter what (a song, etc). Click Save.
- Under Admin -> Congregations, delete the congregation
- Return to Services -> List All. You will get 'An error occurred. Please contact your system administrator for help.' In the logs we see:

```
PHP message: Call to a member function releaseLock() on null - Line 84 of /home/jethro/code/2.33.0/app/views/view_8_services__1_list_all.class.php
```
The Services -> List All page also breaks with:
```
PHP message: Call to a member function getValue() on null - Line 303 of /home/jethro/code/2.33.0/app/views/view_8_services__1_list_all.class.php
```
Clicking 'Edit Schedule' and saving gets us back to normal for now, but there are other codepaths that break.

**Comment by jefft** [comment]
Found this in the wild. A Jethro instance had a congregation deleted that had services + runsheets attached. Now defining a run sheet (i.e. clicking '+' on a defined service) breaks. Clicking 'Copy from previous' results in an error:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/4a763896-0e48-4580-8012-e9f1d9af6718)

The stacktrace:

```
BACKTRACE:
Array
(
    [0] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/views/view_8_services.class.php
            [line] => 415
            [function] => toString
            [class] => service
            [type] => ->
        )

    [1] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/views/view_8_services.class.php
            [line] => 131
            [function] => printRunSheetEditor
            [class] => View_services
            [type] => ->
        )

    [2] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/include/system_controller.class.php
            [line] => 188
            [function] => printView
            [class] => View_services
            [type] => ->
        )

    [3] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/templates/main.template.php
            [line] => 113
            [function] => printBody
            [class] => System_Controller
            [type] => ->
        )

    [4] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/include/system_controller.class.php
            [line] => 130
            [args] => Array
                (
                    [0] => /home/jethro/code/2.33.0/app/templates/main.template.php
                )

            [function] => require
        )

    [5] => Array
        (
            [file] => /home/jethro/code/2.33.0/app/index.php
            [line] => 58
            [function] => run
            [class] => System_Controller
            [type] => ->
        )

)
```
This SQL will identify Jethro instances where the 'create runsheet' action will break:

```sql
select distinct service.id, congregationid, date from service JOIN service_item si ON servi
ce.id = si.serviceid  LEFT JOIN congregation ON service.congregationid=congregation.id WHERE service.date>date_sub(now(
), interval 1 year) and congregation.id is null ;
```

A quick and ugly fix to get the `toString()` method working:
```php
--- a/app/db_objects/service.class.php
+++ b/app/db_objects/service.class.php
@@ -204,7 +204,7 @@ class service extends db_object
        function toString($long=FALSE)
        {
                $cong = $GLOBALS['system']->getDBObject('congregation', $this->getValue('congregationid'));
-               $congName = $cong->getValue($long ? 'name' : 'long_name');
+               $congName = $cong ? $cong->getValue($long ? 'name' : 'long_name') : "<deleted>";
                if (!strlen($congName)) $congName = $cong->toString();
                $date = $long ? date('jS F Y', strtotime($this->getValue('date'))) : $this->getFormattedValue('date');
                return $congName.' Service on '.$date;
```

**Comment by tbar0970** [comment]
I've implemented the idea in https://github.com/tbar0970/jethro-pmm/issues/834#issuecomment-1515807640

Congregations can only be deleted if they have no persons, no services, no account restrictions.  But they can now be made 'inactive' by unticking all the boxes so they don't hold persons, record attendance, or hold services.

It may not make much sense for a congregation to support attendance if it doesn't accept (new) persons. But I've left it for now.

As mentioned above, this effectively implements #722 because a congregation can now function purely as a container for services.
