### ISSUE TITLE
Editing family details gives fatal error: Allowed memory size of  bytes exhausted

### ISSUE THREAD

**Issue by brett-mcgirr** [tbar0970/jethro-pmm#836]
Hi,

When updating a family name, we're getting an error saying allowed memory size exhausted. The code in question is the following:

File: include\db_object.class.php
Line: 358

356 $user = $GLOBALS['user_system']->getCurrentPerson();
357 $now = time();
358 $this->values['history'][$now] = 'Updated by '.$user['first_name'].' '.$user['last_name'].' (#'.$user['id'].")\n".implode("\n", $changes);

$now is set to some unix time, e.g. 1670462680 and when it's used as an index into the string $this->values['history'], PHP is trying to allocate a string that is 1,670,462,680 characters long which is too much. 

I'm not 100% sure what the intention of the $now value is, but might the following code be the way forward?

358 $this->values['history'] = 'Updated by '.$user['first_name'].' '.$user['last_name'].' (#'.$user['id'].")\n".implode("\n", $changes);

Cheers.

**Comment by tbar0970** [comment]
Possibly related: https://github.com/tbar0970/jethro-pmm/issues/825

**Comment by brett-mcgirr** [comment]
It's a new-ish system that's been going since mid-2021, and has just been upgraded from v2.30.1 to v2.32.0. Most person/family records would have no edits against them however, so perhaps the empty history is coming back as an empty string rather than an empty array.

It hasn't been transferred between hosts.

**Comment by tbar0970** [comment]
Thanks for the info.  Will investigate what leads to this scenario and add some resilience to it.

**Comment by brett-mcgirr** [comment]
Thanks, that would be great. I've also done a bit of digging which might help.

In family.class.php, the save() function loads the family members to see if it needs to update each member's family_name (line 425). However, the rows returned do not have the history column loaded since the db_object.class.php specifically excludes type=serialise fields (line 975). Thus the person object has an empty string for the history which doesn't become an array.

I'm new to the code and PHP but would guess that the exclusion on line 975 is there for a reason (performance?) and is used extensively throughout. However, adding the column in person.class.php seems less likely to break everything and fixes the issue. I'll add a PR to show you what I mean but it's still possible it's the wrong fix.

**Comment by tbar0970** [comment]
Thanks, your analysis above is spot on.  I decided to fix it a different way, which retains the performance benefits of not fetching the history in bulk-fetch scenarios.
