### ISSUE TITLE
2.13.1 install bug: missing database updates

### ISSUE THREAD

**Issue by andrewfn** [tbar0970/jethro-pmm#84]
When trying to do a fresh install with 2.13.1 there is an error inserting into the `_person` table because the `feed_uuid` column is not there.
This field was added by the script: `2015-upgrade-to-2.12.sql` for those upgrading from earlier versions, but is not actually present in the 2.13.1 release. There is also a view that needs updating.
The updates needs to be added to:
- `db_objects/person.class.php`
- `include/installer.class.php`

Once I had modified those two files by hand to include the contents of `2015-upgrade-to-2.12.sql`, Jethro installed successfully.

**Comment by tbar0970** [comment]
Thanks for reporting this, and sorry you had this hassle while installing.
