### ISSUE TITLE
Editing a staff account results in loss of custom fields

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#845]
There looks to be a nasty bug in 2.32.0+ (not present in 2.31.2) that results in data loss.  If a Person has an associated staff account, and you edit that staff account (e.g. to adjust their permissions, or mark them active/inactive), then all that person's custom fields are lost.

To replicate:

1) Add a custom field if none exists yet. E.g. here I've got a 'MultiCF' field:

![image](https://user-images.githubusercontent.com/205995/209763578-a1ff2d12-d22f-46e8-a959-9c0c1ff000e5.png)

2) On a Persons page for someone with an associated staff account, set the custom field. E.g. here the value is 'bar':

![image](https://user-images.githubusercontent.com/205995/209763618-e39c0c8a-1aff-414c-9e1c-2d09018371dd.png)

3) In Admin -> User Accounts, find the account and 'edit' it. This is the first sign of a problem: the custom field doesn't show, whereas previously (in 2.31.x) it did:

![image](https://user-images.githubusercontent.com/205995/209763665-6968233c-41c6-4498-afd9-14fa0186d265.png)

4) Fill in your 'current password' and click 'Update Account'. 

5) View the Person record. You'll note the custom field is gone. The History shows it has been blanked out:

![image](https://user-images.githubusercontent.com/205995/209763687-92c77014-2203-4c5f-b42b-a836c9ce7d9e.png) 
 ![image](https://user-images.githubusercontent.com/205995/209763723-da825567-7284-41ee-9fcb-b3c1b2df41a0.png)

**Comment by jefft** [comment]
As for the bug cause: I reckon it's the missing custom fields on the edit_user_account form. Jethro 2.31 showed all custom fields. In 2.32 only a handpicked 5 show. Perhaps, when submitted, the edit_user_account code sees "hm, no custom fields. Blank them all!" 

The change may have originated in https://github.com/tbar0970/jethro-pmm/commit/c7301ca16684254407a746509ddc7586b643e6f3 where the $fields variable changed from containing all fields, to containing just 5.

**Comment by tbar0970** [comment]
THanks for reporting. Leaving custom fields out of that form was a deliberate change (it all got too long).
