### ISSUE TITLE
initial user account not setup in DB on install

### ISSUE THREAD

**Issue by awucweb** [tbar0970/jethro-pmm#852]
Hi Folk

I have been trying to install Jethro v2.32.0 a few times now and have followed the setup however after filling out the install details the initial user account is not setup in DB as the Staff member table is empty.

After completing the install form the db is populated but I get:

_An error has occurred. Your Jethro system has not installed successfully. You will need to drop and re-create the mysql database before trying again._

On refresh

_Fatal error: This system has no user accounts - it has not been installed properly in /home/jszxrrbx/public_html/pmm/include/user_system.class.php on line 161_

Can't quite work out how to insert a user into the table.

Any pointers, thanks

**Comment by jefft** [comment]
Have you checked your webserver error logs? Usually an `error.log` file somewhere in `/var/log/apache2` or `/var/log/httpd`.

**Comment by awucweb** [comment]
> Have you checked your webserver error logs? Usually an `error.log` file somewhere in `/var/log/apache2` or `/var/log/httpd`.

Thanks Jefft unfortunately none I can see

**Comment by jefft** [comment]
`error.log` (or `error_log`) is usually in the same directory as `access.log`, which should definitely be present -- perhaps search for that. Are you using a PHP hosting provider? Perhaps they make web server logs available through a web interface somewhere?

**Comment by awucweb** [comment]
Thanks Jefft found the file but no error from when I did the install. Seems to have failed silently.

Any tips on how to insert a user into the dB

I'll try a local install in the next few days.

**Comment by jefft** [comment]
You could try creating a `test.php` file, in the same directory containing `index.php`:
```
<?php
error_log("Test to errlog");
phpinfo();

```
Then in the browser, if you request `<url>/test.php` you should see lots of PHP diagnostics (which could be useful), and in the `error.log` file (wherever it is) will contain something like:
```
[Tue Jan 24 22:07:14.453855 2023] [proxy_fcgi:error] [pid 985394:tid 140314874914560] [client 127.0.0.1:37096] AH01071: Got error 'PHP message: Test to errlog'
```

Then at least you've identified where errors _should_ appear.

**Comment by awucweb** [comment]
Fantastic foud the correct error_log file so here it is

Undefined index: my_current_password - Line 365 of /home/<user>/public_html/pmm/db_objects/staff_member.class.php

**Comment by jefft** [comment]
Ah, that would be #828

I don't know a nice workaround, sorry. I suggest redeploying the [jethro zip from the latest commit](https://github.com/tbar0970/jethro-pmm/archive/master.zip), which is pretty stable.

**Comment by awucweb** [comment]
Thanks Jefft - I hadn't seen that one so will give the latest commit a go

**Comment by awucweb** [comment]
ok so with the master it looks more like Jethro with the yellow background as previous version was just white and left align. This has the Congregations expanding as indicated whereas previous one just ad a single text box.

Entered all the info then got the error as indicated in the staff_member.class file

Jethro PMM Installer
 Password for current user was incorrect. Account details not saved
Installation Complete!
You can now [log in to the system](url) to start work.

**Comment by jefft** [comment]
Yes, I think that's to be expected as you reused the existing database. If you drop/recreate the database the install should have proceeded normally.

**Comment by awucweb** [comment]
Thanks Jefft - yes each time I deleted the database and recreated.

**Comment by tbar0970** [comment]
Sorry for the hassle here.  The next release, with #828 fixed, will come out within a few days.
