### ISSUE TITLE
error when trying to update service program

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#87]
Hi There, I'm trying to update the service program for next year, I got half way there, then it would say it was saved but wasn't then I started getting these errors (see below) any ideas? Thanks!

SYSTEM ERROR (NOTICE)

Undefined index: 2016-06-12

Show Details
Line 190 of File /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
            Array
(
    [0] => Array
        (
            [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
            [line] => 190
            [function] => _handleError
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                    [0] => 8
                    [1] => Undefined index: 2016-06-12
                    [2] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
                    [3] => 190
                    [4] => [Object/Array]
                )

```
    )

[1] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 100
        [function] => _processServiceCell
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
                [0] => 2
                [1] => 2016-06-12
                [2] => [Object/Array]
            )

    )

[2] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 67
        [function] => _handleProgramSave
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[3] => Array
    (
        [file] => /home/christch/public_html/jethro/include/system_controller.class.php
        [line] => 120
        [function] => processView
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[4] => Array
    (
        [file] => /home/christch/public_html/jethro/index.php
        [line] => 58
        [function] => run
        [class] => System_Controller
        [type] => ->
        [args] => Array
            (
            )

    )
```

)

SYSTEM ERROR (NOTICE)

Undefined index: 2016-06-12

Show Details
Line 191 of File /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
            Array
(
    [0] => Array
        (
            [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
            [line] => 191
            [function] => _handleError
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                    [0] => 8
                    [1] => Undefined index: 2016-06-12
                    [2] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
                    [3] => 191
                    [4] => [Object/Array]
                )

```
    )

[1] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 100
        [function] => _processServiceCell
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
                [0] => 2
                [1] => 2016-06-12
                [2] => [Object/Array]
            )

    )

[2] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 67
        [function] => _handleProgramSave
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[3] => Array
    (
        [file] => /home/christch/public_html/jethro/include/system_controller.class.php
        [line] => 120
        [function] => processView
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[4] => Array
    (
        [file] => /home/christch/public_html/jethro/index.php
        [line] => 58
        [function] => run
        [class] => System_Controller
        [type] => ->
        [args] => Array
            (
            )

    )
```

)

SYSTEM ERROR (WARNING)

Cannot modify header information - headers already sent by (output started at /home/christch/public_html/jethro/include/system_controller.class.php:248)

Show Details
Line 104 of File /home/christch/public_html/jethro/include/general.php
            Array
(
    [0] => Array
        (
            [function] => _handleError
            [class] => System_Controller
            [type] => ->
            [args] => Array
                (
                    [0] => 2
                    [1] => Cannot modify header information - headers already sent by (output started at /home/christch/public_html/jethro/include/system_controller.class.php:248)
                    [2] => /home/christch/public_html/jethro/include/general.php
                    [3] => 104
                    [4] => [Object/Array]
                )

```
    )

[1] => Array
    (
        [file] => /home/christch/public_html/jethro/include/general.php
        [line] => 104
        [function] => header
        [args] => Array
            (
                [0] => Location: https://christchurchmortdale.org.au/jethro/?view=services__service_program&congregations[0]=1&congregations[1]=2&congregations[2]=3&start_date_d=27&start_date_m=10&start_date_y=2015&end_date_d=27&end_date_m=12&end_date_y=2016
            )

    )

[2] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 180
        [function] => redirect
        [args] => Array
            (
                [0] => services__service_program
                [1] => [Object/Array]
            )

    )

[3] => Array
    (
        [file] => /home/christch/public_html/jethro/views/view_8_services__1_service_program.class.php
        [line] => 67
        [function] => _handleProgramSave
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[4] => Array
    (
        [file] => /home/christch/public_html/jethro/include/system_controller.class.php
        [line] => 120
        [function] => processView
        [class] => View_Services__Service_Program
        [type] => ->
        [args] => Array
            (
            )

    )

[5] => Array
    (
        [file] => /home/christch/public_html/jethro/index.php
        [line] => 58
        [function] => run
        [class] => System_Controller
        [type] => ->
        [args] => Array
            (
            )

    )
```

)

**Comment by tbar0970** [comment]
Hi, can you let us know what version of Jethro you're running.  Having had a quick look I think this might be resolved in the latest version.

**Comment by tbar0970** [comment]
@agoddard77 any update on this one?

**Comment by agoddard77** [comment]
Hi There, yes, I am running the latest version. I worked out that if I only ask to edit about 3 months at a time, the data sticks. The problem is only when I try to edit the service program/rosters for the whole year at the same time.

**Comment by tbar0970** [comment]
Today I managed to reproduce something like this and the result included a warning about the max number of POST fields, which needs to be adjusted in php.ini  I suspect that's what was causing this. 

Given the age of this issue I'm going to close it, but @agoddard77  feel free to comment if you're still experiencing the problem all these years later and we can perhaps help with adjusting php.ini to fix it.

![image](https://github.com/tbar0970/jethro-pmm/assets/2133676/312b409f-2421-4ec6-811e-9e6135f519c0)
