### ISSUE TITLE
version 2.33.0

### ISSUE THREAD

**Issue by GlenMcDonald** [tbar0970/jethro-pmm#873]
I have been running version 2.32.0, and checked for updates. It indicated that there is an update 2.33.0, however the link took me to https://github.com/tbar0970/jethro-pmm/releases which incidates that v2.32.0 is the latest version.

I clicked on "Tags" which then had a link 2.33.0. which I followed. I downloaded and installed v2.33.0 (it didn't seem to have any code to run on the database).

After installing v2.33.0, I then checked for updates in Jethro, which then indicated that I was running version "DEV" but v2.33.0 was available.

I notice that the v2.33.0 was uploaded yesterday. Is it just that my timing is that I have proceeded before it is ready, or have I made a mistake somewhere along the line.

I would love some advise of what I should do.

By the way, I am loving the database and am really appreciative of all the effort that so many people are putting into this to allow this.

**Comment by tbar0970** [comment]
Hi Glen
2.33.0 is only a draft version at this stage. That's why it doesn't yet appear on the releases page.
You must have downloaded the raw code from github, rather than a packaged ZIP file ?
Best plan would be to wait a couple of days then 2.33 will be released properly.
Tom

**Comment by GlenMcDonald** [comment]
Thanks Tom.

It must have been a coincidence thati just happened to check for am up date today.

Just so you are aware (not thati an concerned), it was the zipped file I downloaded.

More than happy to wait, it was just that was working on our data base this morning.

Thanks again for this.

Glen

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
