### ISSUE TITLE
iCal URLs only work if the public section is enabled

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#876]
In the members section, it's possible for users to 'Subscribe' to their roster:

![image](https://user-images.githubusercontent.com/205995/222991511-7498cdad-45a7-4efd-985c-499e2c17cb60.png)

This generates an iCal link:

![image](https://user-images.githubusercontent.com/205995/222991569-1a6187f9-eb87-4717-905a-19f6eeaac9c5.png)

However if the 'public' section of Jethro isn't enabled, the ical URL actually just contains a HTML error message:
```
 <p>The public area is not enabled for this Jethro System.  You may like to view the <a href="https://jethro/members">members area<a>
```

Feeding this URL to a calendar app will result in a validation error.

**Comment by tbar0970** [comment]
Sounds like we need to make this call an exception to the "public area enabled" setting.

**Comment by eb3nezer** [comment]
Hey @tbar0970. No I'm not using it.
