### ISSUE TITLE
Contact list: keep family all on one page

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#885]
In Families -> Contact List one can generate a church directory-style contact list, and then 'Download as..' DOCX.

It would be nice if family members could be kept together on a page, rather than being split on pagebreaks:

![image](https://user-images.githubusercontent.com/205995/226532153-cb0336c5-7e47-4724-8db8-650fbe727bb7.png)

**Comment by tbar0970** [comment]
PR is a good step in the right direction. Unfortunately solving this properly would be really tricky.  The way we currently assemble the DOCX doesn't have any awareness of where the page breaks are. For my part I just manually break pages as required before printing.

**Comment by tim-pearce** [comment]
The solution is to put the whole family within a table of just one cell then set the option to not split the table across page or column breaks. I can't find that option in Word 2010 but it honours the option when I create the document with Libreoffice.

![Screenshot_2023-03-22_00-38-28](https://user-images.githubusercontent.com/9509269/226772596-bf428541-6777-4480-9416-831c78a4c9d4.png)

Attached are the two documents I feed into the document merge process.
[Families2.docx](https://github.com/tbar0970/jethro-pmm/files/11035175/Families2.docx)
[Families2.odt](https://github.com/tbar0970/jethro-pmm/files/11035178/Families2.odt)
The only 'fiddle' was to change the font size of the line after the table to 0 and reduce the font size of the last line inside the table by 1.

**Comment by tbar0970** [comment]
>Attached are the two documents I feed into the document merge process.
Ah yes I can see this would work for a document merge.  But this issue is actually talking about the "contact list" page which does merging differently, with more sophisticated layout per family.

> The solution is to put the whole family within a table of just one cell then set the option to not split the table across page or column breaks. I can't find that option in Word 2010 but it honours the option when I create the document with Libreoffice.

The downside of this approach in the contact list, and the reason for not building it this way, was that by using nested tables you'd lose global control over the layout.  If you decide you want the mobile column a bit wider, currently you can adjust it and every family is affected because it's one big table. If it was separate nested table for every family, you'd have to manually adjust every one separately.

**Comment by tbar0970** [comment]
@jefft When photos are included, there is a cell containing the photo which spans all the rows in the family.  If cantSplit=true affects that cell, I think that will end up keeping the whole family together when photos are included.

**Comment by jefft** [comment]
@tbar0970 no, the photo cell is only in the first row. This is probably a separate bug:

![image](https://user-images.githubusercontent.com/205995/226791881-ac406e49-9569-46da-b736-4647558a256f.png)

![image](https://user-images.githubusercontent.com/205995/226791801-c31fcf32-2a6f-4b66-9c27-d44b7abda775.png)

**Comment by tbar0970** [comment]
Eww. Dunno what's happened there...

**Comment by tim-pearce** [comment]
> > The solution is to put the whole family within a table of just one cell then set the option to not split the table across page or column breaks. I can't find that option in Word 2010 but it honours the option when I create the document with Libreoffice.
> 
> The downside of this approach in the contact list, and the reason for not building it this way, was that by using nested tables you'd lose global control over the layout. If you decide you want the mobile column a bit wider, currently you can adjust it and every family is affected because it's one big table. If it was separate nested table for every family, you'd have to manually adjust every one separately.

Would a solution to that be to have some parameters to the process that can specify things like column widths, borders and padding?

**Comment by jefft** [comment]
> Would a solution to that be to have some parameters to the process that can specify things like column widths, borders and padding?

That probably is the only fix. There doesn't appear to be a way, in [PHPWord](https://phpword.readthedocs.io/en/latest/styles.html), just to say "keep these table rows altogether".

Manually specifying widths would be a cure would be worse than the disease I reckon. IMO this is a "close can't fix" bug. Keeping row contents from being split fixes the most egregious symptom.

**Comment by tim-pearce** [comment]
Document merge (or rather TinyButStrong which it uses) might provide a way.
I've been using 'simple'' blocks but it does allow for sub blocks. See [https://www.tinybutstrong.com/manual.php#html_block_subblock](url).
I had previously ruled it out for a contact list because I didn't think it could be used for sub-data.
Using TinyButStrong would allow 'shipping' of a standard template based on the current contact list but then be able to use your own template so it looks exactly as you want.

**Comment by tim-pearce** [comment]
I am currently working on a 'use document template' feature for the contact list.
At present I have a modal box (similar to the one I have for rosters) and a document_merge_contacts call based on document_merge.
All a bit rough and incomplete at this point.

**Comment by tim-pearce** [comment]
I've got it working. The code is pretty messy at present and I haven't figured out what to do about images - not sure if they are possible.
