### ISSUE TITLE
Record character count in SMS log file for calculating cost

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#888]
Jethro can send SMSes if configured, and logs them to `SMS_SEND_LOGFILE` (generally `sms.log`), truncated to 27 characters (for privacy I assume):
```
2023-03-15 11:34: jturner (#536) to 10 recipients: "Hello! You are rostered on ..."
2023-03-17 12:29: jturner (#536) to 8 recipients: "Hi, here is the finalised r..."
```
It would be useful to know the **total length** of the message in bytes, so that by dividing by 160 we can figure out how many SMS 'segments' the message was sent as, and thus the cost.

**Comment by tbar0970** [comment]
If the message includes characters not found in the GSM-7 encoding, calculating the number of message parts required becomes complex. Some SMS vendors may just drop (or corrupt) non-GSM-7 characters. Others will switch to another encoding in which case each message part will contain less than 160 chars. 

Providers such as Easy Jethro might just have to accept a certain level of imprecision for SMS billing.

**Comment by tbar0970** [comment]
OK, this is done.
The new log format looks like this:
```
["Timestamp","Username","RecipientCount","MessageLength","Content"]
["2023-06-02 17:44","tom",1,92,"In the beginning  God creat..."]
["2023-06-02 17:45","tom",1,9,"123456789"]
```
If Jethro sees the log file is completely empty, it writes the header line first.

> If the message includes characters not found in the GSM-7 encoding, calculating the number of message parts required becomes complex. Some SMS vendors may just drop (or corrupt) non-GSM-7 characters. Others will switch to another encoding in which case each message part will contain less than 160 chars.

This is actually not a problem because at the moment Jethro strips out all GSM-7 characters up front. I've verified that the character count for the log file is done after that.

**Comment by tbar0970** [comment]
@jefft let me know any thoughts

**Comment by jefft** [comment]
The new format is very nice and machine-readable. E.g. to count all SMSes sent:
```jq
jq --slurp 'map(.[2] | tonumber) | add' < sms.log
```

To help with migration (for anyone who cares to preserve their `sms.log` history), here is a script that reads `sms.log`, containing old, new or a mix of formats, and emits the content as new-style JSON lines:
```ruby
#!/usr/bin/env ruby
# Parse a Jethro sms.log containing either pre-2.34 lines or 2.34+ JSON lines, and emit the contents in 2.34+ JSON format

require 'date'
require 'json'

puts ARGF.read
  # Split on the year part of the timestamp, which is the only reliable indication of the start of a record (there may be newlines in message bodies). Handle old-style lines beginning directly with a date, and ["<date>",..."]
  .split(/\n(?=(?:\[")?\d\d\d\d-\d\d-\d\d)/)
  .map { |l|
    if l[0] == "[" then
      # ["<date>",...  record - it's already JSON, to parse into array
      JSON.parse(l)
    else
      # <date>,<person>,<count>,"<msg>"  record. Parse with regex, then normalize the timestamp
      # Note that <msg> might contain unescaped "'s, e.g. "Testing "one" two three"
      # <msg> often contains \r\n, hence the //m regex modifier so we can match on $ at the end reliably
      # Note that <person> may be blank, if the SMS is sent from a script. It also may contain whitespace
      #STDERR.puts "line: «#{l}»"
      date, person, count, msg = l.scan(/(\d\d\d\d-\d\d-\d\d \d\d:\d\d): (.*) \(#\d*\) to (\d+) recipients: "(.+)"$/m)[0]
      chars=nil  # New JSON format records the number of characters per SMS. The old format didn't record this, so insert blanks
      [DateTime.parse(date).iso8601, person, count, chars, msg]
    end
  }
  .map { |a|
    # Each line becomes a JSON string
    a.to_json
  }
  .join("\n")
```
