### ISSUE TITLE
Can't attach some files under documents

### ISSUE THREAD

**Issue by supagu** [tbar0970/jethro-pmm#89]
I can attach a .docx file under documents, but I cant upload a .ppt. I'm guessing there is some code that is limiting what extensions are accepted? Can we have control over this as I would also be able to upload powerpoints, videos, songs etc...

**Comment by tbar0970** [comment]
Hi there
I can attach .ppt files OK in my system.  It could be something to do with your server settings.  What result do you experience when you select a ppt file and try to upload it?

**Comment by supagu** [comment]
I select the file, it seems to show the uploading bar and then goes back to the documents page.
When I upload a docx file it does the same but gives me a message to say:
File "qwe.docx" saved
up the doc of the website, which I don't see with the ppt file.

**Comment by tbar0970** [comment]
Can you check the size of the files: it could be that the ppt file is
rejected by the server as too big, and possibly Jethro isn't explaining
that error properly.

**Comment by supagu** [comment]
Its about 10.2MB. If that is the issue, can that be configured to handle larger files in some config file?

**Comment by tbar0970** [comment]
The upload size is a server-wide setting, outside Jethro.  Many servers
have it set to 2-3MB by default, so I think that could be your problem.

**Comment by supagu** [comment]
Yes, that was the problem! Thanks

I increased the max file size using info from here:
http://stackoverflow.com/questions/7754133/php-post-max-size-overrides-upload-max-filesize
