### ISSUE TITLE
Adjustable order for "record attendance" form

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#890]
When marking attendance the [`ATTENDANCE_LIST_ORDER`](https://github.com/tbar0970/jethro-pmm/blob/master/db_objects/attendance_record_set.class.php#L17)  sort applies, which (by default) sorts by last name, then first name. That is fine, but for youth groups it might make more sense to sort by first name.

If this screen is ever redesigned, it might be better for first name and last name to occupy separate columns, and then make the whole table sortable with Javascript:

![image](https://user-images.githubusercontent.com/205995/229255120-152120da-2ac8-41e2-ab59-0fcbf73b3e84.png)

**Comment by tbar0970** [comment]
Also, the ATTENDANCE_LIST_ORDER setting can only (as of recently) be adjusted via the conf.php file. It could be good to allow user editing in the system_config page.  Probably just a selection of pre-set options eg first name then last name;  status then family name; status then first name etc.

**Comment by jefft** [comment]
Another "If this screen is ever redesigned" thought: it would be useful if the filtering by age bracket and status could be done in Javascript too:

<img width="410" height="311" alt="Image" src="https://github.com/user-attachments/assets/a89124ed-f0eb-461c-8637-566aad694725" />

Where one status swamps the others (here 'Other Congregation'), one could:
  1. Sort by first name
  2. Toggle on statuses A, B, C
  3. Mark attendance
  4. Toggle off A, B, C, toggle on D, E
  5. Mark remaining attendance
