### ISSUE TITLE
Reports by attendance rate give unexpected results

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#897]
I wanted to report on those absent from a group over a period of weeks.
I got no results.
I tried where present was > 1% and everyone showed as 100% present!
I captured the SQL (by hacking the getSQL function) and ran it in phpMyAdmin and get a zero result set.
I am totally confused on both counts!
What am I missing here?
It's very complex SQL at this point so that doesn't help either.

**Comment by s4069b** [comment]
For some years now I have had Jethro send an email each Monday afternoon with a list of those who have missed church for > 3 weeks in a row. The email is configured to enclude their email and mobile to make it easy to follow-up. Obviously Jethro relies on the accuracy of our attendance recording on a Sunday night or Monday morning. When a person is marked P or A things work nicely.  If they are left with ? next to their name in the attendance - that can mess with things. 

The report I use is configured like this: 
<img width="490" alt="Screenshot 2023-04-25 at 8 03 04 pm" src="https://user-images.githubusercontent.com/29622389/234244659-5cc1129c-49d7-4ba1-b922-7467043bbefe.png">

**Comment by tim-pearce** [comment]
I only use the 'P' so maybe my problem is the 'dreaded' null!
Still doesn't explain how Jethro can return a result but when I use the same SQL I get nothing!

**Comment by s4069b** [comment]
Yes, only using 'P' will give some challenges to building a report. I don't know about the SQL side of it. Never had a look.

**Comment by s4069b** [comment]
you might be able to use 'number of absences since last marked present' somehow?
<img width="572" alt="Screenshot 2023-04-25 at 8 22 29 pm" src="https://user-images.githubusercontent.com/29622389/234248851-635fd2b6-9a78-40d7-951b-51d3ea317886.png">

**Comment by s4069b** [comment]
Ignore that.. .it will still mean marking 'P'

**Comment by tbar0970** [comment]
> I only use the 'P' so maybe my problem is the 'dreaded' null!

Not "dreaded" but intentional :) 
In Jethro, "?" means "I'm not sure if they were present or absent".
So if somebody's attendance over three weeks is "P ? A" then it counts as a 50% attendance rate.

This is noted at the top of the "attendance statistics" page
![image](https://user-images.githubusercontent.com/2133676/234444701-17563f1d-195f-4cb4-ad46-0d44b542e24e.png)
but I'll add a note to the report-config page too.

> I captured the SQL (by hacking the getSQL function) and ran it in phpMyAdmin and get a zero result set.
Yep this is because Jethro sets the @current_user_id variable in MySQL before running any queries.
In phpMyAdmin you can prefix your query with something like
```
SET @current_user_id=1; 
```
assuming 1 is a high-privilege user.

**Comment by tbar0970** [comment]
> you might be able to use 'number of absences since last marked present' somehow?

This won't help if nobody is ever marked absent because the number of absences will always be zero. (question marks don't count as absences)

**Comment by tim-pearce** [comment]
'Dreaded' as in SQL NULs can trip one up!
I don't use the Attendance Statistics page, so never noticed that. I use Display Attendance and then generate a spreadsheet from that. In that context I've been able to work on the assumption that anyone not present is absent.
I think I would prefer something based around number of attendances in a given period. 
I might even look at creating such a thing based on the current function.

**Comment by tbar0970** [comment]
> I don't use the Attendance Statistics page, so never noticed that. 

Yes fair enough, it needs to be explained more prominently.

> I use Display Attendance and then generate a spreadsheet from that. In that context I've been able to work on the assumption that anyone not present is absent.

Sure.  But Jethro itself won't make that assumption.  For other users, the distinction between ? and A is important.

**Comment by tim-pearce** [comment]
On my test system I have added 'number of attendances' option'. I only had to add to person_query.class.php and it took less than an hour to add it.
![Screenshot_2023-04-26_12-53-54](https://user-images.githubusercontent.com/9509269/234473305-3e089ca7-4d4d-4655-a658-64ec5172df68.png)
