### ISSUE TITLE
How to delete a Service Component Library item

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#906]
Before I go importing songs I would like to know how to delete any 'mistakes'.
There does not appear to be a way!

**Comment by tbar0970** [comment]
The idea is that for service components that are no longer used, you edit it, go to the 'used by' field, and un-tick all the congregations. Then it doesn't appear anywhere.

**Comment by tim-pearce** [comment]
In my case I wanted to remove the couple of test song components I had added before importing songs across from Easyworship.
I was able to delete them in the database after resolving the foreign key constraints.
