### ISSUE TITLE
Importing CSV bug

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#91]
Ive imported my database from csv. 
However when trying to open the database in libreoffice I cant access the _people table as the dates are set to blank "0000-00-00 00:00:00" and office reports this as an error.

Is there anyway to fix this column to have all the value of the date/time of import?

**Comment by Gibbz** [comment]
Workaround for no via phpmyadmin
UPDATE _person SET created = '2015-11-12 00:02:33' 
UPDATE _person SET status_last_changed = '2015-11-12 00:02:33'

**Comment by tbar0970** [comment]
The import tool should apply all the default values for the persons and families it creates.

**Comment by Gibbz** [comment]
Ive noticed this may not be a csv issue after all.
When i make a new contact the default is "0000-00-00 00:00:00" for their "status_last_changed" which is causing the problem with libre office... 
So it may just be that the default there is wrong!

**Comment by Gibbz** [comment]
Found a work around for the crash in libre office

http://lists.freedesktop.org/archives/libreoffice-bugs/2014-December/241438.html
Add a new parameter to your connection string on the same line as your database
name :
?zeroDateTimeBehavior=convertToNull
