### ISSUE TITLE
Choose to display CCLI number and Key with Song Name in Roster View (service component)

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#918]
We have setup a 'roster view' which includes 'songs' (service component). This is used to generate a roster reminder to the musicians. We find that the CCLI number is helpful in communicating which song we're after (ie not just the song title). And a common question the musicians will ask is - 'what key is that in?' 

There is no option atm to include the CCLI number or Key in a Roster View when adding Songs as a service component.

Is this a feature others would use? I can have a mess around.

At the moment our work around is to add the CCLI number in brackets as part of the Song name. We also add the key in which we anticipate it will be played. But this workaround means we have two CCLI numbers and two keys for each song component - which will no doubt cause confusion down the track.

**Comment by tbar0970** [comment]
The "comments" field was designed to be the place for musical details like key, tempo, links to recordings and charts etc.  

Would it be sufficient to have the comments and CCLI number as a click-to-show ?  Or do you need it to show up in a printed roster etc?

**Comment by s4069b** [comment]
Thanks for the quick reply. I can see the "comments" field in the service component (ie if I pick a song, and edit it) - this would allow me to add the ccli and key in the comments for that song. However there's a double-up then, because there is already a spot to enter the CCLI number. 
Also, I can not work out how to have the comments for a song appear in the "roster view" where I have included songs as a 'service component' in the roster.

**Comment by tim-pearce** [comment]
I am hoping to add a document merge option to the service sheet view. This would give the ability to include whatever is available on your personalised version.

**Comment by tbar0970** [comment]
This issue is about how it shows up on a roster, not the service sheet.

**Comment by tim-pearce** [comment]
There would be multiple songs in a service, would there? So are we after a list of some song details to be available in the corresponding roster view? 
In the document merge for rosters that I've created I pull some details about the corresponding service in -
[roster.date] = 25 Jun 2023
[roster.format] = 
[roster.topic] = Sunday service
[roster.notes] = 
[roster.notes_cr] = 
[roster.comment] =

**Comment by s4069b** [comment]
Just after the ability to add CCLI number and Key alongside the Title of each song in a roster view - where the songs are added to the roster view as a service component. I have not had time to have a look at it yet.

**Comment by s4069b** [comment]
OK. I tried having a look at this but I'm very rusty. If someone could point me to the right area, that would be handy. 
I'm thinking perhaps the way forward/goal would be to add another option in the dropdown here:
".. All Songs including CCLI # and Comments" 
<img width="620" alt="Untitled" src="https://github.com/tbar0970/jethro-pmm/assets/29622389/6d8bcf0a-3a87-49ad-bb4a-a4c90b943392">

**Comment by tbar0970** [comment]
Yep you're on the right track.

However:  What I was trying to ask above is whether it would be work OK for you if the CCLI # and comments were shown in a little pop-up box when you click the song title.  If so, I'd be happy to include a link to that popup in the existing 'all songs' option, and avoid adding another option

**Comment by s4069b** [comment]
Now that I understand what you're saying - that would be perfect! Sorry for not getting it first time around.
Our setup at the moment is that the roster reminder includes a link at the bottom with a url (including the secret code https://jethro.ourdomain.com/public/?view=display_roster&secret=54321) meaning it's easy to open the public version of the roster. If the CCLI# and comments were shown as a pop-up in the public roster that would avoid clarifying emails etc.

**Comment by tbar0970** [comment]
Great.
Then don't worry about adding new options.
In db_objects/service.class.php, right at the end of the printFieldValue() function, is where the work needs to be done
```
				if (strpos($fieldname, 'comps_') === 0) {
					$compCatID = (int)substr($fieldname, 6);
					$res = Array();
					foreach ($this->getItems(FALSE, $compCatID) as $item) {
						$res[] = ents($item['title']);
					}
					echo implode('<br />', nbsp($res));
				} else {
					parent::printFieldvalue($fieldname);
				}
```

**Comment by tbar0970** [comment]
Suggested way to do the popup like this:
```
<i class="clickable icon-question-sign" data-toggle="visible" data-target="#tooltip1"></i>
<div class="help-block custom-field-tooltip" id="tooltip1">Choose the user responsible for acting on this note</div>
```

**Comment by s4069b** [comment]
Thanks for the pointers. 
I could not work out how to access the component id for each song in the 'printFieldValue()' function - so my hack/solution uses the song 'title' in the sql. *However 'title' may not be unique. 

Also, my knowledge of code is limited, so I have two sql calls in this hack/solution, where I'm sure one would do.

What I end up with is a popup for each song title, which reveals the ccli number and comments. (Song Keys can be stored in comments as well as other stuff). 

In order to preserve html stuff I also needed to replace nbsp($res) with $res
	
So... to the hack. 

In db_objects/service.class.php replace lines 375 to 385 with

`			default:
				if (strpos($fieldname, 'comps_') === 0) {
					$compCatID = (int)substr($fieldname, 6);
					$res = Array();
					foreach ($this->getItems(FALSE, $compCatID) as $item) {
				        $title = ents($item['title']);
                		$sql = 'SELECT ccli_number FROM service_component WHERE title = "'.$title.'"';
		                $ccli_number = $GLOBALS['db']->queryOne($sql);
 		                $sql = 'SELECT comments FROM service_component WHERE title = "'.$title.'"';
                        $comments = $GLOBALS['db']->queryOne($sql);
						$res[] = $title.'<i class="clickable icon-question-sign" data-toggle="visible" data-target="#tooltip1"></i>
<div class="help-block custom-field-tooltip" id="tooltip1">CCLI #: '.$ccli_number.'<br> Comments: '.$comments.'</div>';
					}
 			    	echo implode('<br />', $res);		
  							
				} else {
					parent::printFieldvalue($fieldname);    
				}`

**Comment by s4069b** [comment]
sorry... I can't work out how to enter code here, so I've attached a .dpf with the new function. 
[function.pdf](https://github.com/tbar0970/jethro-pmm/files/11855569/function.pdf)

**Comment by s4069b** [comment]
actually, ignore that... still working on it.

**Comment by s4069b** [comment]
OK the attached works. 
With the same caveats 
[function.txt](https://github.com/tbar0970/jethro-pmm/files/11855769/function.txt)
