### ISSUE TITLE
Reports: Show people NOT in any congregation or group

### ISSUE THREAD

**Issue by Gibbz** [tbar0970/jethro-pmm#92]
Some things id like to do on the system but lack the options:
1. Group by family - This should be the same as doing the family > contact list. But gives more controls over which people to show, and allows export as csv
2. Option to show people NOT in any congregation
3. Option to show people NOT in any group

These would be really handy additions!

**Comment by tbar0970** [comment]
Just a note that if you want to see people not in any congregation you can use a person report "that have congregation = [ don't select any options ]

**Comment by tbar0970** [comment]
> Just a note that if you want to see people not in any congregation you can use a person report "that have congregation = [ don't select any options ]

This actually didn't work, but now it does, following the fix to #701

**Comment by tbar0970** [comment]
Point 2 (issue title) is now fixed. Can you create separate issues if the other requests are still live.
