### ISSUE TITLE
Make note comments compulsory when changing status from 'action required' to something else.

### ISSUE THREAD

**Issue by tbar0970** [tbar0970/jethro-pmm#920]
When you create a person/family note, you'll often set the 'status' to "action required". Eg "call to follow up absence" - "requires action".  When the action is done, you'll change the status to "complete", etc.

Jethro doesn't store or display a history of who changed the status and when. This means that, for a note that required action but is now complete, it's not always clear who completed the action or when, unless comments have been added along the way.

It'd be ideal for Jethro to keep a complete history of who changed the note status.  But as a quicker solution, we could make it compulsory to add a comment when changing the status from "action required" to something else.  Eg when changing from "requires action" to "complete", the user enters a comment "Spoke today, they've been sick, recovering now" and it's clear how the note was resolved.  Many users will do this already, but adding the rule means it becomes a standard.

In theory this could be a config setting, but actually I think it's fair to make it a hard-coded rule.

**Comment by tbar0970** [comment]
Open to input

**Comment by jefft** [comment]
Good idea.
