### ISSUE TITLE
Error when deleting last tag in the tag manger

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#923]
In the tag manager (service components), when I trash the last remaining tag and hit 'save' Jethro throws an error. 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 
Line 33 of .../public_html/views/view_0_manage_service_component_tags.class.php](http://jethro......au/public_html/views/view_0_manage_service_component_tags.class.php)

USER:       1 
REFERER:    https://jethro.......au/?view=_manage_service_component_tags
USER_AGENT: .....

REQUEST: 
Array
(
   [view] => _manage_service_component_tags
   [tagname] => Array
       (
           [_new_] => Array
               (
                   [0] => 
                   [1] => 
               )

       )

)

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => //public_html/views/view_0_manage_service_component_tags.class.php](http://...../public_html/views/view_0_manage_service_component_tags.class.php)
           [line] => 33
           [function] => query
           [class] => PDO
           [type] => ->
       )

   [1] => Array
       (
           [file] => //public_html/include/system_controller.class.php](http://..../public_html/include/system_controller.class.php)
           [line] => 128
           [function] => processView
           [class] => View__Manage_Service_Component_Tags
           [type] => ->
       )

   [2] => Array
       (
           [file] => //public_html/index.php](http://..../public_html/index.php)
           [line] => 58
           [function] => run
           [class] => System_Controller
           [type] => ->
       )

)

**Comment by tbar0970** [comment]
Same problem straight after you add the first tag. Hmm.
