### ISSUE TITLE
Permit '#' in variable substitutions

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#928]
Say we have a church with two 'Bible reader' roles defined:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/6256f765-2e68-4222-8659-3445248da61c)

Then under Services -> Component Library -> Other, we have a 'Bible Reading' component of our run sheet. We would like its value to become whoever is in the 'Bible reader #1' role for that week, so we use a `%Bible_reader_#1%` variable:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/c789879a-f04b-4240-b664-d9974b22faff)

Then if we have made a roster assignment for 'Bible reader #1' for a given week, and create a service and runsheet for that week containing a 'Bible Reading' component, its value should be auto-filled in the runsheet.

This would work, but the regex which identifies `%...%` variables does not allow `#` symbols. Only uppercase, lowercase and underscores are allowed:

https://github.com/tbar0970/jethro-pmm/blob/df658c37166e7960d3c80303c5a49a6589fb2f1b/db_objects/service.class.php#L470

I think it would be harmless to allow `#` characters, and for that matter, `/` as well, as two symbols often occurring in role names.

**Comment by tbar0970** [comment]
Fair enough. Easy workaround in the meantime is to avoid those symbols :)
