### ISSUE TITLE
2.34.0-RC1 bugs

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#934]
Got
Fatal Error (Exception)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'congregation.print_quantity' in 'field list'

The field has been dropped from the database but is still referenced at line 51 in congregation.class.php

view_10_admin__1_congregations.class.php:54: $class = $congObject->isActive() ? '' : 'archived';
isActive is not defined
Line 61, 64 & 66
Undefined array key "holds_persons"

**Comment by tim-pearce** [comment]
Congregation meeting times seems to be 'not all there'. There seems to be no option to enter the time in the edit congregation view.

**Comment by tbar0970** [comment]
For both these symptoms, I think the cause is you've run the 2.34 database update but actually still have the old code.
See https://github.com/tbar0970/jethro-pmm/blob/v2.34-RC1/db_objects/congregation.class.php
there's no reference to print_quantity.
I checked the download ZIP too.

**Comment by tim-pearce** [comment]
The folder is synchronised with Nextcloud. I think I have managed to mash together the RC1 code with code based against my fork of Jethro!
That said I think I have come across a PHP 8.2 issue which I'll address in the other issue I raised.

**Comment by tim-pearce** [comment]
isActive is still 'missing'!
