### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#936]
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
roster_role.class.php:112
view_3_display_role_description.class.php:48 - change NULL to '' - now I only get 1 role!
view_7_rosters__3_define_roster_roles.class.php:53 - swap NULL and '' on line 52

**Comment by tbar0970** [comment]
> roster_role.class.php:112
can you paste the line this is coming from?  I can't find any calls to strpos in that file.

**Comment by tim-pearce** [comment]
The first one is
`$roles = $GLOBALS['system']->getDBObjectData('roster_role', Array('!details' => '', 'congregationid' => NULL, 'active' => 1), 'AND', 'title');`
The second has
if ($cid == '') $cid = NULL;
$croles = $GLOBALS['system']->getDBObjectData('roster_role', Array('congregationid' => $cid), 'OR', 'active DESC, title ASC');
When we get to getInstancesQueryComps in db_object.class.php:1032 we have this line
$operator = is_array($val) ? 'IN' : (((FALSE === strpos($val, '%')) && (FALSE === strpos($val, '?'))) ? '=' : 'LIKE');

PHP 8.2 gets upset because of the NULL!

My suggested change is to replace that line with
$operator = '=';
if (! ($val == NULL)) {
	$operator = is_array($val) ? 'IN' : (((FALSE === strpos($val, '%')) && (FALSE === strpos($val, '?'))) ? '=' : 'LIKE');
}

**Comment by tbar0970** [comment]
OK thanks. In future can you paste the whole backtrace to make it easy to track down.
