### ISSUE TITLE
'look up postcode' link is broken

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#944]
When entering a new family the 'look up postcode' link does not work. I'm using a mac and tested in both chrome and safari - same result. 

If I hover over the link it is 'https://m.auspost.com.au/view/findpostcode/__SUBURB__'

But I THINK what it needs to be is 'https://auspost.com.au/postcode/__SUBURB__'

**Comment by s4069b** [comment]
I went into the 'settings' table and changed 'POSTCODE_LOOKUP_URL' ... and it works again in Safari and Chrome.

**Comment by tbar0970** [comment]
Great, thanks, I'll save this fix.
