### ISSUE TITLE
Temporary files not deleted

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#947]
Jethro is not great at cleaning up its temporary files. I'm seeing:

```
contactlistXXXXXX
contactlistphotoXXXXX
contactlistphotoXXXXX.jpg
jethro-mc-XXXXXXXXXX
mailchimp_contentXXXXXX
phpXXXXXX.docx
phpXXXXXX.odt
PhpWordXXXXXX
```

Where X is a random letters/number.

E.g. every time I download a .docx of a family contact list (Families -> Contact List -> <show results> -> Download As: DOCX), a new /tmp/contactlistXXXXXX temp file gets created.

**Comment by tbar0970** [comment]
Do you think your PR cleans up most of these, so I can close this issue?

**Comment by jefft** [comment]
The PR doesn't fix most of the tempfiles, but it does fix the `contactlistXXXXXX` ones, which are the largest (as in #949). I'd say the severity is low.

**Comment by jefft** [comment]
Added a PR to delete `/tmp/jethro-mc-TSTAMP` directories that accumulate whenever Mailchimp starts failing.
