### ISSUE TITLE
Run sheet components not visible while dragging and dropping onto runsheet

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#956]
When editing a service runsheet, and dragging a component from the Component Library, the dragged item used to visually move with the mouse cursor:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/92a4aa7a-9d38-4c14-980b-77edb28f2630)

In 2.34.0 dragging items still works, but the song's rectangle doesn't visually move with the mouse:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/6a0327ac-2995-48f7-83d8-d9786aa20e78)

**Comment by jefft** [comment]
Perhaps related to #942?

**Comment by tbar0970** [comment]
This is pretty mysterious, but it's somehow caused by the in-motion object being way offset from the mouse cursor - a few hundred pixels to the right and down. Has the offset parent changed, or something?
