### ISSUE TITLE
Make email separator character configurable to placate Outlook

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#970]
Under Rosters -> Display Roster Assignments, Jethro has an 'Email all assignees' link:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/6ac30d55-d287-4aa3-99a9-583817ec63a5)

This generates a 'mailto:' URL of comma-separated emails. 

Although comma-separated is [correct](https://stackoverflow.com/questions/12120190/what-is-the-best-separator-to-separate-multiple-emails) per rfc6854, Outlook wants semi-colons, and complains:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/f64a77fe-d129-4898-8f3a-815d5bf8898f)

Apparently it is possible to let Outlook use commas, under File -> Options -> Mail -> send messages:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/bdea4a59-748d-4640-a5b0-6f26e5d37783)

It would be nice if the separator were settable in the System Configuration, defaulting to comma, with a note that Jethro instances with primarily Outlook users should set it to semi-colon.

**Comment by tbar0970** [comment]
It's nice that the separator is already settable in the system configuration for this reason :-) 
![image](https://github.com/tbar0970/jethro-pmm/assets/2133676/02e69910-5dfb-42a5-8fc9-b1f13a8dc7c6)
https://github.com/tbar0970/jethro-pmm/issues/48

**Comment by jefft** [comment]
lol thanks :)  Might be useful to add 'Set to ; for Outlook' to the setting description.

**Comment by tim-pearce** [comment]
Looks like an item that should be in the documentation #969
