### ISSUE TITLE
Regression: no longer able to see attendance days when creating/editing a Group

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#971]
When creating a Group, there ought to be an 'Attendance Recording Days' section (assuming the 'Attendance' feature is enabled in Admin -> System Configuration):

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/57fdd364-1319-4c7a-8ed7-45dcc4efde2a)

The 'Attendance Recording Days' section has disappeared in 2.34.0:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/b40494c4-71b0-48e5-9059-1bcacc3b3021)

This makes it impossible to create a new attendable group, or edit the days of attendance for existing groups.

**Comment by jefft** [comment]
The 'Attendance Recording Days' section is being hidden by Javascript, in this line:

https://github.com/tbar0970/jethro-pmm/blame/78fe5920b81c95a71055a3ecd3bfdf19292ef1ca/resources/js/jethro.js#L483

It was added in commit https://github.com/tbar0970/jethro-pmm/commit/68bf2b9fa1683d35b3105bdaf0d6fac46eb507ad when addressing #834. 

A very ugly workaround is to disable Javascript just before loading the page. In chrome, hit F12, ctrl+shift+p and search for 'Javascript' to disable it -- then reload the Add / Edit Group page, and the missing checkboxes will be present.

**Comment by tbar0970** [comment]
Thanks for reporting. That JS is only meant to affect the edit-congregation form. Will fix.

**Comment by tim-pearce** [comment]
I applied the fix manually to my system and it doesn't seem to have made a difference?

**Comment by tim-pearce** [comment]
Is there some sort of 'compile javascript' step? I applied the code for truncated email addresses too and it's not working either.

**Comment by tim-pearce** [comment]
Ok, I found it. There is a js file for each version of Jethro - but how does it get constructed?

**Comment by tbar0970** [comment]
It gets constructed via a packaging script that isn't published.
Best approach for you is to run as a DEV system which doens't use the compiled JS, by deleting include/version.txt

**Comment by tbar0970** [comment]
> I applied the fix manually to my system and it doesn't seem to have made a difference?

You did see that this fix is included in the release https://github.com/tbar0970/jethro-pmm/releases/tag/2.34.1 ?

**Comment by tim-pearce** [comment]
I am on 2.34.0. I am usually a bit slow to upgrade because I have a number of changes (most of which are sitting as outstanding pull requests).
Oddly I just went to Admin->Upgrade and it says 'Your system is up to date on version v2.34.0'!?

**Comment by tbar0970** [comment]
> Oddly I just went to Admin->Upgrade and it says 'Your system is up to date on version v2.34.0'!?

Ah thanks for the heads up. The "v" was missing from the latest tag name. Now fixed.
