### ISSUE TITLE
Order on attendance page has changed

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#975]
The order is now always grouped within member status whereas previously it seems when it was for a group it was grouped within group membership order (or maybe it was just family name order).

**Comment by tim-pearce** [comment]
After some investigation I have added the following to my config.php
define('ATTENDANCE_LIST_ORDER', 'family_name ASC, familyid, ab.`rank` ASC, gender DESC');
The default has 'status ASC' as the first item.

**Comment by tbar0970** [comment]
This setting was removed from the database for security/robustness reasons, and currently needs to be set in the  conf file as above.

**Comment by tim-pearce** [comment]
Another item for 'the documentation' #969
