### ISSUE TITLE
Pasting into email fields strips first 7 characters

### ISSUE THREAD

**Issue by jefft** [tbar0970/jethro-pmm#976]
When creating a Family, there is an Email field. Try pasting '1234567890@gmail.com' into the email field; the first 7 digits are stripped:

![image](https://github.com/tbar0970/jethro-pmm/assets/205995/f7327782-e197-466e-812d-f2e1c225aa55)

Same for Email fields in Person records.

This appears to be some new Javascript validation in 2.34.0, because it doesn't happen in 2.33.0, and it doesn't happen if Javascript is disabled (like #971).

**Comment by tbar0970** [comment]
Ah, this will be related to https://github.com/tbar0970/jethro-pmm/issues/898
